### ISSUE TITLE
keys method return empty array

### ISSUE THREAD

**Issue by lucas-silveira** [luin/ioredis#1002]
When i call await invalidatePrefix, it returned a empty array.

In use:
```js
const cacheKey = `rounds:${page}`;
await Cache.set(cacheKey, rounds);

// Other function
await Cache.invalidatePrefix('rounds');
```

Config:
```js
class Cache {
  constructor() {
    this.redis = new Redis({
      host: process.env.REDIS_HOST,
      port: process.env.REDIS_PORT,
      keyPrefix: 'cache',
    });
  }

  set(key, value) {
    return this.redis.set(key, JSON.stringify(value), 'EX', 60 * 60 * 24);
  }

  async get(key) {
    const cached = await this.redis.get(key);

    return cached ? JSON.parse(cached) : null;
  }

  invalidate(key) {
    return this.redis.del(key);
  }

  async invalidatePrefix(prefix) {
    const keys = await this.redis.keys(`cache:${prefix}:*`);
    const keysWithoutPrefix = keys.map(key => key.replace('cache:', ''));

    return this.redis.del(keysWithoutPrefix);
  }
}
```

Follow error is return:
```js
ReplyError: ERR wrong number of arguments for 'del' command
    at parseError (C:\Users\lugan\Documents\Arquivos\Development\Projects\****\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (C:\Users\lugan\Documents\Arquivos\Development\Projects\****\node_modules\redis-parser\lib\parser.js:302:14) {
  command: { name: 'del', args: [] }
```

**Comment by lucas-silveira** [comment]
I have forget that include two dots (:) in KeyPrefix.
