### ISSUE TITLE
Cluster: CROSSSLOT Keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by klinquist** [luin/ioredis#101]
I'm running redis in cluster mode and am getting this error.

The thing is - I'm not using any mutli-key operations.     No MGET/MSET, no MULTI, no transactions..

I'm running a dozen different services and I'm only getting this error on one of them. I'm using the same SDK with all services, so I'm unsure as to exactly the command causing it.    When I put a console.log in ioredis to try and see the command that gets executed, the previous command is a simple LPUSH.  Previous to that it was an HSET.

Here's the full error stack:
Unhandled rejection ReplyError: CROSSSLOT Keys in request don't hash to the same slot
    at ReplyParser._parseResult (/data/homeboy/node_modules/stringify-rosetta/node_modules/ioredis/lib/parsers/javascript.js:56:14)
    at ReplyParser.execute (/data/homeboy/node_modules/stringify-rosetta/node_modules/ioredis/lib/parsers/javascript.js:175:20)
    at Socket.<anonymous> (/data/homeboy/node_modules/stringify-rosetta/node_modules/ioredis/lib/redis/event_handler.js:90:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)

Maybe ioredis is incorrectly parsing something and redis is interpreting it as a some multi-key op?

**Comment by luin** [comment]
Is it possible to enable `showFriendlyErrorStack` to figure out which line in your code causing the error? Or you may just check the `command` property of the error object(every `ReplyError` has a `command` property showing the command of this error).

Either way I'm going to check the code again today to see whether `lpush` and `hset` are possible to cause this error.

**Comment by klinquist** [comment]
Found the bug, it was on my side, sorry for the trouble!

**Comment by luin** [comment]
Cool! Enjoy ioredis :-)
