### ISSUE TITLE
pipeline queue is not emptied after exec

### ISSUE THREAD

**Issue by renewooller** [luin/ioredis#1011]
Hi, 
When using pipeline multiple times in series, it is apparent the _queue is not being emptied after each call to 'exec'. 

This means that previously pipelined calls are duplicated when exec is called. 

Here's an example which demonstrates the problem and also shows a workaround , by setting the length of the pipeline internal queue to 0 after calling exec.

```
let Redis = require('ioredis')
let util = require('util')
let r = new Redis()
let rp = r.pipeline()

console.log('version ' + process.version)

run_redis()
.catch((err) => {
    console.error(err)
})

async function run_redis() {
    
    console.log("NO PIPELINE")
    console.log(await r.del("testinc").catch())

    console.log(await r.incr("testinc"))
    console.log(await r.incr("testinc"))
    console.log(await r.incr("testinc"))
    console.log(await r.incr("testinc"))
    
    console.log("testinc " +  await r.get("testinc"))
    console.log(await r.del("testinc").catch())


    console.log("PIPELINE")

    await rp.incr("testinc")
    await rp.incr("testinc")
    await rp.incr("testinc")
    await rp.incr("testinc")

    console.log("exec " + await rp.exec())
    console.log("testinc " +  await r.get("testinc"))
    console.log(await r.del("testinc").catch())
    console.log("testinc after deletion " +  await r.get("testinc"))
    console.log("setting other key using pipeline")

    console.log(await r.del("test:other:inc").catch())
    await rp.incr("test:other:inc")
    await rp.incr("test:other:inc")
    await rp.incr("test:other:inc")
    await rp.incr("test:other:inc")

    console.log("exec " + await rp.exec())
    console.log("testinc   (should be null)     :  " +  await r.get("testinc"))
    console.log("test:other:inc                 :  " +  await r.get("test:other:inc"))
    
    console.log(await r.del("testinc").catch())
    console.log(await r.del("test:other:inc").catch())
    
    console.log('and again, clearing the internal queue manually (workaround)');
    rp._queue.length = 0

    await rp.incr("test:other:inc")
    await rp.incr("test:other:inc")
    await rp.incr("test:other:inc")
    await rp.incr("test:other:inc")

    console.log("exec " + await rp.exec())
    console.log("testinc        :  " +  await r.get("testinc"))
    console.log("test:other:inc :  " +  await r.get("test:other:inc"))

    process.exit(0)
}
```

**Comment by renewooller** [comment]
I've also found that the workaround causes a problem: 
```
(node:28039) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
warning.js:18
(node:28039) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at Pipeline.fillResult (/Users/renewooller/software/mono/backend/nl-tune-yards/node_modules/ioredis/built/pipeline.js:40:31)
    at command.promise.then.catch.error (/Users/renewooller/software/mono/backend/nl-tune-yards/node_modules/ioredis/built/pipeline.js:171:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
warning.js:18
(node:28039) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
warning.js:18
(node:28039) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at Pipeline.fillResult (/Users/renewooller/software/mono/backend/nl-tune-yards/node_modules/ioredis/built/pipeline.js:40:31)
    at command.promise.then.catch.error (/Users/renewooller/software/mono/backend/nl-tune-yards/node_modules/ioredis/built/pipeline.js:171:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
warning.js:18
```

**Comment by renewooller** [comment]
New workaround is just to re-instantiate the pipeline each time eg :

rp = r.pipeline()
