### ISSUE TITLE
Syntax Error: Unexpected token A

### ISSUE THREAD

**Issue by andreikun** [luin/ioredis#102]
Hello,

I am trying to implement a real time app by using Lumen + Redis + Nodejs and SocketIO. Thing is that after i got a message from a client via WebSocket, i want to publish it via Redis and catch the message via subscriber in Lumen.

Thing is that when i want to publish a message, i got this strange parsing error.

    socket.on("hello-back", function(message) {
	pub.publish("hello-back", 'Andrei');
    });

Error below:

    /home/vagrant/congredi-api/nodeJs/node_modules/ioredis/lib/parsers/javascript.
    :216
        throw err;
              ^
    SyntaxError: Unexpected token A
        at Object.parse (native)
        at Redis.<anonymous> (/home/vagrant/congredi-api/nodeJs/io.js:20:19)
        at Redis.emit (events.js:118:17)
        at Redis.exports.returnReply (/home/vagrant/congredi-api/nodeJs/node_modul
    /ioredis/lib/redis/parser.js:88:16)
        at ReplyParser.<anonymous> (/home/vagrant/congredi-api/nodeJs/node_modules
    oredis/lib/redis/parser.js:27:10)
        at ReplyParser.emit (events.js:107:17)
        at ReplyParser.send_reply (/home/vagrant/congredi-api/nodeJs/node_modules/
    redis/lib/parsers/javascript.js:281:8)
        at ReplyParser.execute (/home/vagrant/congredi-api/nodeJs/node_modules/ior
     is/lib/parsers/javascript.js:210:14)
        at Socket.<anonymous> (/home/vagrant/congredi-api/nodeJs/node_modules/iore
     s/lib/redis/event_handler.js:90:22)
        at Socket.emit (events.js:107:17)
        at readableAddChunk (_stream_readable.js:163:16)
        at Socket.Readable.push (_stream_readable.js:126:10)
        at TCP.onread (net.js:538:20)

**Comment by luin** [comment]
Looks like you tried to `JSON.parse` a string in the file `/home/vagrant/congredi-api/nodeJs/io.js`(line 20).

**Comment by andreikun** [comment]
Ahh crap. that's my bad. I also have an subscriber.on("pmessage") ... where i do JSON.parse but i forgot that it will enter that closure when i publish from somewhere else. I expected the result in my Lumen installation. Sorry about that and thanks for the tip.
