### ISSUE TITLE
ERR syntax error when using MIGRATE

### ISSUE THREAD

**Issue by franckboudraa** [luin/ioredis#1060]
I got the same issue that is related here : https://github.com/luin/ioredis/issues/534

With the differences that I:
- do not use the COPY arg,
- do use the AUTH arg

ioredis 4.14.1
redis 5.0.7

My query:
`myRedisInstance.migrate(
        '127.0.0.1',
        '6379',
        '',
        7,
        10000,
        'REPLACE',
        'AUTH ' + 'myRedisAuthPassword',
        'KEYS ' + keysToMigrateArray.join(' '),
      )`

The error message:
`ReplyError: ERR syntax error
    at parseError (/home/.../node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/.../node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'migrate',
    args: [
      '127.0.0.1',
      '6379',
      '',
      '7',
      '10000',
      'REPLACE',
      'AUTH myRedisAuthPassword',
      'KEYS b2825f63f9a955d29f58e03bee29b28d 02e95d1db41f5cfba3b91e92753f18d5 226ae8f149ad5b638de38d0a2fbd5f35 bb885c9f67c157dfb87c5bbad41404ae'
    ]
  }
}`

I tried to remove the AUTH arg, I got the same error message.
I tried multiple times with arrays of keys between 10 to 1000 keys, I got the same error every time.

**Comment by franckboudraa** [comment]
The problem may not come from ioredis, as I just saw this Redis issue for MIGRATE command on Redis 5.0.7:
https://github.com/antirez/redis/issues/6881
