### ISSUE TITLE
ioredis + bluebird + 127.0.0.1 = connect ETIMEDOUT

### ISSUE THREAD

**Issue by blat** [luin/ioredis#1074]
I have a weird bug with ioredis.

Here is my sample code:

```
const Redis = require('ioredis');
global.Promise = require('bluebird');
new Redis(6379, '127.0.0.1');
```

Connection fails:

```
Error: connect ETIMEDOUT
    at Socket.<anonymous> (node_modules/ioredis/built/redis/index.js:283:31)
    at Object.onceWrapper (events.js:422:28)
    at Socket.emit (events.js:316:20)
    at Socket._onTimeout (net.js:479:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
```

I'm using:
* node 13.10.1
* ioredis 4.16.0
* bluebird 3.7.2

Those alternatives are working:

```
const Redis = require('ioredis');
new Redis(6379, '127.0.0.1');
```

```
const Redis = require('ioredis');
global.Promise = require('bluebird');
new Redis(6379, 'localhost');
```

**Comment by jehy** [comment]
Seems like https://github.com/luin/ioredis/issues/977

**Comment by luin** [comment]
Closing this in favor of #977.
