### ISSUE TITLE
ReplyError: NOAUTH Authentication required - even if password 100% correct.

### ISSUE THREAD

**Issue by pantuchy** [luin/ioredis#1086]
Hello colleges.

I have issue with authenticated connection to Redis. I set up password in **redis.conf** and in **redis-cli** authentication is passing normally, but in **ioredis** client not. It always throw error: **ReplyError: NOAUTH Authentication required** - even if password is 100% correct. Password is simple for testing of course. Without setting password everything also is OK.

My code:

```
const Redis = require('ioredis')

const client = new Redis({
   host: '127.0.0.1',
   port: 6379,
   db: 0,
   password: 'qwerty',
   enableReadyCheck: true,
   autoResubscribe: true,
   retryStrategy: times => {
      return Math.min(times * 500, 5000)
   }
})

client.on('ready', () => {
   console.log('Redis server is ready.')
})

client.on('error', error => {
   console.log('Error in Redis server: ' + error)
})
```

What could be the problem?
Thank you.

**Comment by luin** [comment]
Hey Maksim, well, I have to say it unlikely to be an issue on ioredis side. Having side that, I would suggest following steps to debug with the issue:

1. Run a redis-cli, invoke `monitor` to log all commands sent to the server.
2. Run your program, to see:
  * whether there're logs printed in redis-cli. that would make sure your program connects to the correct server;
  * find `auth xxx` in the logs, make sure `xxx` is the correct password.

**Comment by pantuchy** [comment]
Thank you for Your response. 

I am running Redis in DEBUG mode, will it be enough? In the beginning of logs (5-th line) is visible, that Auth is sending password **qwerty** which is correct.

Logs:

```
ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +0ms
  ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +119ms
  ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +1ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +2ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> auth([ 'qwerty' ]) +1ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +2ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +1ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +2ms
Redis server is ready.
ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
  ioredis:redis status[127.0.0.1:6379]: connect -> close +4ms
  ioredis:connection reconnect in 2.718281828459045ms +0ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +0ms
  ioredis:redis status[127.0.0.1:6379]: connect -> close +0ms
  ioredis:connection reconnect in 2.718281828459045ms +1ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +1ms
  ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +1ms
  ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +1ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +1ms
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14)
  ioredis:redis status[127.0.0.1:6379]: connect -> close +0ms
  ioredis:connection reconnect in 7.38905609893065ms +3ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +0ms
  ioredis:redis status[127.0.0.1:6379]: connect -> close +0ms
  ioredis:connection reconnect in 7.38905609893065ms +0ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +0ms
  ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +9ms
  ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +1ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +1ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14)
  ioredis:redis status[127.0.0.1:6379]: connect -> close +1ms
  ioredis:connection reconnect in 20.085536923187668ms +13ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +1ms
  ioredis:redis status[127.0.0.1:6379]: connect -> close +0ms
  ioredis:connection reconnect in 20.085536923187668ms +0ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +0ms
  ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +25ms
  ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +1ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14)
  ioredis:redis status[127.0.0.1:6379]: connect -> close +1ms
  ioredis:connection reconnect in 54.598150033144236ms +27ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +0ms
  ioredis:redis status[127.0.0.1:6379]: connect -> close +0ms
  ioredis:connection reconnect in 54.598150033144236ms +0ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +0ms
  ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +58ms
  ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +1ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14)
  ioredis:redis status[127.0.0.1:6379]: connect -> close +1ms
  ioredis:connection reconnect in 148.4131591025766ms +60ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +0ms
  ioredis:redis status[127.0.0.1:6379]: connect -> close +0ms
  ioredis:connection reconnect in 148.4131591025766ms +0ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +0ms
  ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +149ms
  ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +1ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14)
  ioredis:redis status[127.0.0.1:6379]: connect -> close +1ms
  ioredis:connection reconnect in 403.4287934927351ms +151ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +0ms
  ioredis:redis status[127.0.0.1:6379]: connect -> close +0ms
  ioredis:connection reconnect in 403.4287934927351ms +0ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +0ms
  ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +406ms
  ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +1ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +1ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/pol.maksim/Development/nodejs/payflexy/server/notification-service/node_modules/redis-parser/lib/parser.js:302:14)
  ioredis:redis status[127.0.0.1:6379]: connect -> close +1ms
  ioredis:connection reconnect in 1096.6331584284585ms +409ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +0ms
  ioredis:redis status[127.0.0.1:6379]: connect -> close +0ms
  ioredis:connection reconnect in 1096.6331584284585ms +0ms
  ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +0ms
```

**Comment by luin** [comment]
yeah it seems there're three `Redis` instance being created (can tell from the first three lines in the logs), two of which don't have `password` option set.

**Comment by pantuchy** [comment]
> yeah it seems there're three `Redis` instance being created (can tell from the first three lines in the logs), two of which don't have `password` option set.

Thank you so much for Your help. Problem is not in **ioredis** at all. I am using BullMQ with Redis, so BullMQ probably is creating multiple instances of connection or any other problem. 

Thank you.

**Comment by luin** [comment]
np, thanks for using ioredis.

**Comment by SirPhemmiey** [comment]
Just leaving this here for future persons. 

This issue will likely happen if you set a password for Redis while you have an instance already running. So if you're sure that your password is correct, restart the Redis server `brew services stop redis` and `brew services start Redis`. You should not have the issue again.

**Comment by octavian-ene** [comment]
> Just leaving this here for future persons.
> 
> This issue will likely happen if you set a password for Redis while you have an instance already running. So if you're sure that your password is correct, restart the Redis server `brew services stop redis` and `brew services start Redis`. You should not have the issue again.

I'm using redis with bullmq. And the funny part is, if I connect externally from another computer... it works fine. From local computer.... it says this noauth error...

**Comment by aasisdhakal** [comment]
Go to Redis cli and add this command. `CONFIG SET requirepass <password>`
