### ISSUE TITLE
require(...) is not a function at Object.<anonymous>

### ISSUE THREAD

**Issue by Cyral** [luin/ioredis#1101]
Hello, I am getting the following error when using the latest version of `ioredis`. I am having a lot of trouble debugging it because the file `node_modules/ioredis/built/redis.js` does not exist on my local machine (`redis` is instead a folder in `built`), but it does once it is built for production on our CI. (Both dev and prod are docker containers running the same version of node, yarn, etc) I'm really not sure what's happening as this doesn't make any sense, curious if anyone has seen this?

```
/app/node_modules/ioredis/built/redis.js:11
var debug = require('./utils/debug')('ioredis:redis');
                     ^
 
TypeError: require(...) is not a function
    at Object.<anonymous> (/app/node_modules/ioredis/built/redis.js:11:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)

```

**Comment by Cyral** [comment]
This happened after upgrading from version 4.3.0 which _does_ contain redis.js

I realized what is happening is ioredis is used in our common library that is used across many applications. The common library is copied to the various applications in CI, but this operation does not delete the files from the previous copy. This resulted in `redis.js` remaining in the containers, and node tried to load this file instead of `redis/index.js`.
