### ISSUE TITLE
"times" param is incorrect in retryStrategy when "enableReadyCheck" set to false

### ISSUE THREAD

**Issue by qishibo** [luin/ioredis#1111]
version: "4.16.2"

reproduct code: [redis-server auth is '123']
```javascript
const Redis = require('ioredis');

const options = {
  retryStrategy: function(times) {
    console.log('retry......', times);
    return 1000;
  },
  enableReadyCheck: false,
  password: 'wrong password',
};

let client = new Redis(6379, '127.0.0.1', options);
```

result:
```bash
[ioredis] Unhandled error event: ReplyError: ERR invalid password
    at parseError (/home/qii/xxx/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/qii/xxx/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14)
retry...... 1
[ioredis] Unhandled error event: ReplyError: ERR invalid password
    at parseError (/home/qii/xxx/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/qii/xxx/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14)
retry...... 1
[ioredis] Unhandled error event: ReplyError: ERR invalid password
    at parseError (/home/qii/xxx/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/qii/xxx/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14)
retry...... 1
```
as we can see, the `times` passd to retryStrategy is always `1`,
but if I set `enableReadyCheck` to `true`, code works as expeced

**Comment by yuvalhvim** [comment]
Happens to me as well, the exact same scenario with a wrong password.
Is anyone looking into it? 🤔
