### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Connection is closed.

### ISSUE THREAD

**Issue by erdemkosk** [luin/ioredis#1120]
Hello, my redis service is here:
`/* eslint-disable consistent-return */
const Redis = require('ioredis');
const config = require('../config');

const client = new Redis({
  host: config.redis.host,
  port: config.redis.port,
  password: config.redis.password,
});

client.on('connect', () => {
  console.log('[*] Redis connected.');
});

client.on('end', () => {
  console.log('[*] Redis disconnected.');
});

client.on('reconnecting', () => {
  console.log('[*] Redis reconnected.');
});

client.on('error', (error) => {
  console.log(`[*] Redis error:\n${error}`);
});

process.on('SIGINT', () => {
  client.quit();
  console.log('[*] Redis disconnected through app termination (SIGINT).');
});

module.exports = {
  client,
};
`
When ı am trying to use it sometimes throws `(node:833) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at Redis.sendCommand (/Users/erdemkosk/Desktop/Projects/personel/rabbitmq-mail-consumer-server/node_modules/ioredis/built/redis/index.js:578:24)
    at Redis.sismember (/Users/erdemkosk/Desktop/Projects/personel/rabbitmq-mail-consumer-server/node_modules/ioredis/built/commander.js:125:21)
    at checkMailInBlacklist (/Users/erdemkosk/Desktop/Projects/personel/rabbitmq-mail-consumer-server/services/mail.service.js:44:45)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27)`

Acces code here : `async function checkMailInBlacklist({ mailInfo }) {
  let inBlackList = false;

  if (!config.considerBlacklist) {
    return inBlackList;
  }
  // redisService.getClient().SADD('mail_blacklist', 'testme-app@yandex.ru');
  try {
    inBlackList = await redisService.client.sismember('mail_blacklist', mailInfo.email);
  }
  catch (error) {
    inBlackList = await redisService.client.sismember('mail_blacklist', mailInfo.email);
  }

  if (inBlackList) {
    console.log(`[*] ${mailInfo.email} in blacklist !`);
  }

  return inBlackList;
}`

**Comment by osukaa** [comment]
It might be that the operation within the `catch()` is failing, I would suggest wrapping both in `try-catch` and see if that helps debug the problem.

```javascript
async function checkMailInBlacklist({ mailInfo }) {
  let inBlackList = false;

  if (!config.considerBlacklist) {
    return inBlackList;
  }
  // redisService.getClient().SADD('mail_blacklist', 'testme-app@yandex.ru');
  try {
    inBlackList = await redisService.client.sismember('mail_blacklist', mailInfo.email);
  } catch () { /* empty */ }

  try {
    inBlackList = await redisService.client.sismember('mail_blacklist', mailInfo.email);
  } catch () { /*empty */ }

  if (inBlackList) {
    console.log(`[*] ${mailInfo.email} in blacklist !`);
  }

  return inBlackList;
}
```

**Comment by erdemkosk** [comment]
Redis could not understand that the connection was broken. I found the solution for everyone who has this problem.

```
client.on('error', (error) => {
  client.disconnect(true);
  console.log(`[*] Redis error:\n${error}`);
});
```
When client.disconnect(true); redis will reconnected.
