### ISSUE TITLE
ioredis in Bull Queue can't connect to redis, but redis-cli works

### ISSUE THREAD

**Issue by microvnhaxor** [luin/ioredis#1171]
version info
ioredis: 4.5.1 ( bull 3.5.1 ) or 4.14.1 ( bul 3.16.0)
node: 11.10 or 12.8.3
OS: alpine docker
redis: 4.0.4 or 6.0.6

I have already read a similar thread, and followed the debug instructions for ioredis. I also tried both the ip address, and also a named host(by defining in /etc/hosts. both result in the same problem. below is an excerpt from the error log

> 2020-07-26T10:34:42.725Z ioredis:redis status[redis:6379]: connecting -> close
2020-07-26T10:34:42.725Z ioredis:connection reconnect in 2.718281828459045ms
2020-07-26T10:34:42.725Z ioredis:redis status[redis:6379]: close -> reconnecting
2020-07-26T10:34:42.726Z ioredis:redis status[redis:6379]: reconnecting -> connecting
2020-07-26T10:34:43.721Z ioredis:redis status[redis:6379]: [empty] -> connecting
2020-07-26T10:34:43.722Z ioredis:redis queue command[redis:6379]: 0 -> info([])
2020-07-26T10:34:43.722Z ioredis:redis status[redis:6379]: [empty] -> connecting
2020-07-26T10:34:43.723Z ioredis:redis queue command[redis:6379]: 0 -> hget([ 'links', 'e2a7d8ee7c5c6186889d77834b4a3c3a' ])
2020-07-26T10:34:44.950Z ioredis:redis status[redis:6379]: [empty] -> connecting
2020-07-26T10:34:44.950Z ioredis:redis queue command[redis:6379]: 0 -> info([])
2020-07-26T10:34:46.553Z ioredis:connection error: Error: connect ETIMEDOUT
    at TLSSocket.<anonymous> (/home/service/node_modules/ioredis/built/redis.js:290:31)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.Socket._onTimeout (net.js:481:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
2020-07-26T10:34:54.605Z ioredis:redis status[redis:6379]: connecting -> close
2020-07-26T10:34:54.605Z ioredis:connection reconnect in 2.718281828459045ms
2020-07-26T10:34:54.605Z ioredis:redis status[redis:6379]: close -> reconnecting
2020-07-26T10:34:54.607Z ioredis:redis status[redis:6379]: reconnecting -> connecting
2020-07-26T10:34:54.975Z ioredis:connection error: Error: connect ETIMEDOUT
    at TLSSocket.<anonymous> (/home/service/node_modules/ioredis/built/redis.js:290:31)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.Socket._onTimeout (net.js:481:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}

**Comment by alex88** [comment]
@microvnhaxor how did you fix this? I think i'm having the same issue

**Comment by evle** [comment]
@microvnhaxor  same here

**Comment by microvnhaxor** [comment]
There is a problem, the connections are not closed. We have 18,000 establish connections.
