### ISSUE TITLE
enableAutoPipelining fails on authorization

### ISSUE THREAD

**Issue by daniluk4000** [luin/ioredis#1238]
When I pass enableAutoPipelining: true, none of my authorization parameters work. 

The error is: 
```
ReplyError: NOAUTH Authentication required.
    at parseError (/Jetbrains/Webstorm/project/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Jetbrains/Webstorm/project/node_modules/redis-parser/lib/parser.js:303:14) {
  command: { name: 'info', args: [] }
}
```

**Works:** 
```typescript
new Redis({
  db: 0,
  host: redisUrl.host,
  port: redisUrl.port,
  password: redisUrl.password,
  enableAutoPipelining: false,
})
```

**NOAUTH Authentication required:** 
```typescript
new Redis({
  db: 0,
  host: redisUrl.host,
  port: redisUrl.port,
  password: redisUrl.password,
  enableAutoPipelining: true,
})
```

**Comment by sj82516** [comment]
The sending command behavior is changed when enableAutoPipelining is true.
```
  ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +7ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +8ms
  ioredis:redis queue command[127.0.0.1:6379]: 0 -> set([ '123', '123' ]) +7ms
  ioredis:redis queue command[127.0.0.1:6379]: 0 -> auth([ 'foobared' ]) +2ms
```
info command is sent before auth command sent.  

Comparing to enableAutoPipelining is false, which should be correct order.
```
  ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +0ms
  ioredis:redis queue command[127.0.0.1:6379]: 0 -> set([ '123', '123' ]) +3ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +17ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> auth([ 'foobared' ]) +1ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +2ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +7ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> set([ '123', '123' ]) +0ms
```

**Comment by DmitrySergeyev** [comment]
Temporary solution, probably, can be in manually adding "auth" command in auto pipelining ignored command list 

```
...
enableAutoPipelining: true,
autoPipeliningIgnoredCommands: ['auth'],
...
```

**Comment by bungambohlah** [comment]
same issue here, any update of this issue?

**Comment by Manghud** [comment]
> Temporary solution, probably, can be in manually adding "auth" command in auto pipelining ignored command list
> 
> ```
> ...
> enableAutoPipelining: true,
> autoPipeliningIgnoredCommands: ['auth'],
> ...
> ```

Is there an alternative for Typescript users? Seems like the `autoPipeliningIgnoredCommands` flag is not supported yet

**Comment by Paul-Isache** [comment]
Are you still able to reproduce the error? If so can you please provide additional informations.

I am not able to reproduce it.

**Comment by simoneb** [comment]
This issue was fixed in https://github.com/luin/ioredis/pull/1242

**Comment by daniluk4000** [comment]
Great.
