### ISSUE TITLE
We got the error of `All keys in the pipeline should belong to the same slots allocation group` when enableAutoPipelining set true

### ISSUE THREAD

**Issue by yunnysunny** [luin/ioredis#1248]
The error stack is below:
```javascript
    at Pipeline.exec (/myapp/node_modules/ioredis/built/pipeline.js:250:29)
    at executeAutoPipeline (/myapp/node_modules/ioredis/built/autoPipelining.js:41:14)
    at /myapp/node_modules/ioredis/built/autoPipelining.js:59:13
    at tryCatcher (/myapp/node_modules/standard-as-callback/built/utils.js:11:23)
    at /myapp/node_modules/standard-as-callback/built/index.js:19:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
When update our version to 4.19.2 and set `enableAutoPipelining` true, the error come up. It make us annoying. And then we disabled the `enableAutoPipelining`, the error dismissing.

We also met with an uncaught exception that make the process exited:
```javascript
TypeError: Cannot read property 'Symbol(callbacks)' of undefined
    at Immediate.executeAutoPipeline (/myapp/node_modules/ioredis/built/autoPipelining.js:39:31)
    at processImmediate (internal/timers.js:441:21)
```
It increased our determination to disable `enableAutoPipelining`.

**Comment by simoneb** [comment]
Can you please provide a reproduction for this issue? A code example would work. Thanks

**Comment by Paul-Isache** [comment]
Checked on latest version of ioredis ,4.22.0 down to 4.19.0, with 2 master and 3 slaves, and I am not able to reproduce it.
