### ISSUE TITLE
IORedis : TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Abhi-Codes** [luin/ioredis#1273]
I am using express with ioredis and http proxy middleware . My use case is to first get the results from redis , if not found in redis , proxy it to an API which will return the results . Everything works fine , but when the Redis connection is not available , I would like to proxy to my API instead of returning redis error . 

```
const express = require("express");
const { createProxyMiddleware } = require("http-proxy-middleware");
const config = require("../config");
const client = require("../helpers/init_redis.js");
const Logger = require("../logger");
const verifyToken = require("../middleware/verifyToken");

const drupal_host_url = config.drupal_host_url;
const drupalLogger = new Logger("drupal");
const router = express.Router();

// Function to retrieve string data from cache
function cachestring(req, res, next) {
  const url = req.url;
  var pos = url.indexOf("?");
  console.log(req.private);
  var type = req.private == true ? "private" : "public";
  var cachekey = url.slice(0, pos).concat(type);
  console.log(cachekey);
  client.get(cachekey, (err, data) => {
    if (err) {

      // How should I handle errors and move on to proxy middleware . As you see below , I am sending the below error response , but instead of doing that , If I call next() , I get the below error     
      // res.status(500).json({
      //   error: err.name,
      //   error_description: err.message,
      // });
      // return;
    }
    if (data && data !== null) {
      drupalLogger.info("<<<< Found in Cache >>>>");
      console.log(typeof data);
      res.send(data);
    } else {
      drupalLogger.info("<<<< Not Found in Cache >>>>");
      next();
    }
  });
}

function customPathRewrite() {
  return (path, req) => {
    console.log(req.private);
    console.log(path);
    if (req.private == true) {
      path.replace("/drupal", "").concat("&type=private");
      console.log(path);
      return path;
    } else {
      path = path.replace("/drupal", "").concat("&type=public");
      console.log(path);
      return path;
    }
  };
}

function onProxyRes(proxyResponse, request, response) {
  delete proxyResponse.headers["x-powered-by"];
  delete proxyResponse.headers["x-generator"];
  delete proxyResponse.headers["server"];
}

router.get(
  "*",
  verifyToken,
  cachestring,
  createProxyMiddleware({
    target: drupal_host_url,
    changeOrigin: true,
    onProxyRes: onProxyRes,
    pathRewrite: customPathRewrite(),
  })
);

module.exports = router;
```
```
/Users/anandabhishe/gitlab/wellness/wellbeing-proxy/node_modules/standard-as-callback/built/index.js:6
        throw e;
        ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/anandabhishe/gitlab/wellness/wellbeing-proxy/routes/drupal.js:29:16
    at tryCatcher (/Users/anandabhishe/gitlab/wellness/wellbeing-proxy/node_modules/standard-as-callback/built/utils.js:11:23)
    at /Users/anandabhishe/gitlab/wellness/wellbeing-proxy/node_modules/standard-as-callback/built/index.js:30:51
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Abhi-Codes** [comment]
not an issue
