### ISSUE TITLE
Unhandled error event: Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by birdwell** [luin/ioredis#1331]
I'm using nodejs with the following code.

```
import Redis from "ioredis";

const client = new Redis(process.env.HEROKU_REDIS_YELLOW_URL, {
	tls: {
		rejectUnauthorized: false,
	},
});
```

With the following log errors in heroku,
```
Apr 08 17:17:45 app/web.1 [ioredis] Unhandled error event: Error: connect ETIMEDOUT
Apr 08 17:17:45 app/web.1     at TLSSocket.<anonymous> (/app/node_modules/ioredis/built/redis/index.js:308:37)
Apr 08 17:17:45 app/web.1     at Object.onceWrapper (events.js:421:28)
Apr 08 17:17:45 app/web.1     at TLSSocket.emit (events.js:315:20)
Apr 08 17:17:45 app/web.1     at TLSSocket.EventEmitter.emit (domain.js:467:12)
Apr 08 17:17:45 app/web.1     at TLSSocket.Socket._onTimeout (net.js:483:8)
Apr 08 17:17:45 app/web.1     at listOnTimeout (internal/timers.js:554:17)
Apr 08 17:17:45 app/web.1     at processTimers (internal/timers.js:497:7)
```

**Comment by luin** [comment]
ETIMEDOUT errors are raised directly from Node.js. Can you access your sever via redis-cli? redis-cli -h yourserverhost.

**Comment by Khauri** [comment]
@luin I'm also experiencing this issue.

Running this _locally_ I can confirm that

```js
new Redis();
```

works fine, and so does...

```js
new Redis(REDIS_CONNECTION_STRING)
```

but supplying tls, even if it's an empty object...

```js
new Redis(REDIS_CONNECTION_STRING, {tls: {}});
```

appears to cause an `Error: connect ETIMEDOUT` error. It doesn't seem to matter if the connection string starts with `redis://`, `rediss://` or is simply `undefined`.

**Comment by kasvith** [comment]
Im having the same problem. This is a critical one though

**Comment by kasvith** [comment]
FYI I used following to avoid the error. But it should be done by the package itself

```ts
function getRedisUrlConfig(url: string, opts: RedisOptions): RedisOptions {
  const { port, hostname, password, pathname } = new URL(url);
  const db = pathname.startsWith('/') ? Number(pathname.split('/')[1]) : 0;
  const baseOpts = {
    port: Number(port),
    host: hostname,
    password,
    db,
  };

  if (!url.startsWith('rediss://')) {
    const { tls: _, ...rest } = opts;
    return { ...baseOpts, ...rest };
  }

  return { ...baseOpts, ...opts };
}
```

**Comment by fewbadboy** [comment]
Today when I use Nuxt set nitro storage  in  nuxt.config,ts file, also has same error.
nuxt version 3.0.0
the test redis version 7.
document part:  [Server Storage](https://nuxt.com/docs/guide/directory-structure/server#server-storage) 

remove the `tsl: {}` can  fix the error: connect ETIMEDOUT
