### ISSUE TITLE
Unhandled error event: Error: read ECONNRESET after v4.27.0 using Sentinel

### ISSUE THREAD

**Issue by fractalawareness** [luin/ioredis#1346]
After this PR https://github.com/luin/ioredis/pull/1328 I started to get multiple ECONNRESET errors when using Sentinel:

> ioredis:redis status[xx.xx.xxx.xxx:26379]: reconnecting -> connecting +15s
> ioredis:redis status[xx.xx.xxx.xxx:26379]: connecting -> connect +31ms
> ioredis:redis status[xx.xx.xxx.xxx:26379]: connect -> ready +0ms
> **ioredis:connection subscribe 1 channels +40s**
> **ioredis:redis write command[xx.xx.xxx.xxx:26379]: 0 -> subscribe([ '+switch-master' ]) +0ms**
> ioredis:redis status[yyy.yy.yy.y:26379]: reconnecting -> connecting +20s
> ioredis:redis status[zzz.zzz.zz.z:26379]: reconnecting -> connecting +0ms
> ioredis:redis status[qqq.qq.qq.q:26379]: reconnecting -> connecting +0ms
> ioredis:redis status[yyy.yy.yy.y:26379]: connecting -> connect +1ms
> ioredis:redis status[yyy.yy.yy.y:26379]: connect -> ready +0ms
> **ioredis:connection resend 1 unfulfilled commands +20s**
> **ioredis:redis write command[yyy.yy.yy.y:26379]: 0 -> subscribe([ '+switch-master' ]) +0ms**
> ioredis:redis status[zzz.zzz.zz.z:26379]: connecting -> connect +0ms
> ioredis:redis status[zzz.zzz.zz.z:26379]: connect -> ready +0ms
> **ioredis:connection resend 1 unfulfilled commands +0ms**
> **ioredis:redis write command[zzz.zzz.zz.z:26379]: 0 -> subscribe([ '+switch-master' ]) +0ms**
> ioredis:redis status[qqq.qq.qq.q:26379]: connecting -> connect +1ms
> ioredis:redis status[qqq.qq.qq.q:26379]: connect -> ready +0ms
> **ioredis:connection resend 1 unfulfilled commands +1ms**
> **ioredis:redis write command[qqq.qq.qq.q:26379]: 0 -> subscribe([ '+switch-master' ]) +0ms**
> **ioredis:connection error: Error: read ECONNRESET +10s**
> **[ioredis] Unhandled error event: Error: read ECONNRESET**
>   **at TCP.onStreamRead (internal/stream_base_commons.js:111:27)**
> **ioredis:connection error: Error: read ECONNRESET +1ms**
> **[ioredis] Unhandled error event: Error: read ECONNRESET**
>   **at TCP.onStreamRead (internal/stream_base_commons.js:111:27)**
> ioredis:redis status[yyy.yy.yy.y:26379]: ready -> close +10s
> **ioredis:connection reconnect in 60000ms +0ms**
> ioredis:redis status[yyy.yy.yy.y:26379]: close -> reconnecting +0ms
> ioredis:redis status[zzz.zzz.zz.z:26379]: ready -> close +0ms
> **ioredis:connection reconnect in 60000ms +0ms**
> ioredis:redis status[zzz.zzz.zz.z:26379]: close -> reconnecting +0ms
> **ioredis:connection error: Error: read ECONNRESET +0ms**
> **[ioredis] Unhandled error event: Error: read ECONNRESET**
>   **at TCP.onStreamRead (internal/stream_base_commons.js:111:27)**
> ioredis:redis status[qqq.qq.qq.q:26379]: ready -> close +0ms
> **ioredis:connection reconnect in 60000ms +0ms**
> ioredis:redis status[qqq.qq.qq.q:26379]: close -> reconnecting +0ms

It doesn't happen on 4.26.0

**Comment by wilsoniya** [comment]
I believe I'm seeing something similar: 

```
[ioredis] Unhandled error event: Error: read ECONNRESET\n","stream":"stderr","time":"2021-06-16T11:09:56.540491082Z
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)\n","stream":"stderr","time":"2021-06-16T11:09:56.540526683Z
    at TCP.callbackTrampoline (internal/async_hooks.js:134:14)\n","stream":"stderr","time":"2021-06-16T11:09:56.540534083Z
```

**Comment by viphehe** [comment]
I believe I'm seeing something similar:
```js 
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
```
on 4.27.5

**Comment by flyingCrp** [comment]
i also got this problem in `4.27.7`;

its look like the connection didnt reconnect when it timeout
