### ISSUE TITLE
[ioredis] Unhandled error event: Error: read ECONNRESET

### ISSUE THREAD

**Issue by SNvMK** [luin/ioredis#1347]
I just installed ioredis, and using it:
```js
client.db = new Redis(process.env.REDIS_URL);
```
process.env.REDIS_URL:
`redis://i-wont-show-password@ec2-52-204-217-245.compute-1.amazonaws.com:8690`

```
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[ioredis] Unhandled error event: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/home/container/node_modules/ioredis/built/redis/event_handler.js:176:37)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:673:12)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
```
And it is showing just eternal. What am i doing wrong?

**Comment by luin** [comment]
`ECONNRESET` is a network error so can you check whether the server URL is accessible?
