### ISSUE TITLE
Looping on ERR max number of clients reached

### ISSUE THREAD

**Issue by PaddyOl** [luin/ioredis#1348]
Using version ioredis@4.27.2 (but problems also in older version, can't say since when):

Error: Command queue state error. If you can reproduce this, please report it. Last error: ERR max number of clients reached
            at DataHandler.shiftCommand (/myApp/node_modules/ioredis/built/DataHandler.js:164:27)
            at DataHandler.returnError (/myApp/node_modules/ioredis/built/DataHandler.js:33:27)
            at JavascriptRedisParser.returnError (/myApp/node_modules/ioredis/built/DataHandler.js:15:22)
            at JavascriptRedisParser.execute (/myApp/node_modules/redis-parser/lib/parser.js:542:14)
            at Socket.<anonymous> (/myApp/node_modules/ioredis/built/DataHandler.js:25:20)
            at Socket.emit (events.js:314:20)
            at addChunk (_stream_readable.js:297:12)
            at readableAddChunk (_stream_readable.js:272:9)
            at Socket.Readable.push (_stream_readable.js:213:10)
            at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
            at TCP.callbackTrampoline (internal/async_hooks.js:126:14)

loops ...

my config of redis client:
{
sentinels:[
{host : '1.1.1.1', port : 26379 },
{host : '2.2.2.2', port : 26379 },
{host : '3.3.3.3', port : 26379 },
],
name: 'mymaster',
options: {
enableOfflineQueue: false,
password: '*******',
connect_timeout: 10000
},
}

Can't see in my logs what has triggered this activity ...

**Comment by keshav-gaur** [comment]
@luin  I'm also facing the similar issue and I checked the client list those were all from my production servers

**Comment by keshav-gaur** [comment]
@luin I have increased the limit already and has set that to 25000
but still I reach a point where number of clients reach the threshold.

**Comment by luin** [comment]
> @luin I have increased the limit already and has set that to 25000
> 
> but still I reach a point where number of clients reach the threshold.

Sounds like there should be some usage issues? A typical web application would only have 1 connection per Node.js process so I think you need to find the cause why there are so many connections.

**Comment by keshav-gaur** [comment]
@luin I have created a singleton class which returns only one client and I use that to call redis functions,
Do I explicitly have to quit the client connection?

**Comment by keshav-gaur** [comment]
@luin I went through the example and I'm using redis in the similar manner.

**Comment by luin** [comment]
@keshav-gaur Nothing comes to my mind. The code looks correct so I assume there should be somewhere else that also creates Redis connections. You can try to assign the connection a name to debug this.

**Comment by keshav-gaur** [comment]
okay @luin thanks,
I will check this possibility also.
