### ISSUE TITLE
Error: All sentinels are unreachable. Retrying from scratch after 50ms. Last error: Connection is closed.

### ISSUE THREAD

**Issue by 247521776** [luin/ioredis#1364]
my code:

```
const Redis = require("ioredis");

const redis = new Redis(
    {
        sentinels: [
            {
                host: "127.0.0.1",
                port: 26379,
            },
            {
                host: "127.0.0.1",
                port: 26380,
            },
            {
                host: "127.0.0.1",
                port: 26381,
            },
        ],
        name: "mymaster",
    }
);
redis.on("error", function (err) {
    console.log("======================");
    console.log(err);
    console.log("======================");
});
const key = "12345";

(async () => {
    const result = await redis.get(key);
    const ttl = await redis.ttl(key);

    console.log("======================");
    console.log(result);
    console.log(ttl);
    console.log("======================");

    redis.disconnect();
})();

```

error massage:
```
ioredis:redis status[127.0.0.1:26379]: [empty] -> connecting +43ms
  ioredis:redis queue command[127.0.0.1:26379]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ]) +0ms
  ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:26379 +44ms
  ioredis:redis status[127.0.0.1:26379]: connecting -> close +1ms
  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
  ioredis:redis status[127.0.0.1:26379]: close -> end +0ms
  ioredis:SentinelConnector failed to connect to sentinel 127.0.0.1:26379 because Connection is closed. +43ms
  ioredis:redis status[localhost:26380]: [empty] -> connecting +1ms
  ioredis:redis queue command[localhost:26380]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ]) +0ms
  ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:26380 +6ms
  ioredis:redis status[localhost:26380]: connecting -> close +5ms
  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
  ioredis:redis status[localhost:26380]: close -> end +0ms
  ioredis:SentinelConnector failed to connect to sentinel localhost:26380 because Connection is closed. +6ms
  ioredis:redis status[localhost:26381]: [empty] -> connecting +0ms
  ioredis:redis queue command[localhost:26381]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ]) +1ms
  ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:26381 +5ms
  ioredis:redis status[localhost:26381]: connecting -> close +4ms
  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
  ioredis:redis status[localhost:26381]: close -> end +0ms
  ioredis:SentinelConnector failed to connect to sentinel localhost:26381 because Connection is closed. +5ms
  ioredis:SentinelConnector All sentinels are unreachable. Retrying from scratch after 50ms. Last error: Connection is closed. +0ms
======================
Error: All sentinels are unreachable. Retrying from scratch after 50ms. Last error: Connection is closed.
    at SentinelConnector.<anonymous> (/Users/yanglei01/work/test-demo/node_modules/ioredis/built/connectors/SentinelConnector/index.js:73:31)
    at Generator.next (<anonymous>)
    at /Users/yanglei01/work/test-demo/node_modules/ioredis/built/connectors/SentinelConnector/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/yanglei01/work/test-demo/node_modules/ioredis/built/connectors/SentinelConnector/index.js:4:12)
    at connectToNext (/Users/yanglei01/work/test-demo/node_modules/ioredis/built/connectors/SentinelConnector/index.js:59:37)
    at SentinelConnector.<anonymous> (/Users/yanglei01/work/test-demo/node_modules/ioredis/built/connectors/SentinelConnector/index.js:125:24)
    at Generator.throw (<anonymous>)
    at rejected (/Users/yanglei01/work/test-demo/node_modules/ioredis/built/connectors/SentinelConnector/index.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
======================
```

redis info
![image](https://user-images.githubusercontent.com/13410975/121005933-e84ee700-c7c2-11eb-8701-a86460802c25.png)

redis sentinel info
![image](https://user-images.githubusercontent.com/13410975/121005978-f8ff5d00-c7c2-11eb-9f7f-581d4f1f3da3.png)

**Comment by Abdullah8006** [comment]
Any update on this? I am getting the same error and there doesn't seem to be any fixes!

**Comment by abalam666** [comment]
same here !

**Comment by luin** [comment]
It's can be expected when all sentinel were not available at the moment. If you believe that's not your case, please provide more information for us to investigate.

**Comment by Raman-Raje** [comment]
Getting the same error, any solution to this?

**Comment by Raman-Raje** [comment]
@247521776 @luin @abalam666 I am getting the same issue. Even though all my sentinels are accessible and are running fine.

`import Redis from 'ioredis';

const createRedisClient = () => {
    return new Redis({
        sentinels: [
            { host: "localhost", port: 26380 },
            { host: "localhost", port: 26381 },
            { host: "localhost", port: 26382 }
        ],
        name: "mymaster",
        password: "password",
        sentinelRetryStrategy: (times) => {
            // reconnect after
            return Math.min(times * 50, 2000);
        }
    });
}

const connectRedis = () => {
    const redisClient = createRedisClient();

    // handle events
    redisClient.on('connect', () => console.log('<:: Redis Client Connected'));
    redisClient.on('error', (err) => console.error('<:: Redis Client Error: ', err));


    return redisClient;
}

connectRedis();
`

Error:-

`<:: Redis Client Error:  Error: All sentinels are unreachable. Retrying from scratch after 50ms. Last error: Connection is closed.
    at connectToNext (/Users/raman/Desktop/docker_k8/redissentinal/test/node_modules/ioredis/built/connectors/SentinelConnector/index.js:64:31)
    at connectToNext (/Users/raman/Desktop/docker_k8/redissentinal/test/node_modules/ioredis/built/connectors/SentinelConnector/index.js:117:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
<:: Redis Client Error:  Error: connect ETIMEDOUT
    at Socket.<anonymous> (/Users/raman/Desktop/docker_k8/redissentinal/test/node_modules/ioredis/built/Redis.js:170:41)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
<:: Redis Client Error:  Error: All sentinels are unreachable. Retrying from scratch after 50ms. Last error: Connection is closed.
    at connectToNext (/Users/raman/Desktop/docker_k8/redissentinal/test/node_modules/ioredis/built/connectors/SentinelConnector/index.js:64:31)
    at connectToNext (/Users/raman/Desktop/docker_k8/redissentinal/test/node_modules/ioredis/built/connectors/SentinelConnector/index.js:117:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
<:: Redis Client Error:  Error: connect ETIMEDOUT
    at Socket.<anonymous> (/Users/raman/Desktop/docker_k8/redissentinal/test/node_modules/ioredis/built/Redis.js:170:41)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {

**Comment by sibadhish** [comment]
We have been facing the same issue

**Comment by Marsup** [comment]
Anyone ever found a solution to this?
