### ISSUE TITLE
Unable to establish connection to Elasticache Cluster: Error None of startup nodes is available

### ISSUE THREAD

**Issue by smriti-d** [luin/ioredis#1389]
I've double verified redis client configs and network configs w.r.t the application trying to establish a connection with AWS Elasticache cluster. I'm able to access and query the same cluster using redis-cli. Ioredis logs are quite hard to understand the real cause of the inability to establish the connection. 
Also bumped the timeout of the client and enabled showFriendlyErrorStack, lazyConnect, but nothing helped.
Would really appreciate if someone could throw some light on the issue. 
 ```
2021-07-23T23:21:04.608Z ioredis:cluster:connectionPool Reset with []
2021-07-23T23:21:04.608Z ioredis:cluster:connectionPool Disconnect Z.Z.Z.Z:6379 because the node does not hold any slot
2021-07-23T23:21:04.608Z ioredis:redis status[Z.Z.Z.Z:6379]: wait -> close
2021-07-23T23:21:04.608Z ioredis:connection skip reconnecting since the connection is manually closed.
2021-07-23T23:21:04.608Z ioredis:redis status[Z.Z.Z.Z:6379]: close -> end
2021-07-23T23:21:04.608Z ioredis:cluster:connectionPool Remove Z.Z.Z.Z:6379 from the pool
2021-07-23T23:21:04.609Z ioredis:cluster:subscriber subscriber has left, selecting a new one...
2021-07-23T23:21:04.609Z ioredis:redis status[Z.Z.Z.Z:6379 (ioredisClusterSubscriber)]: wait -> close
2021-07-23T23:21:04.609Z ioredis:connection skip reconnecting since the connection is manually closed.
2021-07-23T23:21:04.609Z ioredis:redis status[Z.Z.Z.Z:6379 (ioredisClusterSubscriber)]: close -> end
2021-07-23T23:21:04.609Z ioredis:cluster:subscriber selecting subscriber failed since there is no node discovered in the cluster yet
2021-07-23T23:21:04.609Z ioredis:cluster status: connecting -> close
 INFO elasticCache elasticCache.js:16 Error connecting RedisCluster, retrying again for: 2216 time in 20000 ms
2021-07-23T23:21:04.609Z ioredis:cluster status: close -> reconnecting

2021-07-23T23:21:04.610Z ioredis:cluster Got error Error: None of startup nodes is available
    at Cluster.closeListener (/usr/local/BP/local_modules/veutils/node_modules/ioredis/built/cluster/index.js:171:28)
    at Object.onceWrapper (events.js:421:28)
    at Cluster.emit (events.js:327:22)
    at Cluster.EventEmitter.emit (domain.js:467:12)
    at /usr/local/BP/local_modules/veutils/node_modules/ioredis/built/cluster/index.js:330:18
    at processTicksAndRejections (internal/process/task_queues.js:75:11) when reconnecting. Ignoring...
2021-07-23T23:21:12.264Z ioredis:cluster Cluster is disconnected. Retrying after 20000ms
2021-07-23T23:21:12.264Z ioredis:cluster status: reconnecting -> connecting
2021-07-23T23:21:12.287Z ioredis:cluster resolved hostname redis-cluster.clustercfg.use1.cache.amazonaws.com to IP X.X.X.X
2021-07-23T23:21:12.287Z ioredis:cluster:connectionPool Reset with [ { host: 'X.X.X.X', port: 6379 } ]
2021-07-23T23:21:12.287Z ioredis:cluster:connectionPool Connecting to X.X.X.X:6379 as master
2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379]: [empty] -> wait
2021-07-23T23:21:12.288Z ioredis:cluster:subscriber a new node is discovered and there is no subscriber, selecting a new one...
2021-07-23T23:21:12.288Z ioredis:cluster:subscriber selected a subscriber X.X.X.X:6379
2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379 (ioredisClusterSubscriber)]: [empty] -> wait
2021-07-23T23:21:12.288Z ioredis:cluster getting slot cache from X.X.X.X:6379
2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379 (ioredisClusterRefresher)]: [empty] -> wait
2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379 (ioredisClusterRefresher)]: wait -> connecting
2021-07-23T23:21:12.288Z ioredis:redis queue command[X.X.X.X:6379 (ioredisClusterRefresher)]: 0 -> cluster([ 'slots' ])
2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379 (ioredisClusterSubscriber)]: wait -> close
2021-07-23T23:21:12.288Z ioredis:connection skip reconnecting since the connection is manually closed.
2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379 (ioredisClusterSubscriber)]: close -> end
2021-07-23T23:21:12.288Z ioredis:cluster:subscriber selected a subscriber X.X.X.X:6379
2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379 (ioredisClusterSubscriber)]: [empty] -> wait
2021-07-23T23:21:12.288Z ioredis:cluster:subscriber started
 ERROR elasticCache elasticCache.js:33 Error 
{
    "lastNodeError": {}
}
```

**Comment by smriti-d** [comment]
> I've double verified redis client configs and network configs w.r.t the application trying to establish a connection with AWS Elasticache cluster. I'm able to access and query the same cluster using redis-cli. Ioredis logs are quite hard to understand the real cause of the inability to establish the connection.
> Also bumped the timeout of the client and enabled showFriendlyErrorStack, lazyConnect, but nothing helped.
> Would really appreciate if someone could throw some light on the issue.
> 
> ```
> 2021-07-23T23:21:04.608Z ioredis:cluster:connectionPool Reset with []
> 2021-07-23T23:21:04.608Z ioredis:cluster:connectionPool Disconnect Z.Z.Z.Z:6379 because the node does not hold any slot
> 2021-07-23T23:21:04.608Z ioredis:redis status[Z.Z.Z.Z:6379]: wait -> close
> 2021-07-23T23:21:04.608Z ioredis:connection skip reconnecting since the connection is manually closed.
> 2021-07-23T23:21:04.608Z ioredis:redis status[Z.Z.Z.Z:6379]: close -> end
> 2021-07-23T23:21:04.608Z ioredis:cluster:connectionPool Remove Z.Z.Z.Z:6379 from the pool
> 2021-07-23T23:21:04.609Z ioredis:cluster:subscriber subscriber has left, selecting a new one...
> 2021-07-23T23:21:04.609Z ioredis:redis status[Z.Z.Z.Z:6379 (ioredisClusterSubscriber)]: wait -> close
> 2021-07-23T23:21:04.609Z ioredis:connection skip reconnecting since the connection is manually closed.
> 2021-07-23T23:21:04.609Z ioredis:redis status[Z.Z.Z.Z:6379 (ioredisClusterSubscriber)]: close -> end
> 2021-07-23T23:21:04.609Z ioredis:cluster:subscriber selecting subscriber failed since there is no node discovered in the cluster yet
> 2021-07-23T23:21:04.609Z ioredis:cluster status: connecting -> close
> INFO elasticCache elasticCache.js:16 Error connecting RedisCluster, retrying again for: 2216 time in 20000 ms
> 2021-07-23T23:21:04.609Z ioredis:cluster status: close -> reconnecting
> 
> 2021-07-23T23:21:04.610Z ioredis:cluster Got error Error: None of startup nodes is available
>    at Cluster.closeListener (/usr/local/BP/local_modules/veutils/node_modules/ioredis/built/cluster/index.js:171:28)
>    at Object.onceWrapper (events.js:421:28)
>    at Cluster.emit (events.js:327:22)
>    at Cluster.EventEmitter.emit (domain.js:467:12)
>    at /usr/local/BP/local_modules/veutils/node_modules/ioredis/built/cluster/index.js:330:18
>    at processTicksAndRejections (internal/process/task_queues.js:75:11) when reconnecting. Ignoring...
> 2021-07-23T23:21:12.264Z ioredis:cluster Cluster is disconnected. Retrying after 20000ms
> 2021-07-23T23:21:12.264Z ioredis:cluster status: reconnecting -> connecting
> 2021-07-23T23:21:12.287Z ioredis:cluster resolved hostname redis-cluster.clustercfg.use1.cache.amazonaws.com to IP X.X.X.X
> 2021-07-23T23:21:12.287Z ioredis:cluster:connectionPool Reset with [ { host: 'X.X.X.X', port: 6379 } ]
> 2021-07-23T23:21:12.287Z ioredis:cluster:connectionPool Connecting to X.X.X.X:6379 as master
> 2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379]: [empty] -> wait
> 2021-07-23T23:21:12.288Z ioredis:cluster:subscriber a new node is discovered and there is no subscriber, selecting a new one...
> 2021-07-23T23:21:12.288Z ioredis:cluster:subscriber selected a subscriber X.X.X.X:6379
> 2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379 (ioredisClusterSubscriber)]: [empty] -> wait
> 2021-07-23T23:21:12.288Z ioredis:cluster getting slot cache from X.X.X.X:6379
> 2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379 (ioredisClusterRefresher)]: [empty] -> wait
> 2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379 (ioredisClusterRefresher)]: wait -> connecting
> 2021-07-23T23:21:12.288Z ioredis:redis queue command[X.X.X.X:6379 (ioredisClusterRefresher)]: 0 -> cluster([ 'slots' ])
> 2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379 (ioredisClusterSubscriber)]: wait -> close
> 2021-07-23T23:21:12.288Z ioredis:connection skip reconnecting since the connection is manually closed.
> 2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379 (ioredisClusterSubscriber)]: close -> end
> 2021-07-23T23:21:12.288Z ioredis:cluster:subscriber selected a subscriber X.X.X.X:6379
> 2021-07-23T23:21:12.288Z ioredis:redis status[X.X.X.X:6379 (ioredisClusterSubscriber)]: [empty] -> wait
> 2021-07-23T23:21:12.288Z ioredis:cluster:subscriber started
> ERROR elasticCache elasticCache.js:33 Error 
> {
>    "lastNodeError": {}
> }
> ```

@luin do you have any insights into the issue?

**Comment by smriti-d** [comment]
> any luck solving this one?

it was due to restricted security groups on the ECS task. After opening the required ports, it worked fine.

**Comment by leejh3224** [comment]
For anyone looking for an answer,

You should either

1.  use same security group assigned to your ElastiCache cluster
2.  make sure security group assigned to your ElastiCache cluster have security group id of your ec2/ecs as source with port 6379 and protocol TCP
