### ISSUE TITLE
Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms.

### ISSUE THREAD

**Issue by IgorKuznetsov93** [luin/ioredis#1390]
Hello. Can you help me with this issue? This already spammed my logs
My connect options:
```
{
 lazyConnect: true,
  sentinels: [
    { host: "xx.xx.x.41", port: 26379 }, { host: "xx.xx.x.42", port: 26379 }, { host: "xx.xx.x.43", port: 26379 },
  ],
  name: "mymaster",
}
```
Version: "ioredis": "4.27.6",
Logs:
```
`2021-07-25 17:44:07.988: 2021-07-25T14:44:07.987Z ioredis:redis status[xx.xx.x.41:6379]: ready -> close
2021-07-25 17:44:07.988: 2021-07-25T14:44:07.988Z ioredis:connection reconnect in 50ms
2021-07-25 17:44:07.988: 2021-07-25T14:44:07.988Z ioredis:redis status[xx.xx.x.41:6379]: close -> reconnecting
2021-07-25 17:44:07.988: 2021-07-25T14:44:07.988Z ioredis:redis status[xx.xx.x.41:6379]: ready -> close
2021-07-25 17:44:07.988: 2021-07-25T14:44:07.988Z ioredis:connection reconnect in 50ms
2021-07-25 17:44:07.988: 2021-07-25T14:44:07.988Z ioredis:redis status[xx.xx.x.41:6379]: close -> reconnecting
2021-07-25 17:44:08.038: 2021-07-25T14:44:08.038Z ioredis:redis status[xx.xx.x.41:6379]: reconnecting -> connecting
2021-07-25 17:44:08.038: 2021-07-25T14:44:08.038Z ioredis:SentinelConnector All sentinels are unreachable. Retrying from scratch after 10ms.
2021-07-25 17:44:08.039: [ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms.
2021-07-25 17:44:08.039:     at SentinelConnector.<anonymous> (/opt/www/company/node_modules/ioredis/built/connectors/SentinelConnector/index.js:73:31)
2021-07-25 17:44:08.039:     at Generator.next (<anonymous>:null:null)
2021-07-25 17:44:08.039:     at /opt/www/company/node_modules/ioredis/built/connectors/SentinelConnector/index.js:8:71
2021-07-25 17:44:08.039:     at new Promise (<anonymous>:null:null)
2021-07-25 17:44:08.039:     at __awaiter (/opt/www/company/node_modules/ioredis/built/connectors/SentinelConnector/index.js:4:12)
2021-07-25 17:44:08.039:     at connectToNext (/opt/www/company/node_modules/ioredis/built/connectors/SentinelConnector/index.js:59:37)
2021-07-25 17:44:08.039:     at SentinelConnector.connect (/opt/www/company/node_modules/ioredis/built/connectors/SentinelConnector/index.js:128:16)
2021-07-25 17:44:08.039:     at /opt/www/company/node_modules/ioredis/built/redis/index.js:282:55
2021-07-25 17:44:08.039:     at new Promise (<anonymous>:null:null)
2021-07-25 17:44:08.039:     at Redis.connect (/opt/www/company/node_modules/ioredis/built/redis/index.js:258:21)
2021-07-25 17:44:08.039:     at Timeout._onTimeout (/opt/www/company/node_modules/ioredis/built/redis/event_handler.js:165:18)
2021-07-25 17:44:08.039:     at listOnTimeout (internal/timers.js:554:17)
2021-07-25 17:44:08.039:     at processTimers (internal/timers.js:497:7)
2021-07-25 17:44:08.039:
2021-07-25 17:44:08.040: 2021-07-25T14:44:08.040Z ioredis:redis status[xx.xx.x.41:6379]: reconnecting -> connecting
2021-07-25 17:44:08.040: 2021-07-25T14:44:08.040Z ioredis:SentinelConnector All sentinels are unreachable. Retrying from scratch after 10ms.
2021-07-25 17:44:08.041: [ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms.
2021-07-25 17:44:08.041:     at SentinelConnector.<anonymous> (/opt/www/company/node_modules/ioredis/built/connectors/SentinelConnector/index.js:73:31)
2021-07-25 17:44:08.041:     at Generator.next (<anonymous>:null:null)
2021-07-25 17:44:08.041:     at /opt/www/company/node_modules/ioredis/built/connectors/SentinelConnector/index.js:8:71
2021-07-25 17:44:08.041:     at new Promise (<anonymous>:null:null)
2021-07-25 17:44:08.041:     at __awaiter (/opt/www/company/node_modules/ioredis/built/connectors/SentinelConnector/index.js:4:12)
2021-07-25 17:44:08.041:     at connectToNext (/opt/www/company/node_modules/ioredis/built/connectors/SentinelConnector/index.js:59:37)
2021-07-25 17:44:08.041:     at SentinelConnector.connect (/opt/www/company/node_modules/ioredis/built/connectors/SentinelConnector/index.js:128:16)
2021-07-25 17:44:08.041:     at /opt/www/company/node_modules/ioredis/built/redis/index.js:282:55
2021-07-25 17:44:08.041:     at new Promise (<anonymous>:null:null)
2021-07-25 17:44:08.041:     at Redis.connect (/opt/www/company/node_modules/ioredis/built/redis/index.js:258:21)
2021-07-25 17:44:08.041:     at Timeout._onTimeout (/opt/www/company/node_modules/ioredis/built/redis/event_handler.js:165:18)
2021-07-25 17:44:08.041:     at listOnTimeout (internal/timers.js:554:17)
2021-07-25 17:44:08.041:     at processTimers (internal/timers.js:497:7)
2021-07-25 17:44:08.041:
2021-07-25 17:44:08.050: 2021-07-25T14:44:08.049Z ioredis:redis status[xx.xx.x.41:26379]: [empty] -> connecting
2021-07-25 17:44:08.050: 2021-07-25T14:44:08.050Z ioredis:redis queue command[xx.xx.x.41:26379]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ])
2021-07-25 17:44:08.050: 2021-07-25T14:44:08.050Z ioredis:redis status[xx.xx.x.41:26379]: [empty] -> connecting
2021-07-25 17:44:08.051: 2021-07-25T14:44:08.051Z ioredis:redis queue command[xx.xx.x.41:26379]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ])
2021-07-25 17:44:08.051: 2021-07-25T14:44:08.051Z ioredis:redis status[xx.xx.x.41:26379]: connecting -> connect
2021-07-25 17:44:08.051: 2021-07-25T14:44:08.051Z ioredis:redis status[xx.xx.x.41:26379]: connect -> ready
2021-07-25 17:44:08.051: 2021-07-25T14:44:08.051Z ioredis:connection send 1 commands in offline queue
2021-07-25 17:44:08.052: 2021-07-25T14:44:08.051Z ioredis:redis write command[xx.xx.x.41:26379]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ])
2021-07-25 17:44:08.052: 2021-07-25T14:44:08.052Z ioredis:redis status[xx.xx.x.41:26379]: connecting -> connect
2021-07-25 17:44:08.052: 2021-07-25T14:44:08.052Z ioredis:redis status[xx.xx.x.41:26379]: connect -> ready
2021-07-25 17:44:08.052: 2021-07-25T14:44:08.052Z ioredis:connection send 1 commands in offline queue
2021-07-25 17:44:08.052: 2021-07-25T14:44:08.052Z ioredis:redis write command[xx.xx.x.41:26379]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ])
2021-07-25 17:44:08.052: 2021-07-25T14:44:08.052Z ioredis:redis write command[xx.xx.x.41:26379]: 0 -> sentinel([ 'sentinels', 'mymaster' ])
2021-07-25 17:44:08.053: 2021-07-25T14:44:08.053Z ioredis:redis write command[xx.xx.x.41:26379]: 0 -> sentinel([ 'sentinels', 'mymaster' ])
2021-07-25 17:44:08.053: 2021-07-25T14:44:08.053Z ioredis:SentinelConnector Updated internal sentinels: [{"host":"xx.xx.x.41","port":26379},{"host":"xx.xx.x.42","port":26379},{"host":"xx.xx.x.43","port":26379}] @1
2021-07-25 17:44:08.053: 2021-07-25T14:44:08.053Z ioredis:SentinelConnector resolved: xx.xx.x.41:6379 from sentinel xx.xx.x.41:26379
2021-07-25 17:44:08.054: 2021-07-25T14:44:08.054Z ioredis:SentinelConnector Updated internal sentinels: [{"host":"xx.xx.x.41","port":26379},{"host":"xx.xx.x.42","port":26379},{"host":"xx.xx.x.43","port":26379}] @1
2021-07-25 17:44:08.054: 2021-07-25T14:44:08.054Z ioredis:SentinelConnector resolved: xx.xx.x.41:6379 from sentinel xx.xx.x.41:26379
2021-07-25 17:44:08.055: 2021-07-25T14:44:08.055Z ioredis:redis status[xx.xx.x.41:6379]: connecting -> connect
2021-07-25 17:44:08.055: 2021-07-25T14:44:08.055Z ioredis:redis write command[xx.xx.x.41:6379]: 0 -> info([])
2021-07-25 17:44:08.055: 2021-07-25T14:44:08.055Z ioredis:redis status[xx.xx.x.41:26379]: ready -> close
2021-07-25 17:44:08.055: 2021-07-25T14:44:08.055Z ioredis:connection skip reconnecting since the connection is manually closed.
2021-07-25 17:44:08.055: 2021-07-25T14:44:08.055Z ioredis:redis status[xx.xx.x.41:26379]: close -> end
2021-07-25 17:44:08.056: 2021-07-25T14:44:08.056Z ioredis:redis status[xx.xx.x.41:6379]: connect -> ready
2021-07-25 17:44:08.057: 2021-07-25T14:44:08.057Z ioredis:redis status[xx.xx.x.41:6379]: connecting -> connect
2021-07-25 17:44:08.057: 2021-07-25T14:44:08.057Z ioredis:redis write command[xx.xx.x.41:6379]: 0 -> info([])
2021-07-25 17:44:08.057: 2021-07-25T14:44:08.057Z ioredis:redis status[xx.xx.x.41:26379]: ready -> close
2021-07-25 17:44:08.057: 2021-07-25T14:44:08.057Z ioredis:connection skip reconnecting since the connection is manually closed.
2021-07-25 17:44:08.058: 2021-07-25T14:44:08.057Z ioredis:redis status[xx.xx.x.41:26379]: close -> end
2021-07-25 17:44:08.059: 2021-07-25T14:44:08.059Z ioredis:redis status[xx.xx.x.41:6379]: connect -> ready`
```

**Comment by XieShangxu** [comment]
Hi @IgorKuznetsov93,

I got the same issue with you, how did you fix it? My ioredis version is 4.27.4

Thanks a lot

**Comment by IgorKuznetsov93** [comment]
I thought I had solved the problem, but no, my logger just broke. Unfortunately, the problem still remains

**Comment by FilippGorbunov** [comment]
Getting the same issue on the same ioredis version. Any update?

**Comment by holooloo** [comment]
I have the same issue
Please fix it

**Comment by AmazingDevTeam** [comment]
IORedis Version: **4.28.5**
Error Line: **node_modules\ioredis\built\redis\index.js:327:37**

![Capture](https://user-images.githubusercontent.com/56999169/158407151-be321193-149c-4b5b-915d-a3f9e07f38e3.PNG)

**Comment by zry754331875** [comment]
l have same problem

**Comment by Alsaheem** [comment]
Hi
Has anyone fixed this issue yet ?
@zry754331875

**Comment by olasundell** [comment]
We're also seeing this issue, quite a few years have gone by now. Any plans on fixing it?

**Comment by luin** [comment]
The error is expected if all your sentinels were not available at that time. More information are helpful for us to debug it further if that's not your case.

**Comment by mahesh-av-qp** [comment]
Our application is not even able to establish the connection the very first time, Setup is pretty simple I am just testing in my local system and I have only one sentinel and one redis instance (both are running on docker

```
 ioredis:redis status[127.0.0.1:26379]: wait -> connecting

 ioredis:redis queue command[127.0.0.1:26379]: 0 -> sentinel([ 'get-master-addr-by-name', 'redis-queue' ])

 ioredis:redis status[127.0.0.1:26379]: connecting -> connect

ioredis:redis status[127.0.0.1:26379]: connect -> ready

 ioredis:connection send 1 commands in offline queue

ioredis:redis write command[127.0.0.1:26379]: 0 -> sentinel([ 'get-master-addr-by-name', 'redis-queue' ])

ioredis:redis write command[127.0.0.1:26379]: 0 -> sentinel([ 'sentinels', 'redis-queue' ])

 ioredis:SentinelConnector Updated internal sentinels: [{"host":"127.0.0.1","port":26379}] @1

 ioredis:SentinelConnector resolved: 192.168.80.2:6379 from sentinel 127.0.0.1:26379

ioredis:redis status[127.0.0.1:26379]: ready -> close

ioredis:connection skip reconnecting since the connection is manually closed.

 ioredis:redis status[127.0.0.1:26379]: close -> end

 ioredis:connection error: Error: connect ETIMEDOUT

at Socket. ioredis/built/Redis.js:170:41)

 at Object.onceWrapper (node:events:627:28)

at Socket.emit (node:events:513:28)

 at Socket._onTimeout (node:net:565:8)

 at listOnTimeout (node:internal/timers:564:17)

 at processTimers (node:internal/timers:507:7) {

 errorno: 'ETIMEDOUT',

 code: 'ETIMEDOUT',

 syscall: 'connect'

 }

 redis connection error!: Error: connect ETIMEDOUT

 at Socket. (

node_modules/ioredis/built/Redis.js:170:41)

 at Object.onceWrapper (node:events:627:28)

 at Socket.emit (node:events:513:28)

 at Socket._onTimeout (node:net:565:8)

 at listOnTimeout (node:internal/timers:564:17)

at processTimers (node:internal/timers:507:7) {
 errorno: 'ETIMEDOUT',

code: 'ETIMEDOUT',

syscall: 'connect'

 }
```

**Comment by silverwind** [comment]
I also observe random timeouts towards redis, with a mix of "All sentinels are unreachable" and generic timeout errors being printed, appear to be completely healthy. Both redis and sentinel are on localhost on Ubuntu 22.04.

The application performs around 1-2k queries per second and the timing of the error event seems completely random, but there are usually around 500-1000 such errors per day:

<img width="1098" alt="image" src="https://github.com/redis/ioredis/assets/115237/3012f4e3-481a-4f56-819a-26408b758838">

I have currently disabled retries via `maxRetriesPerRequest: null`, but will check if enabling those will get rid of the errors. Other options I tried are enabling `enableAutoPipelining` but it had no effect.

**Comment by victor-develop** [comment]
Problem still exists...

**Comment by VikramMaiya** [comment]
Problem still exists. Time to find a good redis client. This issue exists since 6 years. Ioredis team failed to fix this issue.

**Comment by edwing-renteria-garibay** [comment]
I encountered the same problem even from redis insight. And I am trying to use an alternative from ioredis but I have not found any.

Something peculiar is that it only happens when using sentinels, I have tested directly with my master shard and replica (works perfectly).

In another article they make reference to the possible cause being because you don't have a DNS, but I'm a bit lost.

![image](https://github.com/user-attachments/assets/d38a129d-70e0-4692-b579-51568f1084ce)

![image](https://github.com/user-attachments/assets/00b5dc85-938a-4e09-ab16-fb274203425c)

**Comment by maxymapp** [comment]
new IORedis({
  maxRetriesPerRequest: null,
  sentinels: [
    ...
  ],
  name: "mymaster",
  sentinelUsername: "default",
  **password: process.env.SENTINEL_PASSWORD,**
  sentinelPassword: process.env.SENTINEL_PASSWORD,
});

Passing `password` to Redis itself worked for me even though the approach includes Sentinels. Related experience described here: https://stackoverflow.com/questions/36010740/ready-check-failed-noauth-authentication-required

**Comment by edwing-renteria-garibay** [comment]
Hello @maxymapp 
This is the configuration of my sentinel, my user is default and I don't have a password.
 This is the code I am using with ioredis to call the sentinel, I followed your recommendation but I still have the same error :c
![image](https://github.com/user-attachments/assets/659506f9-bfd0-45d9-b664-7b7ba74bc958)

At all times the connection status is “connecting”, and at the sentinel log level I have no reference to this connection attempt.
the ips is from a network generated in docker

const Redis = require('ioredis');
        redisClient = await new Redis({
            sentinels: [
                { host: "172.18.0.2", port: 26379 },
                { host: "172.18.0.3", port: 26380 },
                { host: "172.18.0.4", port: 26381 }
            ],
            name: 'mymaster',
            sentinelPassword: '',
            password:'',
            port: 26379,
            tls: {},
            showFriendlyErrorStack: true,
            maxRetriesPerRequest: null,
            sentinelUsername: "default",
            connectTimeout: 100000,
            sentinelRetryStrategy: (times) => Math.min(times * 1000, 60000),
            retryStrategy: (times) => Math.min(times * 1000, 60000),
            reconnectOnError: (err) => {
                console.log("############", err);
                const targetError = 'READONLY';
                if (err.message.includes(targetError)) {
                    // Only reconnect when the error contains "READONLY"
                    return true;
                }
            },
            //db: 0,
            //preferredSlaves: preferredSlaves,
            //host: "172.18.0.2",
            //role: "master", 
        });
        console.log("### STATUS ### ", await redisClient.status);

**Comment by edwing-renteria-garibay** [comment]
Update,

In spite of my efforts and reviewing several forums I still can't find a solution.
However I don't know if you have gotten the same error, the connection does reach the sentinel (configure a user through an ACL to be sure).

What happens then is that the connection is not maintained even for thousands of seconds, almost immediately breaks completely, hence the timeout errors because it waits for Redis to respond, but it already responded and never gets that log.

![image](https://github.com/user-attachments/assets/4f035cf6-2261-4209-8348-b81cfa674d51)

I share with you the ioredis configuration I have used to reach this conclusion, I hope it helps someone else

`redisClient = await new Redis({
            sentinels: [
                { host: "127.0.0.1", port: 26379 },
                { host: "127.0.0.1", port: 26380 },
                { host: "127.0.0.1", port: 26381 }
            ],
            name: 'mymaster',
            sentinelUsername: "edwing",
            sentinelPassword: "abc123",
            host: "127.0.0.1",
            username: "edwing",
            password: "abc123",
            port: 23679,
            showFriendlyErrorStack: true,
            maxRetriesPerRequest: null,
            sentinelMaxRetryTime: 10000,
            sentinelRetryStrategy: (times) => Math.min(times * 1000, 10000),
            retryStrategy: (times) => Math.min(times * 1000, 10000),
            reconnectOnError: (err) => {
                console.log("############", err);
                const targetError = 'READONLY';
                if (err.message.includes(targetError)) {
                    return true;
                }
            },
            tls: {},
            db: 0,
            keepAlive: 1000,
            role: "master",
            connectTimeout: 10000,
        });`

**Comment by zymon** [comment]
I had the same issue. Addin keepAlive in redis options fix the problem: keepAlive: 15 * 60 * 1000

**Comment by edwing-renteria-garibay** [comment]
Hi @zymon,

I followed your advice, I increased this configuration in the ioredis, additionally I increased the tcp-keepalive in the configuration of the sentinels, master and slave. But I still have the same problem,
Could you share your configuration please?
![image](https://github.com/user-attachments/assets/769456d7-c61e-453e-a1cb-19b51d6c0052)

![image](https://github.com/user-attachments/assets/1c02c9aa-2fb1-4075-b3c4-dc5c4921e4b4)

**Comment by maxymapp** [comment]
> Hi @zymon,
> 
> I followed your advice, I increased this configuration in the ioredis, additionally I increased the tcp-keepalive in the configuration of the sentinels, master and slave. But I still have the same problem, Could you share your configuration please? ![image](https://private-user-images.githubusercontent.com/69475042/375849094-769456d7-c61e-453e-a1cb-19b51d6c0052.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDcwNjcsIm5iZiI6MTcyOTIwNjc2NywicGF0aCI6Ii82OTQ3NTA0Mi8zNzU4NDkwOTQtNzY5NDU2ZDctYzYxZS00NTNlLWExY2ItMTliNTFkNmMwMDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDIzMTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNGFlZjg1OTUzYzUzN2M0OThlMTZkYTgxNjFmYTRkMzhhM2YyYjllZTUzNWY3MzAyNTcxYzNlZDgxYWJkYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZTo_lUWDV8G9O1vtyR-f_3pea6p3ZehhjT-_fANDvKQ)
> 
> ![image](https://private-user-images.githubusercontent.com/69475042/375849278-1c02c9aa-2fb1-4075-b3c4-dc5c4921e4b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDcwNjcsIm5iZiI6MTcyOTIwNjc2NywicGF0aCI6Ii82OTQ3NTA0Mi8zNzU4NDkyNzgtMWMwMmM5YWEtMmZiMS00MDc1LWIzYzQtZGM1YzQ5MjFlNGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDIzMTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNDIwZmU5NmYxMWVjMmRiYThmYmJmNTkxNDJmNDkyZDMxNGE4Y2Y4NzJmNTA3ZWVhZWU2MDM5MTIzMGJlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fs-K4pwoWTWcsSjH10w54z6qorDTAStKQWXSWv9I7u8)

How about not passing `port: 26379` variable at the bottom? 
```
sentinels: [
{ host: "172.18.0.2", port: 26379 },
{ host: "172.18.0.3", port: 26380 },
{ host: "172.18.0.4", port: 26381 }
],
name: 'mymaster',
sentinelPassword: '',
password:'',
port: 26379,
```
You're already specifying port for each sentinel instead, as you should. My guess it's `port: 26379` is for single redis, but you have sentinels[].

**Comment by maxymapp** [comment]
@zymon 
How about not passing `port: 26379` variable at the bottom? 
```
sentinels: [
{ host: "172.18.0.2", port: 26379 },
{ host: "172.18.0.3", port: 26380 },
{ host: "172.18.0.4", port: 26381 }
],
name: 'mymaster',
sentinelPassword: '',
password:'',
port: 26379, <-- remove this line
```
You're already specifying port for each sentinel instead, as you should. My guess  `port: 26379` is for single redis, but you have sentinels[].

**Comment by maxymapp** [comment]
@IgorKuznetsov93 your sentinels should have different ports - each with a unique port. 
Also, try passing `password` and `sentinelPassword` as defined in your sentinel/redis `.conf` files:
```
sentinelUsername: "default",
sentinelPassword: process.env.SENTINEL_PASSWORD,
password: process.env.SENTINEL_PASSWORD,
  ```

**Comment by edwing-renteria-garibay** [comment]
Hi @maxymapp,
I set up the configuration as you recommended, removed the other lines and finally tested the following

 sentinels: [
                { host: "127.0.0.1", port: 26379 },
                { host: "127.0.0.1", port: 26380 },
                { host: "127.0.0.1", port: 26381 }
            ],
            name: 'mymaster',
            username: "edwing",
            password: "abc123",
            sentinelUsername: "edwing",
            sentinelPassword: "abc123",


![image](https://github.com/user-attachments/assets/df0d62da-3460-4355-9872-0d9db454972a)
I keep getting ETIMEDOUT.
On the sentinel side I see that the connection arrives, but it still closes it.
![image](https://github.com/user-attachments/assets/e2b19180-a531-4c30-8e8a-d30ad1d2841e)
On the other hand I share with you the configuration of my sentinel and configuration files

root@ef8f1436e34c:/cluster# cat redis_master.conf
bind 0.0.0.0
protected-mode no
port 6380
tcp-backlog 511
timeout 30000
tcp-keepalive 30000
daemonize no
supervised no
pidfile "/var/run/redis/redis_master.pid"
loglevel debug
logfile "/cluster/logs/redis_master.log"
databases 16
stop-writes-on-bgsave-error yes
rdbchecksum yes
dbfilename "dump.rdb"
dir "/cluster/appendonlydir/"
slave-serve-stale-data yes
slave-read-only yes
repl-diskless-sync no
repl-diskless-sync-delay 0
repl-disable-tcp-nodelay no
slave-priority 100
appendonly yes
appendfilename "appendonly.aof"
appenddirname "appendonlydir"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
lua-time-limit 5000
slowlog-log-slower-than 10000
slowlog-max-len 128
latency-monitor-threshold 0
notify-keyspace-events "xE"
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
hll-sparse-max-bytes 3000
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
aof-rewrite-incremental-fsync yes
maxclients 4064
repl-timeout 180
repl-backlog-size 16kb
replicaof no one
save 60 1
#save ""
maxmemory-policy volatile-lfu
maxmemory 4000000000
aclfile /cluster/logs/users.acl
masteruser edwing
requirepass "abc123"

root@ef8f1436e34c:/cluster# cat sentinel1.conf
# Example sentinel.conf

#Basic configuration+
bind 0.0.0.0
protected-mode no
#port 6381
daemonize no
pidfile "/var/run/redis-sentinel.pid"
loglevel debug
logfile "/cluster/logs/redis_sentinel.log"
dir "/cluster"
sentinel announce-ip "172.18.0.2"
sentinel announce-port 26379
sentinel monitor mymaster 172.18.0.2 6380 2
maxclients 4064
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 60000

sentinel resolve-hostnames yes
timeout 30000
tcp-keepalive 30000
sentinel auth-user mymaster edwing
sentinel auth-pass mymaster abc123
user default on nopass sanitize-payload ~* &* +@all
# Generated by CONFIG REWRITE
port 26379
latency-tracking-info-percentiles 50 99 99.9
user edwing on sanitize-payload #6ca13d52ca70c883e0f0bb101e425a89e8624de51db2d2392593af6a84118090 &* +@all
sentinel myid 55fdc71eb8dcddc3bcd6752c70edc2aa20cf78f5
sentinel config-epoch mymaster 0
sentinel leader-epoch mymaster 0
sentinel current-epoch 0

sentinel known-replica mymaster 172.18.0.4 6380

sentinel known-replica mymaster 172.18.0.3 6380

sentinel known-sentinel mymaster 172.18.0.4 26379 a41b39f393248d2a1208c2b937d9b9997670c96b

sentinel known-sentinel mymaster 172.18.0.3 26379 f22331a095662060ed97b0bb41a423ef20cceac0

-------------------------------------------------------------------

The other interesting point is that I cannot use the IPs of the containers, the network I create is supposed to be exclusive to Redis and is taken by the containers.
172.18.0.1

IP Container 1 -> 172.18.0.2
IP Container 2 -> 172.18.0.3
Container IP 3 -> 172.18.0.4
The error is very different explaining that it fails to connect to the sentinels.

![image](https://github.com/user-attachments/assets/ffa0188c-a64d-447e-ba2a-75723642456c)
![image](https://github.com/user-attachments/assets/1d3c1e72-4fe8-4563-83e0-83cfda55cc0c)

**Comment by maxymapp** [comment]
@edwing-renteria-garibay 
Have you tried connecting to redis directly without sentinel? Just to narrow down the issue.

**Comment by edwing-renteria-garibay** [comment]
Hi @maxymapp,
If I have tried and if I manage to connect to the database, with the port and hostname of the localhost.
But only when I activate the sentinels part is when I get the error.

![image](https://github.com/user-attachments/assets/59152d43-9b79-4aba-8cc2-8cb8f7f464d7)

**Comment by zymon** [comment]
Here's my config that works:

{
   "showFriendlyErrorStack":true,
   "keepAlive":900000,
   "sentinels":[
      {
         "host":"host1",
         "port":20333
      },
      {
         "host":"host2",
         "port":20333
      },
      {
         "host":"host3",
         "port":20333
      },
      {
         "host":"host4",
         "port":20333
      }
   ],
   "name":"main_5333",
   "password":"xxx"
}

**Comment by Kev1ntan** [comment]
any update on this issue?

**Comment by rozaqabdul656** [comment]
any update on this issue?

**Comment by fjqingyou** [comment]
I using ioredis@3.2.1 version, and using tunnel-ssh on dev only, try a custom patch, it's works my env

[ioredis+3.2.2.patch](https://github.com/user-attachments/files/18514512/ioredis%2B3.2.2.patch)

**Comment by juicemia** [comment]
This error can actually happen for a bunch of different reasons and the message doesn't really tell you. I just resolved it for something I was working on and I figured I should share my solution in case it helps anybody, but it might not be the thing that solves your particular issue.

My setup is I'm running a Redis and a sentinel on a remote Docker host. I'm trying to connect to Redis via the sentinel from my Macbook and every way I tried worked except using this library. It turns out, the master's host was set to the container name on my remote host, which wasn't resolvable from my Macbook. However, the error message made it seem like the sentinel was unreachable when in reality it was the underlying Redis that was unreachable.

**Comment by trondhindenes** [comment]
Its insane how badly documented this library is. We found "enableTLSForSentinelMode" deep in a connection file and tried it, and that solved it for us (we use TLS-secured connections)
