### ISSUE TITLE
`mget` with Redis.Cluster and `enableAutoPipelining: true` causes "Error: All the keys in a pipeline command should belong to the same slot"

### ISSUE THREAD

**Issue by TysonAndre** [luin/ioredis#1392]
Discovered while investigating issues similar to ones fixed by https://github.com/luin/ioredis/pull/1391

Any command that affects multiple keys is probably also affected (`exists`/`del` with more than one key, mset, mget, etc)

```js
const IORedis = require('./built');
const process = require('process');
async function main() {
    // Using instructions from https://redis.io/topics/cluster-tutorial
    // redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 --cluster-replicas 0
    const redis = new IORedis.Cluster([{ host: '127.0.0.1', port:7000 }], { enableAutoPipelining: true });
    const results = await Promise.all([
      redis.mget(['v{profile}1', 'v{profile}2', 'v{profile}3', 'v{profile}4']),
      redis.get('b'),
    ]);
    console.log(results);
    process.exit(0);
}
main();
```

```
(node:35846) UnhandledPromiseRejectionWarning: Error: All the keys in a pipeline command should belong to the same slot
    at Pipeline.exec (/path/to/ioredis/built/pipeline.js:248:29)
    at Immediate.executeAutoPipeline (/path/to/ioredis/built/autoPipelining.js:35:14)
    at processImmediate (internal/timers.js:463:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35846) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
```

**Comment by TysonAndre** [comment]
Possibly related to #1264 and #1248.

**Comment by TysonAndre** [comment]
One possible fix would be to check if a command allowed and had multiple keys. The `_iterateKeys` helper method is called (by getKeys, which is called by lib/pipeline.js to check for pipeline consistency) - maybe a similar check should be added to lib/autoPipelining.ts when `client.isCluster` in `shouldUseAutoPipelining`

```ts
// lib/command.ts
  /**
   * Iterate through the command arguments that are considered keys.
   *
   * @param {Function} [transform=(key) => key] The transformation that should be applied to
   * each key. The transformations will persist.
   * @returns {string[]} The keys of the command.
   * @memberof Command
   */
  private _iterateKeys(
    transform: Function = (key) => key
  ): Array<string | Buffer> {
    if (typeof this.keys === "undefined") {
      this.keys = [];
      if (commands.exists(this.name)) {
        const keyIndexes = commands.getKeyIndexes(this.name, this.args);
        for (const index of keyIndexes) {
          this.args[index] = transform(this.args[index]);
          this.keys.push(this.args[index] as string | Buffer);
        }
      }
    }
    return this.keys;
  }
```
