### ISSUE TITLE
Unknown Command 'GEOSEARCH'

### ISSUE THREAD

**Issue by epodol** [luin/ioredis#1443]
When using the GEOSEARCH command, an error is thrown:

```
/home/.../node_modules/redis-parser/lib/parser.js:179
return new ReplyError(string)
           ^

ReplyError: ERR unknown command 'geosearch'
    at parseError (/home/.../node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/.../node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'geosearch',
    args: [
      'example',
      'FROMLONLAT',
      '0',
      '0',
      'BYRADIUS',
      '100',
      'km',
      'ASC'
    ]
  }
}
```

However, the GEORADIUS command and other commands like GET work just fine.

Code that is failing:

```javascript
    logger.info(await redis.georadius("example", 0, 0, 100, "km", "ASC"));
    logger.info(
      await redis.geosearch(
        "example",
        "FROMLONLAT",
        0,
        0,
        "BYRADIUS",
        100,
        "km",
        "ASC"
      )
    );
```

**Comment by luin** [comment]
The cause should be your Redis server doesn't support `GEOSEARCH`. Sorry for the late response.
