### ISSUE TITLE
ENOTFOUND artprod.dev.bloomberg.com

### ISSUE THREAD

**Issue by gustawdaniel** [luin/ioredis#1444]
After `npm install` on master

```
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
npm WARN deprecated fsevents@2.1.2: "Please update to latest v2.3 or v2.2"
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to http://artprod.dev.bloomberg.com/artifactory/api/npm/npm-repos/tslib/-/tslib-1.10.0.tgz failed, reason: getaddrinfo ENOTFOUND artprod.dev.bloomberg.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daniel/.npm/_logs/2021-10-09T16_30_43_704Z-debug.log
```

But this domain `artprod.dev.bloomberg.com` really do not works.

My log file

```
... many Completed in x ms 
1779 timing reifyNode:node_modules/rxjs Completed in 4001ms
1780 timing reify:rollback:createSparse Completed in 1759ms
1781 timing reify:rollback:retireShallow Completed in 0ms
1782 timing command:install Completed in 80025ms
1783 verbose type system
1784 verbose stack FetchError: request to http://artprod.dev.bloomberg.com/artifactory/api/npm/npm-repos/tslib/-/tslib-1.10.0.tgz failed, reason: getaddrinfo ENOTFOUND artprod.dev.bloomberg.com
1784 verbose stack     at ClientRequest.<anonymous> (/Users/daniel/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:110:14)
1784 verbose stack     at ClientRequest.emit (events.js:376:20)
1784 verbose stack     at Socket.socketErrorListener (_http_client.js:475:9)
1784 verbose stack     at Socket.emit (events.js:388:22)
1784 verbose stack     at emitErrorNT (internal/streams/destroy.js:106:8)
1784 verbose stack     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
1784 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
1785 verbose cwd /Users/daniel/pro/hn/ioredis
1786 verbose Darwin 20.6.0
1787 verbose argv "/Users/daniel/.nvm/versions/node/v14.17.0/bin/node" "/Users/daniel/.nvm/versions/node/v14.17.0/bin/npm" "i"
1788 verbose node v14.17.0
1789 verbose npm  v7.22.0
1790 error code ENOTFOUND
1791 error syscall getaddrinfo
1792 error errno ENOTFOUND
1793 error network request to http://artprod.dev.bloomberg.com/artifactory/api/npm/npm-repos/tslib/-/tslib-1.10.0.tgz failed, reason: getaddrinfo ENOTFOUND artprod.dev.bloomberg.com
1794 error network This is a problem related to network connectivity.
1794 error network In most cases you are behind a proxy or have bad network settings.
1794 error network
1794 error network If you are behind a proxy, please make sure that the
1794 error network 'proxy' config is set properly.  See: 'npm help config'
1795 verbose exit 1
```

**Comment by luin** [comment]
Hi @gustawdaniel,

There was an issue in package-lock.json as it contained `http://artprod.dev.bloomberg.com` as your log shows. However, it've been fixed several days ago. Can you pull the latest changes and try again?
