### ISSUE TITLE
ElasticCache thrown a lot of  ECONNRESET and ETIMEDOUT erroes

### ISSUE THREAD

**Issue by ntedgi** [luin/ioredis#1478]
I am using ioredis on ElasticCache I have 2 nodes one  master and one  replica ,

with this configurations

Data tiering: disable 
Engine Version Compatibility: 5.0.6
Multi-AZ : enabled
Auto-failover: enabled

at the last month we started to get a lot of ECONNRESET and ETIMEDOUT errors usually at scale up with new instances 
some of them connected and other falling with this errors

```
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)
```
and 
```
Error: read ETIMEDOUT
     at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
     at TCP.callbackTrampoline (internal/async_hooks.js:131:14)
```

this is our wrapper code 

```

     import IORedis, { KeyType, Ok, ValueType } from 'ioredis';

    import { logger, monitor } from '@utils/logging';

    const { host, port, maxRetriesPerRequest, connectTimeout } = config.get('redis');

    class RedisUtil {
        private redis: IORedis.Redis;

        private static handleError(type: string, key: string, error?: any): void {
            let errorMessage = '';
            switch (type) {
                case 'increment':
                    errorMessage = `Error thrown when trying to increment ${key}`;
                    break;
                case 'ttl':
                    errorMessage = `Error thrown when trying to get ttl for ${key}`;
                    break;
                case 'decrement':
                    errorMessage = `Error thrown when trying to decrement ${key}`;
                    break;
                case 'reset':
                    errorMessage = `Error thrown when trying to reset  ${key}`;
                    break;
            }
            logger.error(error, errorMessage);
            throw new Error(errorMessage);
        }

        constructor() {
            this.initRedis();
        }

        public async set(key: KeyType, value: ValueType, ttl?: number | string): Promise<Ok> {
            try {
                this.notifyDbSet(key, value);
                if (ttl) {
                    return await this.redis.set(key, value, 'EX', ttl);
                }
                return await this.redis.set(key, value);
            } catch (error) {
                logger.error(error, `Redis failed setting key ${key}`);
            }
        }

        public async get(key: KeyType): Promise<any> {
            try {
                this.notifyDbGet(key);
                return await this.redis.get(key);
            } catch (error) {
                logger.error(error, `Redis failed getting value for key ${key}`);
            }
        }

        public async expire(key, expiry): Promise<void> {
            await this.redis.pexpire(key, expiry);
        }

        public increment(key, cb): void {
            this.redis
                .multi()
                .incr(key)
                .pttl(key)
                .exec(async (err, replies) => {
                    if (!Array.isArray(replies)) throw err;
                    const [[incrError, counter], [ttlError, ttl]] = replies;
                    if (incrError) RedisUtil.handleError('increment', key, incrError);
                    if (ttlError) RedisUtil.handleError('ttl', key, ttlError);
                    cb({ counter, ttl });
                });
        }

        public decrement(key, cb): void {
            this.redis
                .multi()
                .decr(key)
                .pttl(key)
                .exec(async (err, replies) => {
                    if (!Array.isArray(replies)) throw err;
                    const [[decrError, _], [ttlError, ttl]] = replies;
                    if (decrError) RedisUtil.handleError('decrement', key, decrError);
                    if (ttlError) RedisUtil.handleError('ttl', key, ttlError);
                    cb({ ttl });
                });
        }

        public async resetKey(key): Promise<void> {
            this.redis.del(key).catch(resetError => {
                if (resetError) RedisUtil.handleError('reset', key, resetError);
            });
        }

        private initRedis(): void {
            this.redis = new IORedis({
                host,
                port,
                enableReadyCheck: true,
                showFriendlyErrorStack: true,
                maxRetriesPerRequest: maxRetriesPerRequest | 3,
                connectTimeout: connectTimeout | 2000
            });
            this.setEventListeners();
        }

        private setEventListeners(): void {
            this.redis.on('connect', () => {
                logger.info(`Redis connection is established. Host: ${host}`);
            });

            this.redis.on('ready', () => {
                logger.info(`Redis is ready`);
            });

            this.redis.on(
                'error',
                (error => {
                    logger.error(error, 'Redis error occurred while trying to connect Redis server');
                    monitor.errorEvent(
                        'Redis error occurred while trying to connect Redis server',
                        `Error: ${error}. Host: ${host}`,
                        ['redis_connection_failure'],
                        null
                    );
                    this.redis.disconnect();
                }).bind(this)
            );

            this.redis.on('close', () => {
                logger.info(`Redis server connection has closed`);
            });

            this.redis.on('end', ms => {
                logger.info(`Redis connection end - connection is failed to establish`);
            });
        }

        private notifyDbGet(key: KeyType): void {
            try {
                monitor.increment('redis_db.get', 1, [`db_host:${host}`]);
            } catch (error) {
                logger.error(error, `failed to notify datadog on redis DB get for key: ${key}`);
            }
        }

        private notifyDbSet(key: KeyType, value: ValueType): void {
            try {
                monitor.increment('redis_db.set', 1, [`db_host:${host}`]);
            } catch (error) {
                logger.error(error, `failed to notify datadog on redis DB set for key: ${key}, value: ${value}`);
            }
        }
    }

    export const redis = new RedisUtil();

```

can you please help ? called it to be related to the latest version releases?
 
```  
this.redis.on('error',(error => {
                logger.error(error, 'Redis error occurred while trying to connect Redis server');
                this.redis.disconnect();
            }).bind(this)
        );
```
what is the best practice, in this case, should I call disconnect when [ECONNRESET,ETIMEDOUT] status code returns?

**Comment by christopher-caldwell** [comment]
I am seeing this as well, after about 4-5 hours of the local server running.

**Comment by savvykir** [comment]
Hello @ntedgi, did you fix that?
