### ISSUE TITLE
Having problems with the package with standard-as-callback?

### ISSUE THREAD

**Issue by dragon3636** [luin/ioredis#1520]
Hi, I hope someone can help me here.
My code runs fine locally but on the development server it crashes. I tried to find solutions everywhere but nothing. Seems to be the problem from the standard-as-callback package by ioredis.
Code:
```
const stream = redisClient.streamScan({
    match: `${TRANSACTION.PREFIX}:*`,
    type: 'hash'
  });
  stream.on('data', async (resultKeys) => {
    // Pause the stream from scanning more keys until we've migrated the current keys.
    stream.pause();
    const removedKeys = [];
    const transactionIds = [];
    for (let i = 0; i < resultKeys.length; i++) {
      let key = resultKeys[i];
      const transaction = await redisClient.hgetall(key);
      const twoBeforeDate = moment().tz(process.env.TIMEZONE).subtract(DAYS_TO_CLEAR_EXPIRE_TRANSACTION, 'days').toDate();
      if (transaction) {
        if (transaction.status === PENDING && new Date(transaction.createdAt) <= twoBeforeDate || transaction.status === PAYING && new Date(transaction.updatedAt) <= twoBeforeDate) {
          removedKeys.push(key);
          transactionIds.push(transaction.id);
        }
      }
    }
    if (_.size(removedKeys)) {
      await Notification.destroy({ transaction: { in: transactionIds } });
      await Transaction.destroy({ id: { in: transactionIds } });
      await redisClient.del(...removedKeys);
    }
    stream.resume();
  });
  stream.on('end', () => {
    console.log('done migration');
  });
```
And the output will be:

```
/home/ubuntu/pueritroc-api/node_modules/standard-as-callback/built/index.js:6
        throw e;
        ^

ReplyError: ERR syntax error
    at parseError (/home/ubuntu/pueritroc-api/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/ubuntu/pueritroc-api/node_modules/redis-parser/lib/parser.js:302:14)
Emitted 'error' event on ScanStream instance at:
    at /home/ubuntu/pueritroc-api/node_modules/ioredis/built/ScanStream.js:38:22
    at tryCatcher (/home/ubuntu/pueritroc-api/node_modules/standard-as-callback/built/utils.js:12:23)
    at /home/ubuntu/pueritroc-api/node_modules/standard-as-callback/built/index.js:33:51
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  command: {
    name: 'scan',
    args: [ '0', 'MATCH', 'transaction:*', 'TYPE', 'hash', 'COUNT', '100' ]
  }
}
```
And debug results. I'm attaching hope it's helpful 
```
ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +0ms
  ioredis:redis queue command[127.0.0.1:6379]: 0 -> info([]) +16ms
  ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +3ms
  ioredis:redis queue command[127.0.0.1:6379]: 0 -> info([]) +1ms
  ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +1ms
  ioredis:redis queue command[127.0.0.1:6379]: 0 -> info([]) +1ms
  ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +0ms
  ioredis:redis queue command[127.0.0.1:6379]: 0 -> info([]) +1ms
  ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +0ms
  ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +373ms
  ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +2ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +6s
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +1ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +14ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +6ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +6ms
  ioredis:connection send 1 commands in offline queue +20ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +4ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +8ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +1ms
  ioredis:connection send 1 commands in offline queue +13ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
  ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +2ms
  ioredis:redis queue command[127.0.0.1:6379]: 0 -> client([ 'setname', 'bull:bm90aWZpY2F0aW9u' ]) +9ms
  ioredis:redis queue command[127.0.0.1:6379]: 0 -> client([ 'setname', 'bull:bm90aWZpY2F0aW9u' ]) +8ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +11ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +1ms
  ioredis:connection send 1 commands in offline queue +31ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +2s
  ioredis:redis write command[127.0.0.1:6379]: 1 -> select([ '1' ]) +2ms
  ioredis:redis write command[127.0.0.1:6379]: 1 -> info([]) +6ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +0ms
  ioredis:redis write command[127.0.0.1:6379]: 3 -> select([ '3' ]) +1ms
  ioredis:redis write command[127.0.0.1:6379]: 3 -> info([]) +2ms
Redis Connection Established:redis://127.0.0.1:6379/3
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +10ms
  ioredis:redis write command[127.0.0.1:6379]: 2 -> select([ '2' ]) +1ms
  ioredis:redis write command[127.0.0.1:6379]: 2 -> info([]) +1ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +78ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +9ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +1ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +126ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +1ms
  ioredis:connection send 2 commands in offline queue +127ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> client([ 'setname', 'bull:bm90aWZpY2F0aW9u' ]) +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> client([ 'setname', 'bull:bm90aWZpY2F0aW9u' ]) +1ms
  ioredis:redis status[127.0.0.1:6379]: [empty] -> connecting +238ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +16ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> subscribe([ 'bull:notification:delayed' ]) +0ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> evalsha('8b912cdc5b4c20108ef73d952464fba3a7470d7b,6,bull:notification:delayed,bull:notification:active,bull:notification:wait,bull:notification:priority,bull:notification:paused,bull:notification:meta-paused,b ... <REDACTED full-length="268">') +2s
  ioredis:redis write command[127.0.0.1:6379]: 0 -> evalsha('ff9c18634832b0b4115a19b4de5f4788a7cfbd4e,7,bull:notification:stalled,bull:notification:wait,bull:notification:active,bull:notification:failed,bull:notification:stalled-check,bull:notification:meta-pau ... <REDACTED full-length="269">') +17ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> evalsha('ff9c18634832b0b4115a19b4de5f4788a7cfbd4e,7,bull:notification:stalled,bull:notification:wait,bull:notification:active,bull:notification:failed,bull:notification:stalled-check,bull:notification:meta-pau ... <REDACTED full-length="269">') +1ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> brpoplpush([ 'bull:notification:wait', 'bull:notification:active', '5' ]) +24ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> brpoplpush([ 'bull:notification:wait', 'bull:notification:active', '5' ]) +1ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> brpoplpush([ 'bull:notification:wait', 'bull:notification:active', '5' ]) +5ms
  ioredis:redis write command[127.0.0.1:6379]: 3 -> scan([ '0', 'MATCH', 'transaction:*', 'TYPE', 'hash', 'COUNT', '100' ]) +4s
```
What is my problem and how do I deal with it?Thank you so much for reading my post :)

**Comment by luin** [comment]
What if you remove `type: 'hash'`? I think the cause is your server doesn't support the argument. It's not related to `standard-as-callback`, it's just what async error stack looks like. Enable `showFriendlyErrorStack` can make the error stack more readable.
