### ISSUE TITLE
All write/read operations result in ReplyError: MOVED exception

### ISSUE THREAD

**Issue by jackvhall** [luin/ioredis#1606]
Hello,

On version `5.0.6` I am trying to connect and utilize a redis cluster running in kubernetes on gcp. The connection is established fine, and even takes commands and allows for event subscriptions. Unfortunately, read/write operations are resulting in errors. Here is the output with `DEBUG=ioredis:*` of some unit tests I was running against the cluster:

```sh
  ● Test Node Service › Test Processing Checkin › Should update and persist node with payload data
    ReplyError: MOVED 6516 10.4.3.190:6379

      at parseError (node_modules/redis-parser/lib/parser.js:179:12)
      at parseType (node_modules/redis-parser/lib/parser.js:302:14)
  ● Test Node Service › Test Processing Checkin › Should update and persist node with payload data
    ReplyError: READONLY You can't write against a read only replica.

      at parseError (node_modules/redis-parser/lib/parser.js:179:12)
      at parseType (node_modules/redis-parser/lib/parser.js:302:14)

  ● Test Node Service › Test Processing Checkin › Should update and persist node with payload data
    ReplyError: MOVED 6516 10.4.3.190:6379
    ReplyError: READONLY You can't write against a read only replica.
  ioredis:redis status[redis-cluster:6379]: wait -> connecting +0msfied interval using correct objects
  ioredis:redis status[redis-cluster:6379]: wait -> connecting +5ms
  ioredis:redis queue command[redis-cluster:6379]: 0 -> CONFIG([ 'SET', 'notify-keyspace-events', 'Ex' ]) +5ms
  ioredis:redis status[10.8.1.62:6379]: connecting -> connect +44ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> info([]) +3ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> subscribe([ '__keyevent@1__:expired' ]) +6ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> get([ 'cluster:1de34dd1-c333-4129-ba2b-0f16f85ff021' ]) +9ms
2022-06-16 00:34:34:3434 error: Error processing checkin: MOVED 5284 10.4.3.189:6379
  ioredis:redis write command[10.8.1.62:6379]: 0 -> get([ 'cluster:foo-hardware-id' ]) +10ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> get([ 'cluster:1de34dd1-c333-4129-ba2b-0f16f85ff021' ]) +10ms
2022-06-16 00:34:34:3434 error: Error processing checkin: MOVED 5284 10.4.3.189:6379
  ioredis:redis write command[10.8.1.62:6379]: 0 -> get([ 'cluster:foo-hardware-id' ]) +5ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> get([ 'cluster:1de34dd1-c333-4129-ba2b-0f16f85ff021' ]) +9ms
2022-06-16 00:34:34:3434 error: Error processing checkin: MOVED 5284 10.4.3.189:6379
  ioredis:redis write command[10.8.1.62:6379]: 0 -> get([ 'cluster:1de34dd1-c333-4129-ba2b-0f16f85ff021' ]) +4ms
2022-06-16 00:34:34:3434 error: Error processing checkin: MOVED 5284 10.4.3.189:6379
  ioredis:redis write command[10.8.1.62:6379]: 0 -> get([ 'cluster:1de34dd1-c333-4129-ba2b-0f16f85ff021' ]) +4ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> get([ 'cluster:foo-hardware-id' ]) +3ms0f16f85ff021' ]) +5ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> get([ 'cluster:1de34dd1-c333-4129-ba2b-0f16f85ff021' ]) +8ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> quit([]) +102ms4 10.4.3.189:6379
 FAIL  src/cluster/__tests__/clusterService.test.tsriber mode +0ms
  Test Node Service
    Test Processing Checkin
      ✕ Should update and persist node with payload data 0 (15 ms)
      ✕ Should update and persist node with payload data 3 (8 ms))
      ✕ Should update and persist node with payload data 4 (7 ms)
      ✕ Should update and persist node with payload data 6 (6 ms)
      ✕ Should write back at specified interval using correct objects (115 ms)

  ● Test Node Service › Test Processing Checkin › Should update and persist node with payload data 0

    ReplyError: MOVED 109 10.4.3.189:6379

      at parseError (node_modules/redis-parser/lib/parser.js:179:12)
      at parseType (node_modules/redis-parser/lib/parser.js:302:14)

  ● Test Node Service › Test Processing Checkin › Should update and persist node with payload data 1

    ReplyError: MOVED 109 10.4.3.189:6379

      at parseError (node_modules/redis-parser/lib/parser.js:179:12)
      at parseType (node_modules/redis-parser/lib/parser.js:302:14)
  ● Test Node Service › Test Processing Checkin › Should update and persist node with payload data 2
  ● Test Node Service › Test Processing Checkin › Should update and persist node with payload data 3
  ● Test Node Service › Test Processing Checkin › Should update and persist node with payload data 4
  ● Test Node Service › Test Processing Checkin › Should update and persist node with payload data 5
  ● Test Node Service › Test Processing Checkin › Should update and persist node with payload data 6
  ioredis:redis status[redis-cluster:6379]: wait -> connecting +0msfied interval using correct objects
  ioredis:redis status[redis-cluster:6379]: wait -> connecting +2ms
  ioredis:redis queue command[redis-cluster:6379]: 0 -> CONFIG([ 'SET', 'notify-keyspace-events', 'Ex' ]) +2ms
  ioredis:redis status[10.8.1.62:6379]: connecting -> connect +5ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> info([]) +1ms
  ioredis:redis status[10.8.1.62:6379]: connect -> ready +5ms
  ioredis:redis status[10.8.1.62:6379]: connect -> ready +2ms +0ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> CONFIG([ 'SET', 'notify-keyspace-events', 'Ex' ]) +2ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> subscribe([ '__keyevent@1__:expired' ]) +4ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> set([ 'foo', '{"foo":"bar"}' ]) +3ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> setex([ 'writeback:node:1234', '1', 'node:1234' ]) +7ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> quit([]) +4ms
  ioredis:redis write command[10.8.1.62:6379]: 0 -> quit([]) +1ms
  ● Test cache service › Should set and read propertiesr mode +0ms
    ReplyError: MOVED 12182 10.4.1.125:6379

      at parseError (node_modules/redis-parser/lib/parser.js:179:12)
      at parseType (node_modules/redis-parser/lib/parser.js:302:14)
```

I am not sure why this is happening. My impression was that the receipt of such a response would result in the client changing hosts to the new node. Also, ignore my test's chatter about `nodes`. `nodes` and `clusters` are part of our domain. Here's my connection code:

```ts
class Cache {
  client: Redis;
  #subscriber: Redis;
  #uri: string = config.redis.uri as string;
  #db: string = config.redis.db as string;
  #registeredHandlers: { [key: string]: (key: string) => void } = {};

  async connect() {
    try {
      this.client = new Redis(this.#uri /* + `/${this.#db}` */);
      this.client.on("error", (err) => Logger.error("Redis Client Error", err));

      const subscriber = new Redis(this.#uri /* + `/${this.#db}` */);
      this.#subscriber = subscriber;
      this.#subscriber.on("error", (err) =>
        Logger.error("Redis Subscriber Error", err)
      );

      // enable expiry events in Redis
      await this.client.sendCommand(
        new Redis.Command(
          "CONFIG",
          ["SET", "notify-keyspace-events", "Ex"],
          {},
          (err, result) => {
            if (err)
              Logger.error(
                "Error enabling keyspace events" + JSON.stringify(err)
              );
            Logger.debug(
              "Redis keyspace events enabled: " +
                JSON.stringify(result.toString())
            );
          }
        )
      );

      this.#subscribe(
        this.#subscriber,
        `__keyevent@${this.#db}__:expired`,
        this.#expireHandler.bind(this)
      );

      Logger.info("Redis connection initialized.");
    } catch (err: unknown) {
      Logger.error(
        "Failed to connect to redis server: " +
          (err instanceof Error ? err.message : JSON.stringify(err))
      );
      throw err;
    }
  }
}
```

Thanks for any help you can give. I'm pretty new to using redis this way, and ioredis as well.

**Comment by jackvhall** [comment]
Looks like I just needed to use a cluster-aware connection in the form of `Redis.Cluster` instead of the default constructor. Thanks!
