### ISSUE TITLE
Timeout errors when load increases 

### ISSUE THREAD

**Issue by ramprasad1996** [luin/ioredis#1613]
Hi, 

We're using a NodeJS-based app using express for routing http requests. Before routing the requests we have a middleware to perform some validation using Redis, wherein we use ioredis. 

When the load is moderate it works fine. But when there is an increase in load, ioredis started throwing timeout errors. 

Error: Command timed out
    at Timeout._onTimeout (/proj/node_modules/ioredis/built/command.js:261:33)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  [stack]: 'Error: Command timed out\n' +
    '    at Timeout._onTimeout (/proj/node_modules/ioredis/built/command.js:261:33)\n' +
    '    at listOnTimeout (internal/timers.js:554:17)\n' +
    '    at processTimers (internal/timers.js:497:7)',
  [message]: 'Command timed out'
}

Initially, we had the command timeout set as 2 seconds. It started throwing the error frequently. Post that we now changed it to 5 seconds. It was better than before, but still, we face the timeout issue when the load increases. 

We didn't find any redis slowlog too. We're using a Kubernetes setup within which we use redis sentinels ( 1 master 2 slaves ) to connect to from the app. 

Any help on this query would be helpful

**Comment by luin** [comment]
Hey @ramprasad1996,

A possible cause could be CPU load was too high so ioredis didn't get enough CPU resource to handle the requests. You may want to monitor CPU load or just increase Node.js processes.

**Comment by marcbachmann** [comment]
How many parallel requests do you expect to handle against redis?
Do you have [Autopipelining](https://github.com/luin/ioredis#autopipelining) enabled? Maybe a high latency against and round trips against redis are causing issues and requests time out before they even get sent to redis?
