### ISSUE TITLE
`Emitted 'error' event on ScanStream instance` on dev/production environment

### ISSUE THREAD

**Issue by NashJames** [luin/ioredis#1651]
I get this error below using scanstream. I've been working to solve this for a couple days, but it's been a difficult one. It works perfectly on my mac locally, but errors when running on the ubuntu server. I've attached the error, the script I wrote to test, and the redis.conf file. I can access it via CLI without trouble, and a rust application making similar use has no trouble. I considered switching dependencies, due to the importance I get this sorted, but I'm not sure scanstream has an equivalent in another package?

Any help is appreciated.

ioredis: 5.0.6
node: v16
redis: v5

```
🚀 Connected to PackageDB: redis://localhost:7000
/home/gb127197/Documents/pkgdb/node_modules/standard-as-callback/built/index.js:6
        throw e;
        ^

ReplyError: ERR syntax error
    at parseError (/home/gb127197/Documents/pkgdb/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/gb127197/Documents/pkgdb/node_modules/redis-parser/lib/parser.js:302:14)
Emitted 'error' event on ScanStream instance at:
    at /home/gb127197/Documents/pkgdb/node_modules/ioredis/built/ScanStream.js:34:22
    at tryCatcher (/home/gb127197/Documents/pkgdb/node_modules/standard-as-callback/built/utils.js:12:23)
    at /home/gb127197/Documents/pkgdb/node_modules/standard-as-callback/built/index.js:33:51
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  command: {
    name: 'scan',
    args: [
      '0',     'MATCH',
      '*go*',  'TYPE',
      'hash',  'COUNT',
      '10000'
    ]
  }
}
```

```js
import Redis from "ioredis"

const REDIS_URL = `redis://localhost:7000`
let packagedb = null

if (packagedb === null) {
  packagedb = new Redis(REDIS_URL)
  packagedb.on("connect", () => {
    console.log(`🚀 Connected to PackageDB: ${REDIS_URL}`)
    searchPackageDb("*go*")
  })
  packagedb.on("error", () =>
    console.log(`Error connecting to PackageDB: ${REDIS_URL}`)
  )
}

const searchPackageDb = async (query) => {
  if (!packagedb) return []
  // Name => Versions
  const results = {}
  const stream = await packagedb.scanStream({
    match: query,
    count: 10000,
    type: "hash",
  })
  await new Promise((res) => {
    stream.on("data", (keys) => {
      stream.pause()
      Promise.all(
        keys.map(async (key) => {
          results[key] = await packagedb.hkeys(key)
        })
      ).then(() => stream.resume())
    })

    stream.on("end", res)
  })

  return Object.entries(results)
    .flatMap(([name, versions]) => ({ name, versions }))
    .slice(0, 100)
}
```

[redis.conf.txt](https://github.com/luin/ioredis/files/9565392/redis.conf.txt)

**Comment by NashJames** [comment]
Also, not sure how helpful it is, but this is the object output from the stream itself. [scanstream.json.txt](https://github.com/luin/ioredis/files/9565817/scanstream.json.txt)

It's worth noting that it was working before. I'm not really not sure what changed, but I do wonder if it was some config with our redis.

**Comment by NashJames** [comment]
Fixed by wiping all the config and installation, and installing redis v7. I never discovered the cause.
