### ISSUE TITLE
ETIMEDOUT error in Redis Sentinel

### ISSUE THREAD

**Issue by saurabh2608** [luin/ioredis#1678]
Hi guys,
I observe a very strange connection issue. I have  setup with 3 Sentinels with Quorum 2 - I have 2 slaves and 1 master.

I have setup my local system using the url [https://medium.com/@talk2amareswaran/redis-sentinel-the-high-availability-for-redis-using-docker-5495e0173559](https://medium.com/@talk2amareswaran/redis-sentinel-the-high-availability-for-redis-using-docker-5495e0173559)

The configuration information of redis sentinel setup is this
` Saurabhs-MacBook-Air:~ saurabh.aggarwal$  redis-cli -p 26379 sentinel master mymaster
 1) "name"
 2) "mymaster"
 3) "ip"
 4) "172.17.0.4"
 5) "port"
 6) "6379"
 7) "runid"
 8) "0106ee869099d1ca47486e99a1c35b9bc055b15f"
 9) "flags"
10) "master"
11) "link-pending-commands"
12) "0"
13) "link-refcount"
14) "1"
15) "last-ping-sent"
16) "0"
17) "last-ok-ping-reply"
18) "992"
19) "last-ping-reply"
20) "992"
21) "down-after-milliseconds"
22) "60000"
23) "info-refresh"
24) "6306"
25) "role-reported"
26) "master"
27) "role-reported-time"
28) "8109173"
29) "config-epoch"
30) "1"
31) "num-slaves"
32) "3"
33) "num-other-sentinels"
34) "2"
35) "quorum"
36) "2"
37) "failover-timeout"
38) "180000"
39) "parallel-syncs"
40) "1"
Saurabhs-MacBook-Air:~ saurabh.aggarwal$ redis-cli -p 26379 INFO sentinel
# Sentinel
sentinel_masters:1
sentinel_tilt:0
sentinel_tilt_since_seconds:-1
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
sentinel_simulate_failure_flags:0
master0:name=mymaster,status=ok,address=172.17.0.4:6379,slaves=3,sentinels=3`

Now  When I have written the code its showing issue, sample code is here
`const Redis = require("ioredis");
const redis = new Redis({
  port: 6379,
  // maxRetriesPerRequest: 1,
  connectTimeout: 10000,
  sentinels: [
    {
      port: 26379,
      host: "localhost",
    },
    {
      port: 26380,
      host: "localhost",
    },
    {
      port: 26381,
      host: "localhost",
    },
  ],
  name: "mymaster",
});

redis.on("error", function (err) {
  console.log("test:");
  if (err) {
    console.log("errortesttt:", err);
  }
});

redis.on("connect", () => {
  console.log("CacheStore - Connection status: connected");
});

redis.set("mykey", "value");
redis.get("mykey", (err, result) => {
  if (err) {
    console.error(err);
  } else {
    console.log(result); // Prints "value"
  }
});`

**I am facing this issue**
`test:
errortesttt: Error: connect ETIMEDOUT
    at Socket.<anonymous> (/Users/saurabh.aggarwal/Desktop/test/node_modules/ioredis/built/Redis.js:168:41)
    at Object.onceWrapper (node:events:509:28)
    at Socket.emit (node:events:390:28)
    at Socket._onTimeout (node:net:501:8)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/Users/saurabh.aggarwal/Desktop/test/node_modules/ioredis/built/redis/event_handler.js:175:37)
    at Object.onceWrapper (node:events:510:26)
    at Socket.emit (node:events:390:28)
    at TCP.<anonymous> (node:net:687:12)`

- Have anybody gone through this type of issue?
- can anybody please suggest or give an alternative to clear this issue.
- I have to connect it with sentinel only.

**Comment by MichaelPlan** [comment]
Same Problem. Can somebody help?

**Comment by untrueme** [comment]
same problem

**Comment by TxusBlack** [comment]
Same here. Version ^5.3.2

**Comment by gwiater** [comment]
Got the same issue on macos on ubuntu the same code works ok.
I'm able to connect without sentinels, direct to master

**Comment by PavelPashov** [comment]
Thanks for reporting this. Sentinel is returning the Docker-internal address `172.17.0.4:6379`, so make sure that Redis node is available at `127.0.0.1:6379` and use the following configuration:

```js
const Redis = require("ioredis");

const redis = new Redis({
  port: 6379,
  connectTimeout: 10000,
  sentinels: [
    { host: "localhost", port: 26379 },
    { host: "localhost", port: 26380 },
    { host: "localhost", port: 26381 },
  ],
  name: "mymaster",
  natMap: {
    "172.17.0.4:6379": { host: "127.0.0.1", port: 6379 },
  },
});
```

Each replica must also have a unique published port and corresponding `natMap` entry for failover. Since this is a Docker networking configuration issue rather than an ioredis defect, I’ll close this issue, but we can reopen it if the problem persists with reachable mapped addresses.
