### ISSUE TITLE
Keep getting MOVED errors after enabling autopipelining

### ISSUE THREAD

**Issue by gustavotoyota** [luin/ioredis#1692]
For some reason I keep getting MOVED errors after enabling auto-pipelining.
Anyone knows a possible reason for this?

![Screenshot from 2022-12-15 00-05-31](https://user-images.githubusercontent.com/11639451/207770619-6c53700f-a973-4463-98c7-be50cf479c79.png)

I thought the library was supposed to handle these errors automatically.
I'm using some Lua scripts in Redis, maybe it has something to do with that?

**Comment by gustavotoyota** [comment]
I found that my redis cluster is behaving very strangely.
One of the slaves isn't synchronizing with its master at all.
I'll try to fix it and close this issue.

**Comment by gustavotoyota** [comment]
Strangely, I keep receiving MOVED errors even after fixing the slave:
```
2022-12-15T16:23:43.951551038Z 0|index  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
2022-12-15T16:23:43.951619937Z 0|index  | WO: MOVED 15327 5.161.75.167:48418
2022-12-15T16:23:43.951631339Z 0|index  |     at R0e (/app/index.js:195:11553)
2022-12-15T16:23:43.951635837Z 0|index  |     at pG (/app/index.js:195:12448)
```

**Comment by gustavotoyota** [comment]
Okay I found something.
Auto pipelining in ioredis separates pipelines per node.
I solved by making ioredis separate pipelines per slot.
I don't know why it didn't happen to anyone else, given Redis itself states that pipelines should always target a single slot.

I will close the issue and open a PR.
