### ISSUE TITLE
cant test redis database on integrations test using jest and supertest

### ISSUE THREAD

**Issue by danilomourelle** [luin/ioredis#1697]
I have an express app that uses redis througth ioredis lib and it works fine on all environment but the test environment.

I put it in the simplest form possible. Using JS, just a app.js file, with a second file where a connect to redis and export the client that is used in app.
app.js
```javascript
const express = require('express');
const ioredis = require('./database/ioredis');
// const redis = require('./database/redis');;

const app = express();

app.use("/", async (req, res) => {
  await ioredis.set("ioredis", "test")
  
  // await redis.connect();
  // await redis.set('redis', 'value');
  // const value = await redis.get('redis');
  // await redis.disconnect();
  res.status(200).send({ message: "Hello" })
})

module.exports = app
```

database/ioredis.js
```javascript
const Redis = require('ioredis');

const ioredis = new Redis({
  host: "localhost",
  port: 6379,
  db: 2
})

module.exports = ioredis
```

test.js
```javascript
const supertest = require('supertest');
const app = require('../app');

describe("Testing Redis on supertest", () => {
  it("should run supertest", async () => {
    const { status, body } = await supertest(app).post("/")

    expect(status).toBe(200)
    expect(body).toEqual({ message: "Hello" })
  })
})
```

When run the test jest gives the following message
```shell
Jest has detected the following 1 open handles potentially keeping Jest from exiting:
●  TCPWRAP

      1 | import Redis from 'ioredis'
      2 |
    > 3 | const ioredis = new Redis({
        |                 ^
      4 |   host: "localhost",
      5 |   port: 6379,
      6 |   db: 2

      at ../../node_modules/ioredis/built/connectors/StandaloneConnector.js:44:21
      at Object.<anonymous> (../database/ioredis.ts:3:17)
      at Object.<anonymous> (../app.ts:2:1)
      at Object.<anonymous> (supertest.ts:2:1)
```

It's possible to see I'm doing tests with redis lib... and since they connect and disconnect in each operations, it worked fine, but if I comment the `diconnect` line I got same problem as well.

**Comment by danilomourelle** [comment]
I'm sorry. I forgot to update here. Last week I found out that if we import the client instance on tests files, and in the `afterAll()` we call `redis.quit()` it closes connections that supertest had open, and jest can finish their process with no problem.... Thank you for your time.
