### ISSUE TITLE
How to use sort command with ioredis?

### ISSUE THREAD

**Issue by BraveEvidence** [luin/ioredis#1731]
```
await ioredis.sort(
    itemsByViewsKey(),
    "BY",
    "nosort",
    "LIMIT",
    0,
    10,
    "GET",
    `${itemsKey("*")}->name`,
    `${itemsKey("*")}->views`,
    order
  );
```

I want to sort the above logic by no sort and then add limit with the provided offset and count and Get the name and views but i get error saying 

```
error - ReplyError: ERR unknown command `sort_ro`, with args beginning with: `items:views`, `BY`, `nosort`, `LIMIT`, `0`, `10`, `GET`, `items#*->name`, `items#*->views`, `DESC`, 
    at parseError (/Users/transformhub/Desktop/VID/Redis/rbay/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/transformhub/Desktop/VID/Redis/rbay/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'sort_ro',
    args: [
      'items:views',
      'BY',
      'nosort',
      'LIMIT',
      '0',
      '10',
      'GET',
      'items#*->name',
      'items#*->views',
      'DESC'
    ]
  },
  page: '/api/itemsByViews'
}
```

I also tried `sort_ro` but i get error saying 

```
error - ReplyError: ERR unknown command `sort_ro`, with args beginning with: `items:views`, `BY`, `nosort`, `LIMIT`, `0`, `10`, `GET`, `items#*->name`, `items#*->views`, `DESC`, 
    at parseError (/Users/transformhub/Desktop/VID/Redis/rbay/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/transformhub/Desktop/VID/Redis/rbay/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'sort_ro',
    args: [
      'items:views',
      'BY',
      'nosort',
      'LIMIT',
      '0',
      '10',
      'GET',
      'items#*->name',
      'items#*->views',
      'DESC'
    ]
  },
  page: '/api/itemsByViews'
}
```

**Comment by luin** [comment]
`sort()` won't trigger `sort_ro` error so can you double check?

**Comment by PavelPashov** [comment]
`redis.sort(...)` should send the `SORT` command, not `SORT_RO`. In current ioredis these are separate methods: use `sort(...)` for `SORT`, and only use `sort_ro(...)` when your Redis server supports the read-only variant.

The stack trace shows the command name is already `sort_ro`. `SORT_RO` was added in Redis 7.0, so servers older than that will return `ERR unknown command`.
