### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by manast** [luin/ioredis#1742]
Lately, I have seen a lot of errors like this in my logs. I do not yet have enough information on the particular Redis instance that is producing this, but I will investigate it further. I wanted to open an issue though in case anybody knows what could produce an error like this. Note that the error does not come from ioredis itself but from the module "redis-parser" (https://www.npmjs.com/package/redis-parser) I am a bit worried that this module which has not been maintained in 6 years and may have issues with newer versions of Redis 🤔

```bash
"Protocol error, got \"S\" as reply type byte. Please report this.",
        "stack": "ParserError: Protocol error, got \"S\" as reply type byte. Please report this.\n    at handleError (/var/www/server/node_modules/redis-parser/lib/parser.js:190:15)\n    at parseType (/var/www/server/node_modules/redis-parser/lib/parser.js:304:14)",
```

**Comment by manast** [comment]
There are similar issues reported already but no action has been taken: https://github.com/NodeRedis/node-redis-parser/issues/64
