### ISSUE TITLE
Node server uses cluster db not "0" get Error

### ISSUE THREAD

**Issue by andyliuzs** [luin/ioredis#1751]
My Node server uses cluster, and creates a client in each process. When the option "db" is set to the default value of '0', no error is thrown. However, if the database value is not "0", an error is thrown with the following message：

**Error:**
 ```
  events.js:291
        throw er; // Unhandled 'error' event
        ^
  
  Error: Command queue state error. If you can reproduce this, please report it. Last reply: 1682232897.609074 [3 127.0.0.1:36322] "info"
      at DataHandler.shiftCommand (/*xxxpath*/node_modules/ioredis/built/DataHandler.js:173:27)
      at DataHandler.returnReply (/**/node_modules/ioredis/built/DataHandler.js:50:27)
      at JavascriptRedisParser.returnReply (/**/node_modules/ioredis/built/DataHandler.js:21:22)
      at JavascriptRedisParser.execute (/**/node_modules/redis-parser/lib/parser.js:544:14)
      at Socket.<anonymous> (/**/node_modules/ioredis/built/DataHandler.js:25:20)
      at Socket.emit (events.js:314:20)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:272:9)
      at Socket.Readable.push (_stream_readable.js:213:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
  Emitted 'error' event at:
      at DataHandler.shiftCommand (/**/node_modules/ioredis/built/DataHandler.js:177:24)
      at DataHandler.returnReply (/**/node_modules/ioredis/built/DataHandler.js:50:27)
      [... lines matching original stack trace ...]
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Additional information**: I found that setting enableOfflineQueue to false in the Redis options prevents the error from occurring, but based on the description of the enableOfflineQueue configuration, this is not the desired outcome for me.

**Node version** 12.22.0
**ioredis version** 5.3.1

-------

My Redis options:
{
  host:'127.0.0.1',
  port: 6379,
  password: "****", 
  db: 3,
  maxRetriesPerRequest: null,
  enableReadyCheck: false,
}

**Comment by leibale** [comment]
This is a limitation of redis-cluster, not ioredis.

"Redis Cluster does not support multiple databases like the standalone version of Redis. We only support database 0; the [SELECT](https://redis.io/commands/select) command is not allowed."

https://redis.io/docs/reference/cluster-spec/#implemented-subset
