### ISSUE TITLE
Parser Error after sending a 'hello(3)' command to my local redis server(running on WSL2 ubuntu with Windows11)

### ISSUE THREAD

**Issue by aiyuzui** [luin/ioredis#1761]
> [ioredis] Unhandled error event: ParserError: Protocol error, got "%" as reply type byte. Please report this.
>     at handleError (D:\DollMasterServer\node_modules\.pnpm\redis-parser@3.0.0\node_modules\redis-parser\lib\parser.js:190:15)
>     at parseType (D:\DollMasterServer\node_modules\.pnpm\redis-parser@3.0.0\node_modules\redis-parser\lib\parser.js:304:14)
> error hello 3
> D:\DollMasterServer\node_modules\.pnpm\redis-parser@3.0.0\node_modules\redis-parser\lib\parser.js:190
>   const err = new ParserError(
>               ^
> ParserError: Protocol error, got "%" as reply type byte. Please report this.     
>     at handleError (D:\DollMasterServer\node_modules\.pnpm\redis-parser@3.0.0\node_modules\redis-parser\lib\parser.js:190:15)
>     at parseType (D:\DollMasterServer\node_modules\.pnpm\redis-parser@3.0.0\node_modules\redis-parser\lib\parser.js:304:14) {
>   offset: 1,
>   buffer: '{"type":"Buffer","data":[37,55,13,10,36,54,13,10,115,101,114,118,101,114,13,10,36,53,13,10,114,101,100,105,115,13,10,36,55,13,10,118,101,114,115,105,111,110,13,10,36,54,13,10,55,46,48,46,49,49,13,10,36,53,13,10,112,114,111,116,111,13,10,58,51,13,10,36,50,13,10,105,100,13,10,58,49,49,48,53,13,10,36,52,13,10,109,111,100,101,13,10,36,49,48,13,10,115,116,97,110,100,97,108,111,110,101,13,10,36,52,13,10,114,111,108,101,13,10,36,54,13,10,109,97,115,116,101,114,13,10,36,55,13,10,109,111,100,117,108,101,115,13,10,42,48,13,10,62,51,13,10,36,57,13,10,115,117,98,115,99,114,105,98,101,13,10,36,49,48,13,10,68,79,76,76,77,65,83,84,69,82,13,10,58,49,13,10]}'
> }
> [ioredis] Unhandled error event: ParserError: Protocol error, got "%" as reply type byte. Please report this.
>     at handleError (D:\DollMasterServer\node_modules\.pnpm\redis-parser@3.0.0\node_modules\redis-parser\lib\parser.js:190:15)
>     at parseType (D:\DollMasterServer\node_modules\.pnpm\redis-parser@3.0.0\node_modules\redis-parser\lib\parser.js:304:14)

**Comment by luin** [comment]
Hey @aiyuzui 👋

Can you create a reproducible demo for the issue?

**Comment by PavelPashov** [comment]
`HELLO 3` switches the connection to RESP3. ioredis with `redis-parser@3.0.0` expects RESP2.

If you need RESP3 features, use a RESP3-capable client like `node-redis` with `RESP: 3`.
