### ISSUE TITLE
windows 运行 redis.set('key', 100, 'EX', 10); 报错。

### ISSUE THREAD

**Issue by pangguoming** [luin/ioredis#180]
Redis 版本：windows 直装版 2.4.5

Unhandled rejection ReplyError: ERR wrong number of arguments for 'set' command
    at ReplyParser._parseResult (e:\NodeJSWorkSpace\RealTimeBus-RESTful\node_modules\ioredis\lib\parsers\javascript.js:56:14)
    at ReplyParser.execute (e:\NodeJSWorkSpace\RealTimeBus-RESTful\node_modules\ioredis\lib\parsers\javascript.js:174:20)
    at Socket.<anonymous> (e:\NodeJSWorkSpace\RealTimeBus-RESTful\node_modules\ioredis\lib\redis\event_handler.js:90:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by pangguoming** [comment]
ok，got it.
