### ISSUE TITLE
Problems running in Node.js 4.2.x

### ISSUE THREAD

**Issue by ajkerr** [luin/ioredis#195]
I am getting an exception when running a setex command under node.js 4.2.x. Reverting to Node 0.12 fixes the issue.

Here is the exception:
```
     Uncaught TypeError: must start with number, buffer, array or string
      at fromObject (buffer.js:167:9)
      at FlexBuffer.Buffer (buffer.js:58:10)
      at new FlexBuffer (node_modules/ioredis/node_modules/flexbuffer/flexbuffer.js:9:30)
      at Command.toWritable (node_modules/ioredis/lib/command.js:167:24)
      at Redis.sendCommand (node_modules/ioredis/lib/redis.js:502:43)
      at Redis.Commander.(anonymous function) [as setex] (node_modules/ioredis/lib/commander.js:40:17)
```
I think that the problem lies with the way the FlexBuffer class is creating the underlying Buffer. It appears that there is some stricter typechecking going on in newer versions of Node that causes an exception to be thrown.

I'm opening the bug here because the flexbuffer project doesn't appear to be active.

**Comment by luin** [comment]
What ioredis version are you using? I remember it has already been fixed.

**Comment by ajkerr** [comment]
Oh! You are right, I thought I was using 1.10.0, but I had a typo in my package.json file and was using 1.1.0. Sorry about that.
