### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#196]
Hi,
Using ioredis 1.7.6, we observed the following issue.
It probably happens if for some reason the response received from redis is incorrect (maybe timed out).
You should add a check that the response exists and is correct?

```
TypeError: undefined is not a function
    at /var/www/XXX/node_modules/YYY/node_modules/ioredis/lib/cluster.js:471:34
    at run (/var/www/XXX/node_modules/YYY/node_modules/ioredis/lib/utils/index.js:151:16)
    at tryCatcher (/var/www/XXX/node_modules/YYY/node_modules/ioredis/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/var/www/XXX/node_modules/YYY/node_modules/ioredis/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/var/www/XXX/node_modules/YYY/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:575:21)
    at Promise._settlePromises (/var/www/XXX/node_modules/YYY/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/var/www/XXX/node_modules/YYY/node_modules/ioredis/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/var/www/XXX/node_modules/YYY/node_modules/ioredis/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/XXX/node_modules/YYY/node_modules/ioredis/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by luin** [comment]
Could you please post the result of command `cluster slots`?

**Comment by shaharmor** [comment]
there you go:
```
127.0.0.1:6379> cluster slots
1) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "127.0.0.1"
      2) (integer) 6379
   4) 1) "10.240.56.139"
      2) (integer) 6380
2) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.240.29.254"
      2) (integer) 6379
   4) 1) "10.240.78.46"
      2) (integer) 6380
3) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "10.240.56.139"
      2) (integer) 6379
   4) 1) "10.240.29.254"
      2) (integer) 6380
```

I think the issue happened when the cluster was not in its OK state, maybe during promotion or some other state

**Comment by AVVS** [comment]
This looks like the issue I had during the tests, and it was already fixed in the modern versions of ioredis

**Comment by shaharmor** [comment]
But the issue is at this line:
https://github.com/luin/ioredis/blob/1.7.6/lib/cluster.js#L471
meaning there was no error, and the result just became not as it should.

I don't see any check of the response in the master branch

**Comment by luin** [comment]
That's strange. It seems that redis guarantees [`cluster slots`](http://redis.io/commands/cluster-slots) returns a nested array so that [`items`](https://github.com/luin/ioredis/blob/master/lib/cluster.js#L500) should be an array. Could you print the result of `cluster slots` that ioredis gets when this error happens?

**Comment by shaharmor** [comment]
It doesn't happen anymore, it only happened last night during a cluster failover.

**Comment by luin** [comment]
Just checked the source code of cluster slots command: https://github.com/antirez/redis/blob/unstable/src/cluster.c#L3737. Haven't find out why `items` is not an array. Anyway, let me know if the error happens again.

@AVVS Are you able to reproduce the error (using the 1.7.6 version)?

**Comment by AVVS** [comment]
Thought was related to #56, but doesn't seem to be. Either way that was when cluster wasn't yet initialized and not all slots were allocated yet. In the recent versions I haven't seen it once and can't really try 1.7.6 at this point - these test sets are long gone :-1:

**Comment by shaharmor** [comment]
I'm not sure its related to redis.
I think that there was something in the connection, maybe load on the server, on redis, timeout, network issue, or something like that.

**Comment by shaharmor** [comment]
I believe this can be closed as i have yet to witness it again using the latest version
