### ISSUE TITLE
Crash during a startup

### ISSUE THREAD

**Issue by AVVS** [luin/ioredis#231]
Latest ioredis version. Doesn't replicate often, but this time it seems that node.js has started before the cluster bootstrapped during the tests and what we had is this. I have 3 nodes with 0 replicas

```
redis_1      | 1:M 19 Jan 18:07:51.382 # Cluster state changed: ok
ms-users     | 
ms-users     | > ms-users@1.3.6 start /src
ms-users     | > node ./bin/mservice.js | ./node_modules/.bin/bunyan -o short
ms-users     | 
ms-mailer    | 18:07:51.827Z  INFO mservice: created transport cappasity@makeomatic.co (namespace=accounts)
ms-mailer    | 18:07:51.900Z  INFO mservice: connected to amqp and transports
ms-mailer    | 18:07:51.900Z  INFO mservice: service started
ms-payments  | /src/node_modules/ioredis/lib/parsers/javascript.js:181
ms-payments  |         throw err;
ms-payments  |         ^
ms-payments  | 
ms-payments  | TypeError: Cannot set property 'masterNode' of undefined
ms-payments  |     at Object._this.handleError.moved (/src/node_modules/ioredis/lib/cluster.js:417:40)
ms-payments  |     at Cluster.handleError (/src/node_modules/ioredis/lib/cluster.js:501:16)
ms-payments  |     at Command.command.reject (/src/node_modules/ioredis/lib/cluster.js:414:13)
ms-payments  |     at Redis.exports.returnError (/src/node_modules/ioredis/lib/redis/parser.js:63:20)
ms-payments  |     at ReplyParser.replyParser.sendError (/src/node_modules/ioredis/lib/redis/parser.js:22:10)
ms-payments  |     at ReplyParser.execute (/src/node_modules/ioredis/lib/parsers/javascript.js:145:14)
ms-payments  |     at Socket.<anonymous> (/src/node_modules/ioredis/lib/redis/event_handler.js:90:22)
ms-payments  |     at emitOne (events.js:77:13)
ms-payments  |     at Socket.emit (events.js:169:7)
ms-payments  |     at readableAddChunk (_stream_readable.js:146:16)
ms-payments  |     at Socket.Readable.push (_stream_readable.js:110:10)
ms-payments  |     at TCP.onread (net.js:523:20)
redis_2      | 1:M 19 Jan 18:07:52.264 # Cluster state changed: ok
redis_client | Waiting for the cluster to join..
redis_client | >>> Performing Cluster Check (using node 172.17.0.6:6379)
redis_client | M: 4e884efb59566bfc470328874679308668bde354 172.17.0.6:6379
redis_client |    slots:0-5460 (5461 slots) master
redis_client | M: d50defd3f9bba36057cd482095fb11d654193283 172.17.0.5:6379
redis_client |    slots:5461-10922 (5462 slots) master
redis_client | M: 1b0eeb358ff21b73a984cd762799168637e8920b 172.17.0.4:6379
redis_client |    slots:10923-16383 (5461 slots) master
redis_client | [OK] All nodes agree about slots configuration.
redis_client | >>> Check for open slots...
redis_client | >>> Check slots coverage...
redis_client | [OK] All 16384 slots covered.
redis_client | OK
redis_client | 1453226872.451937 [0 172.17.0.12:34480] "info"
```

**Comment by AVVS** [comment]
More info - this actually happened when I had a bootstrapped cluster. But then I started resharding it. At this point ioredis tried to get some info, I assume it got error that a SLOT was moved and then crashed.
