### ISSUE TITLE
ECONNABORTED terminates process

### ISSUE THREAD

**Issue by sakthivel49** [luin/ioredis#243]
{ [Error: write ECONNABORTED] code: 'ECONNABORTED', errno: 'ECONNABORTED', syscall: 'write' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write ECONNABORTED
    at errnoException (net.js:901:11)
    at Socket._write (net.js:643:26)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)
    at Socket.Writable.write (_stream_writable.js:180:11)
    at Socket.write (net.js:613:40)
    at Redis.sendCommand (C:\_Practice\redis\node_modules\ioredis\lib\redis.js:522:29)
    at Redis.info (C:\_Practice\redis\node_modules\ioredis\lib\commander.js:117:17)
    at Redis._readyCheck (C:\_Practice\redis\node_modules\ioredis\lib\redis.js:373:8)
    at Socket.<anonymous> (C:\_Practice\redis\node_modules\ioredis\lib\redis\event_handler.js:29:12)
    at Socket.g (events.js:180:16)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Object.afterConnect [as oncomplete] (net.js:883:10)

My Code:

var Redis = require('ioredis');
var redis = new Redis({
    port: 6379 // Redis port 
    host: '127.0.0.1', // Redis host 
    family: 4, // 4 (IPv4) or 6 (IPv6) 
    password: 'auth',
    db: 0,
    lazyConnect: true
})

redis.on("error", function(err) {
    console.log("redis con err", err);
})

redis.connect().then(function() {
    console.log('connected!');
}, function(error) {
    console.log(error);
    
});

Hi, I have installed redis server on cent OS which is running in vagrant box. I have forwarded the default port 6379 and I try to connect from windows OS, it works fine if redis server is running. When I stop redis server and try to connect it throws the above exception and terminates the process instead of catch by redis error event. 

One Catch:
When I give wrong port like 1234 and try to connect, error event triggered as expected and process not terminated. So problem here is I have forwarded port 6379 between centos and windows and I try to connect, a request forwarded to cent os and that rejects the request as redis server is stopped. I think this scenario is not handled. Help me out.

**Comment by luin** [comment]
What's node.js  version are you using?

**Comment by sakthivel49** [comment]
$ node --version
v0.10.25

**Comment by sakthivel49** [comment]
I tested with latest version of node.js (v4.2.6) it works fine, error catch on event and process not terminated. Thanks. Any hope for v0.10.25?

**Comment by luin** [comment]
It seems to be a bug of libuv with windows, so I don't think we can do anything about that.

**Comment by sakthivel49** [comment]
Yes when I run the same code on cent os it works fine. Thank you for ​your swift ​reply.
