### ISSUE TITLE
Sentinel: If you subscribe after connection established, you error.

### ISSUE THREAD

**Issue by evantahler** [luin/ioredis#255]
Consider the folowing:

```js
var Redis = require('ioredis');

var config = {
  options: {
    name: 'mymsater',
    db: 10,
    sentinels: [
      { host: '127.0.0.1', port: 26379 },
    ]
  }
};

var pub = Redis.createClient(null, null, config.options);
var sub = Redis.createClient(null, null, config.options);

pub.on('error', function(err){ console.log(err); });
sub.on('error', function(err){ console.log(err); });

pub.on('connect', function(){
  console.log('PUB connected');
});

sub.on('connect', function(){
  console.log('SUB connected');

  sub.subscribe('channel', function(error){
    if(error){ console.log(error); }

    sub.on('message', function(channel, message){
      console.log('[%s]: %s', channel, message);
    })

    pub.publish('channel', 'hello');
  })
});

```

If you wait until after the connection even to subscribe the following uncaught promise rejection is fired:

```
Unhandled rejection Error: Connection in subscriber mode, only subscriber commands may be used
    at Redis.sendCommand (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/lib/redis.js:500:20)
    at Redis.selectBuffer (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/lib/commander.js:117:17)
    at /Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/lib/redis/event_handler.js:184:12
    at /Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/lib/redis/event_handler.js:35:39
    at /Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/lib/redis.js:392:7
    at tryCatcher (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

This only seems to happen when sentinels are in use

**Comment by evantahler** [comment]
Oh, I should point out that while the rejection occurs, the message is still received:

```
> node test.js
PUB connected
SUB connected
Unhandled rejection Error: Connection in subscriber mode, only subscriber commands may be used
    at Redis.sendCommand (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/lib/redis.js:500:20)
    at Redis.selectBuffer (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/lib/commander.js:117:17)
    at /Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/lib/redis/event_handler.js:184:12
    at /Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/lib/redis/event_handler.js:35:39
    at /Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/lib/redis.js:392:7
    at tryCatcher (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/evantahler/Dropbox/Projects/actionhero/node_modules/ioredis/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
[channel]: hello
```

**Comment by luin** [comment]
Thank you for the feedback! This issue is related with `db` option instead of sentinel. The following code can reproduce the error:

```javascript
var redis = new Redis({ db: 10 });
redis.on('connect', function () {
  redis.subscribe('anychannel');
});
```

The error is because ioredis sends the `SELECT` command to switch to db 10 on the `ready` event. In most cases that would not cause any problem because commands sent after the `connect` event and before the `ready` event will be added to the offline queue and will be resent after the `ready` event.

However, pub/sub commands (`SUBSCRIBE`, `PSUBSCRIBE` and `UNSUBSCRIBE` etc) are special that ioredis allows them to be sent to Redis before the `ready` event. So when we sends `SELECT` command on the `ready` event, the connection has been in the subscribe mode and Redis will reject the `SELECT` command.

**Comment by luin** [comment]
Release in 1.15.1 :rocket:

**Comment by evantahler** [comment]
Thanks for the quick patch!

**Comment by luin** [comment]
@seunlanlege This issue has been resolved, so there may be another issue. Could you enable debug mode (`DEBUG=ioredis:* node yourapp.js`) and post the logs here?

**Comment by seunlanlege** [comment]
![screenshot from 2018-10-22 18-02-46](https://user-images.githubusercontent.com/16494314/47306570-b645e200-d624-11e8-90d8-47261d3b9db5.png)

**Comment by luin** [comment]
@seunlanlege What's the constructor argument of `Redis`? And what's the version of Redis server? Please enable the `showFriendlyErrorStack` option to see which command cause the exception (`new Redis({showFriendlyErrorStack: true})`).

**Comment by AVVS** [comment]
I think its a problem with the code. Redis.config is issued without await, command cant complete before .subscribe, connection is then moved to subscriber mode and cant finish it

ie I'm pretty sure if you do 

await Redis.config()

and only then subscribe - you should be good
