### ISSUE TITLE
ENETUNREACH unhandled error

### ISSUE THREAD

**Issue by cmcewen** [luin/ioredis#294]
My setup: Kubernetes cluster with redis-sentinel. I have a node application that connects to redis via redis-sentinel:

```
Redis({
  sentinels: [{ host: process.env.REDIS_SENTINEL, port: 26379 }],
  name: 'mymaster',
  retryStrategy: function(times) {
    return Math.min(times * 2, 2000);;
  }
});
```

I'm getting this error consistently on some of my containers:
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ENETUNREACH 192.168.180.0:6379 - Local (0.0.0.0:0)
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at connect (net.js:847:16)
    at net.js:933:9
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

Adding `DEBUG = ioredis:*` fixes the issue, but I'm able to reproduce consistently without it. Tried on both `2.0.0-rc3` and `1.15.1`

**Comment by cmcewen** [comment]
Ah actually was able to get some logs with DEBUG on
```
Fri, 06 May 2016 16:05:07 GMT ioredis:redis status[localhost:6379]: [empty] -> connecting
Fri, 06 May 2016 16:05:07 GMT ioredis:redis status[redis-sentinel:26379]: [empty] -> connecting
Fri, 06 May 2016 16:05:07 GMT ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,mymaster)
Fri, 06 May 2016 16:05:07 GMT ioredis:redis status[localhost:6379]: [empty] -> connecting
Fri, 06 May 2016 16:05:07 GMT ioredis:redis status[redis-sentinel:26379]: [empty] -> connecting
Fri, 06 May 2016 16:05:07 GMT ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,mymaster)
Fri, 06 May 2016 16:05:07 GMT ioredis:redis queue command[0] -> subscribe({q}:events)
Listening at port 80
Fri, 06 May 2016 16:05:07 GMT ioredis:redis status[192.168.185.195:26379]: connecting -> connect
Fri, 06 May 2016 16:05:07 GMT ioredis:redis status[192.168.185.195:26379]: connect -> ready
Fri, 06 May 2016 16:05:07 GMT ioredis:connection send 1 commands in offline queue
Fri, 06 May 2016 16:05:07 GMT ioredis:redis write command[0] -> sentinel(get-master-addr-by-name,mymaster)
Fri, 06 May 2016 16:05:07 GMT ioredis:redis status[192.168.185.195:26379]: connecting -> connect
Fri, 06 May 2016 16:05:07 GMT ioredis:redis status[192.168.185.195:26379]: connect -> ready
Fri, 06 May 2016 16:05:07 GMT ioredis:connection send 1 commands in offline queue
Fri, 06 May 2016 16:05:07 GMT ioredis:redis write command[0] -> sentinel(get-master-addr-by-name,mymaster)
Fri, 06 May 2016 16:05:07 GMT ioredis:connection error: Error: connect ENETUNREACH 192.168.180.0:6379 - Local (0.0.0.0:0)
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ENETUNREACH 192.168.180.0:6379 - Local (0.0.0.0:0)
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at connect (net.js:847:16)
    at net.js:933:9
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

**Comment by luin** [comment]
`ENETUNREACH` means the network was unreachable. In your case, the client is able to connect to 192.168.185.195: 26379 but not to 192.168.180.0:6379. It should have nothing to do with whether the debug mode is enabled.

**Comment by cmcewen** [comment]
Yeah that makes sense - might be some momentary network problems when the container first starts, but I just thought all the connection errors were silent and the connection would be retried if no error listener was attached. This error crashes the app

**Comment by luin** [comment]
Yes, ioredis won't emit error if there's no listener attached (https://github.com/luin/ioredis/blob/master/lib/redis/event_handler.js#L104). It's strange the error crashes your app. Could you post the code that can reproduce the problem?

**Comment by luin** [comment]
Closing this issue. Feel free to reopen it with more details if the issue still valid.

**Comment by atcheri** [comment]
hi @cmcewen , have you ever been able to slve your problem ?
My app is also crashing when the redis docker container is either not running.

**Comment by gonejack** [comment]
Crashes!!

While manually toggle the MacBook's WIFI off during the `sleeping`.

```typescript
import * as Redis from "ioredis"

async function main() {
    const client = new Redis.Cluster([
        {host: "192.168.10.60", port: 6397},
        {host: "192.168.10.60", port: 6398},
        {host: "192.168.10.60", port: 6399},
    ], {
        enableReadyCheck:   true,
        enableOfflineQueue: false,
        redisOptions:       {
            password: "xxxxxxx",
        },
    });

    try {
        client.on('error', console.error)
        await new Promise(res => client.on('ready', res))
    } catch (e) {
        console.error(e)
        return
    }

    console.log("sleeping")
    await new Promise(res => setTimeout(res, 20e3))
    console.log("sleeping end")

    let i = 1
    while (i++ < 10) {
        try {
            const set = await client.set("abc", "qq122321")
            const get = await client.get("abc")
            console.log(set, get)
        } catch (e) {
            console.log(e)
        }
        await new Promise(res => setTimeout(res, 5e3))
    }
}

main()
```

```
sleeping
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: connect ENETUNREACH 192.168.10.60:6399 - Local (0.0.0.0:55166)
    at internalConnect (net.js:923:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:364:12)
    at net.js:1011:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.10.60',
  port: 6399
}

```
