### ISSUE TITLE
Corrupted entry in cache

### ISSUE THREAD

**Issue by bgrieder** [luin/ioredis#303]
We are using ioredis 1.15.1 and doing a simple `hmset` for a key and 4 numbers.
From time to time on `hmget`, we get the error below.
Looking at the REDIS db, we see that the entry for this key is corrupted and is nil

The frequency of this error significantly increases as the connexion latency between the client and Redis increases and as the number of queries increase

Any idea ?
    
    Unhandled rejection ReplyError: ERR value is not an integer or out of range
        at ReplyParser._parseResult (/opt/b2proxy/node_modules/ioredis/lib/parsers/javascript.js:39:14)
        at ReplyParser.execute (/opt/b2proxy/node_modules/ioredis/lib/parsers/javascript.js:139:20)
        at Socket.<anonymous> (/opt/b2proxy/node_modules/ioredis/lib/redis/event_handler.js:94:22)
        at emitOne (events.js:90:13)
        at Socket.emit (events.js:182:7)
        at readableAddChunk (_stream_readable.js:153:18)
        at Socket.Readable.push (_stream_readable.js:111:10)
        at TCP.onread (net.js:529:20)

**Comment by luin** [comment]
`value is not an integer or out of range` shouldn't be caused by `hmset` command. Instead, `incr` or `decr` may cause the error.

You can enable the `showFriendlyErrorStack` option to see where the error is from.

**Comment by bgrieder** [comment]
This was du to an entry expiring between an HMGET and an INCR.
Obviously the more latency, the higher chances this was to occur.
Many Thanks
