### ISSUE TITLE
weird NOAUTH error

### ISSUE THREAD

**Issue by ORESoftware** [luin/ioredis#307]
hey there!

I got this error after running "npm test" on this lib

```
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at JavascriptReplyParser.replyParser.Parser.returnError (/Users/Olegzandr/WebstormProjects/ioredis/lib/redis/parser.js:25:25)
    at JavascriptReplyParser.run (/Users/Olegzandr/WebstormProjects/ioredis/node_modules/redis-parser/lib/javascript.js:135:18)
    at JavascriptReplyParser.execute (/Users/Olegzandr/WebstormProjects/ioredis/node_modules/redis-parser/lib/javascript.js:112:10)
    at Socket.<anonymous> (/Users/Olegzandr/WebstormProjects/ioredis/lib/redis/event_handler.js:106:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

```

do you know why that might happen and how to fix it? It didn't happen the first time I ran the test suite, but happened after, and now keeps happening. Thanks.

**Comment by ORESoftware** [comment]
nevermind fixed it by disabling auth

**Comment by hustcer** [comment]
I got the same issue, Any one know how to fix it?
