### ISSUE TITLE
Catch ECONNREFUSED exceptions

### ISSUE THREAD

**Issue by neslinesli93** [luin/ioredis#321]
Hi, I want to test what happens to my application when redis goes down. So after starting the server I manually stop the redis daemon that's running on my machine, and I expect to have the errors reported on my error callback/promise.
Instead, I get uncaught exceptions all over the place.

I've tried using a custom `retryStrategy`, I've tried to set `Redis.Promise.onPossiblyUnhandledRejection` as well... all with no luck.
Is there something I'm missing here? How am I supposed to test what happens to my server if for any reason redis stops working?
Thanks

**Comment by luin** [comment]
Have you listened to the `error` event to the redis instance? `redis.on('error', handleError)`

**Comment by Tomino2112** [comment]
In my code I have:

```
redis.on("error", function(err){
    console.log(err);
});
```

But still my app crashes (after taking down redis server) with exception:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

Process finished with exit code 1
```

**Comment by luin** [comment]
ioredis won't emit error message unless you listen it explicitly (like your case). Did you use other library listening to the error message and re-emit it?

**Comment by Tomino2112** [comment]
Yes thats what it says in readme, yet still it is actually throwing errors which stop my app. I am not doing anything unusual, as simple as:

```
var redis = new Redis({
    port: config.redis.port,
    host: config.redis.host,
    family: config.redis.family,
    password: config.redis.password,
    db: config.redis.db,
    showFriendlyErrorStack: (process.env.NODE_ENV !== "production"),
});

redis.on("error", (error) => {
    debug("Redis connection error", error);
});
```

**Comment by luin** [comment]
That's strange. What ioredis version are you using?

**Comment by Tomino2112** [comment]
`"version": "2.2.0"`

**Comment by Tomino2112** [comment]
This is the whole code that I use to connect to redis. (Typescript)

```
import * as Redis from "ioredis";
import {main as config} from "../config/main";
import IRedis = IORedis.Redis;
let debug: Debugger = require("debug")("ipp:redis");

// Handle unhandled exceptions
Redis.Promise.onPossiblyUnhandledRejection((error: any) => {
    debug("Redis unhandled error ", error);
});

debug("creating default redis connection");
export const redis: IRedis = new Redis({
    port: config.redis.port,
    host: config.redis.host,
    family: config.redis.family,
    password: config.redis.password,
    db: config.redis.db,
    // keyPrefix: config.redis.keyPrefix, // @todo https://github.com/luin/ioredis/issues/325
    showFriendlyErrorStack: (process.env.NODE_ENV !== "production"),
});

// Handle connection error
redis.on("error", (error) => {
    debug("Redis connection error", error);
});
```

**Comment by luin** [comment]
I used the following code trying to reproduce the issue:

```javascript
'use strict';

var Redis = require('ioredis');
var redis = new Redis({
  port: 2722,
  showFriendlyErrorStack: (process.env.NODE_ENV !== "production"),
});

Redis.Promise.onPossiblyUnhandledRejection((error) => {
  console.log("Redis unhandled error ", error);
});

redis.on("error", (error) => {
  console.log("Redis connection error", error);
});
```

I didn't have any Redis server listen to port 2722, so I got the following outputs:

```
ioredis git:master ❯ node test.js                                                                  ⏎
Redis connection error { [Error: connect ECONNREFUSED 127.0.0.1:2722]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 2722 }
Redis connection error { [Error: connect ECONNREFUSED 127.0.0.1:2722]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 2722 }
Redis connection error { [Error: connect ECONNREFUSED 127.0.0.1:2722]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 2722 }
Redis connection error { [Error: connect ECONNREFUSED 127.0.0.1:2722]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 2722 }
```

My application kept reconnecting and didn't crash.

Since you exported the redis instance, did you re-emit the error in the other place of your code like this:

```
const redis = require('./lib/yourredis');
redis.on('error', function (err) {
  this.emit('error', err);
  // or process.exit(1);
});
```

**Comment by Tomino2112** [comment]
If I kill the server why app is running, I also get list of reconnection tries but eventually app is killed. If I start the app without server running it gives just one error and dies. 

I am not using `emit` anywhere throughout my app

**Comment by Tomino2112** [comment]
Here is full output from console when I kill server during app run

```
ioredis:redis status[127.0.0.1:6379]: ready -> close +3s
ioredis:connection reconnect in 2ms +1ms
ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +1ms
ioredis:redis status[127.0.0.1:6379]: ready -> close +3ms
ioredis:connection reconnect in 2ms +0ms
ioredis:redis status[127.0.0.1:6379]: close -> reconnecting +1ms
ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +1ms
ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting +2ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +5ms
    [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
ioredis:redis status[localhost:6379]: connecting -> close +3ms
ioredis:connection reconnect in 4ms +0ms
ioredis:redis status[localhost:6379]: close -> reconnecting +1ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +1ms
ipp:redis Redis connection error +1ms { Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
    code: 'ECONNREFUSED',
        errno: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 6379 }
ioredis:redis status[localhost:6379]: connecting -> close +22ms
ioredis:connection reconnect in 4ms +1ms
ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +0ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +3ms
    [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
ioredis:redis status[localhost:6379]: connecting -> close +3ms
ioredis:connection reconnect in 6ms +0ms
ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +0ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +3ms
ipp:redis Redis connection error +0ms { Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
    code: 'ECONNREFUSED',
        errno: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 6379 }
ioredis:redis status[localhost:6379]: connecting -> close +2ms
ioredis:connection reconnect in 6ms +0ms
ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +2ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +2ms
    [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
ioredis:redis status[localhost:6379]: connecting -> close +1ms
ioredis:connection reconnect in 8ms +1ms
ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +0ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +3ms
ipp:redis Redis connection error +3ms { Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
    code: 'ECONNREFUSED',
        errno: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 6379 }
ioredis:redis status[localhost:6379]: connecting -> close +3ms
ioredis:connection reconnect in 8ms +1ms
ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +1ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +2ms
    [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
ioredis:redis status[localhost:6379]: connecting -> close +2ms
ioredis:connection reconnect in 10ms +1ms
ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +3ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +3ms
ipp:redis Redis connection error +0ms { Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
    code: 'ECONNREFUSED',
        errno: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 6379 }
ioredis:redis status[localhost:6379]: connecting -> close +3ms
ioredis:connection reconnect in 10ms +0ms
ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +2ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +2ms
    [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
ioredis:redis status[localhost:6379]: connecting -> close +2ms
ioredis:connection reconnect in 12ms +1ms
ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +4ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +5ms
ipp:redis Redis connection error +0ms { Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
    code: 'ECONNREFUSED',
        errno: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 6379 }
ioredis:redis status[localhost:6379]: connecting -> close +3ms
ioredis:connection reconnect in 12ms +0ms
ioredis:redis status[localhost:6379]: close -> reconnecting +1ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +0ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +2ms
    [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
ioredis:redis status[localhost:6379]: connecting -> close +2ms
ioredis:connection reconnect in 14ms +1ms
ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +7ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +3ms
ipp:redis Redis connection error +0ms { Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
    code: 'ECONNREFUSED',
        errno: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 6379 }
ioredis:redis status[localhost:6379]: connecting -> close +2ms
ioredis:connection reconnect in 14ms +0ms
ioredis:redis status[localhost:6379]: close -> reconnecting +1ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +3ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +2ms
    [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
ioredis:redis status[localhost:6379]: connecting -> close +1ms
ioredis:connection reconnect in 16ms +0ms
ioredis:redis status[localhost:6379]: close -> reconnecting +1ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +7ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +2ms
ipp:redis Redis connection error +1ms { Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
    code: 'ECONNREFUSED',
        errno: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 6379 }
ioredis:redis status[localhost:6379]: connecting -> close +1ms
ioredis:connection reconnect in 16ms +0ms
ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +5ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +3ms
    [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
ioredis:redis status[localhost:6379]: connecting -> close +1ms
ioredis:connection reconnect in 18ms +0ms
ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +9ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +2ms
ipp:redis Redis connection error +0ms { Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
    code: 'ECONNREFUSED',
        errno: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 6379 }
ioredis:redis status[localhost:6379]: connecting -> close +2ms
ioredis:connection reconnect in 18ms +1ms
ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +6ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +2ms
    [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
ioredis:redis status[localhost:6379]: connecting -> close +1ms
ioredis:connection reconnect in 20ms +0ms
ioredis:redis status[localhost:6379]: close -> reconnecting +1ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +8ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +3ms
ipp:redis Redis connection error +0ms { Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
    code: 'ECONNREFUSED',
        errno: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 6379 }
ioredis:redis status[localhost:6379]: connecting -> close +1ms
ioredis:connection reconnect in 20ms +0ms
ioredis:redis status[localhost:6379]: close -> reconnecting +1ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +7ms
ioredis:redis status[localhost:6379]: reconnecting -> connecting +15ms
ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379 +0ms
    [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
events.js:160
throw er; // Unhandled 'error' event
^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:1007:11)
at exports._exceptionWithHostPort (util.js:1030:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
```

**Comment by luin** [comment]
Could you run the following code and see the output:

```javascript
'use strict';

var Redis = require('./index');
var redis = new Redis({
  port: 2722
});

Redis.Promise.onPossiblyUnhandledRejection((error) => {
  console.log("Redis unhandled error ", error);
});

redis.on("error", (error) => {
  console.log("Redis connection error", error);
  process.exit(1);
});

process.on('exit', function (){
  console.log('Exiting...listener count', redis.listenerCount('error'));
});
```

**Comment by Tomino2112** [comment]
`Exiting...listener count 1`

**Comment by hellish** [comment]
hello,

i'm getting the error as well. I have both
`Redis.Promise.onPossiblyUnhandledRejection((error) ...`
and
```
redis.on('error', function() {
    debug('redis error caught');
});
```

The error occurs when redis (sentinel slave) machine dies or reboots. I stay connected to the master but my app crashes with the following error
```
redis error caught
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 45.32.154.136:6380
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

has anyone solved this?

**Comment by luin** [comment]
@hellish Is 127.0.0.1:6666 your slave? Could you give me a minimal reproducible example so I can debug locally?

**Comment by hellish** [comment]
@luin i am running master at 127.0.0.1:5555 and slave 127.0.0.1:6666 and sentinel at 127.0.0.1:7000.
the setup works fine with the sentinel and i can connect to the sentinel with the code available in the documentation.
```
var redis = new Redis({
  sentinels: [{ host: '127.0.0.1', port: 7000 }],
  name: 'mymaster'
});
```
once i kill the slave node app dies.
Its the simplest sentinel setup with 3 instances.
I do not know how can I give you a  reproducible example.

**Comment by luin** [comment]
@hellish Hi, I run the same setup on my machine and use the following code to see whether the error can be reproduced:

```javascript
var Redis = require('ioredis');

var redis = new Redis({
  sentinels: [{ host: '127.0.0.1', port: 7000 }],
  name: 'mymaster'
});

setInterval(function () {
  redis.ping(console.log);
}, 1000);
```

Nothing happened when I killed 6666. Here's my sentinel configuration:

```
sentinel myid 57ed4573534842da2a805a88e32d98d548d05c21
sentinel monitor mymaster 127.0.0.1 5555 2
sentinel down-after-milliseconds mymaster 60000
sentinel config-epoch mymaster 0
port 7000
# Generated by CONFIG REWRITE
dir "/Users/luin"
sentinel leader-epoch mymaster 0
sentinel known-slave mymaster 127.0.0.1 6666
sentinel current-epoch 0
```

Could you enable the debug mode (`DEBUG=ioredis:* node yourapp.js`) and post the logs here if the error still exists?

**Comment by hellish** [comment]
```
Tue, 31 Jan 2017 13:41:06 GMT ioredis:redis write command[0] -> sentinel(sentinels,mymaster)
Tue, 31 Jan 2017 13:41:06 GMT ioredis:redis write command[0] -> sentinel(sentinels,mymaster)
Tue, 31 Jan 2017 13:41:06 GMT ioredis:redis write command[0] -> sentinel(sentinels,mymaster)
Tue, 31 Jan 2017 13:41:06 GMT ioredis:redis write command[0] -> sentinel(sentinels,mymaster)
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:redis write command[0] -> sentinel(sentinels,mymaster)
Tue, 31 Jan 2017 13:41:06 GMT ioredis:redis write command[0] -> sentinel(sentinels,mymaster)
Tue, 31 Jan 2017 13:41:06 GMT ioredis:redis write command[0] -> sentinel(sentinels,mymaster)
Tue, 31 Jan 2017 13:41:06 GMT ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ]
Tue, 31 Jan 2017 13:41:06 GMT ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6666
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:6666
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
Tue, 31 Jan 2017 13:41:08 GMT ioredis:redis status[127.0.0.1:7000]: [empty] -> connecting
Tue, 31 Jan 2017 13:41:08 GMT ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,mymaster)
Tue, 31 Jan 2017 13:41:08 GMT ioredis:redis status[127.0.0.1:7000]: [empty] -> connecting
Tue, 31 Jan 2017 13:41:08 GMT ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,mymaster)
```

**Comment by luin** [comment]
@hellish Seems there is more than one connection are made in your code. Could you use the following code to see if killing the slave crashes the application?

```javascript
var Redis = require('ioredis');

var redis = new Redis({
  sentinels: [{ host: '127.0.0.1', port: 7000 }],
  name: 'mymaster'
});

setInterval(function () {
  redis.ping(console.log);
}, 1000);
```

**Comment by hellish** [comment]
the code u gave me runs ok. and the app is not crashing. it produces the following

```
  ioredis:redis write command[0] -> ping() +979ms
null 'PONG'
  ioredis:redis write command[0] -> ping() +1s
null 'PONG'
  ioredis:redis write command[0] -> ping() +1s
null 'PONG'
  ioredis:redis write command[0] -> ping() +1s
null 'PONG'
  ioredis:redis write command[0] -> ping() +1s
null 'PONG'
  ioredis:redis write command[0] -> ping() +1s
null 'PONG'
  ioredis:redis write command[0] -> ping() +1s
null 'PONG'
  ioredis:redis status[127.0.0.1:6666]: ready -> close +554ms
  ioredis:connection reconnect in 2ms +1ms
  ioredis:redis status[127.0.0.1:6666]: close -> reconnecting +0ms
  ioredis:redis status[127.0.0.1:6666]: reconnecting -> connecting +4ms
  ioredis:SentinelConnector All sentinels are unreachable. Retrying from scratch after 10 +1ms
  ioredis:redis status[127.0.0.1:7000]: [empty] -> connecting +10ms
  ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,mymaster) +0ms
  ioredis:redis status[127.0.0.1:7000]: connecting -> connect +1ms
  ioredis:redis status[127.0.0.1:7000]: connect -> ready +1ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[0] -> sentinel(get-master-addr-by-name,mymaster) +0ms
  ioredis:redis write command[0] -> sentinel(sentinels,mymaster) +1ms
  ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ] +0ms
  ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6666 +2ms
  ioredis:redis status[127.0.0.1:7000]: ready -> close +0ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[127.0.0.1:7000]: close -> end +1ms
  ioredis:redis status[localhost:6379]: connecting -> close +1ms
  ioredis:connection reconnect in 4ms +0ms
  ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
  ioredis:redis status[localhost:6379]: reconnecting -> connecting +4ms
  ioredis:SentinelConnector All sentinels are unreachable. Retrying from scratch after 10 +1ms
...
```

i noticed two things with this:
* since i kill the slave it says All sentinels are unreachable although sentinel runs ok
* and at the end of the logs says that it tries to connect to localhost:6379 which is weird since localhost:6379 is not specified anywhere and since nothing is running there it fails to connect

at the end it reconnects fine once the slave is up and running

**Comment by luin** [comment]
@hellish The two things are normal though the debug logs were somewhat misleading which I will fix in the next version. I think the setup may be misconfigured. What's the configuration of the sentinel? Typically here's what ioredis do when connect to a redis instance via sentinel:

1. Connect to the sentinel (:7000).
2. Ask for the address of the master (Will get :5555).
3. Connect to the master (:5000).
4. Disconnect from the sentinel (:7000).

And when the master is down, ioredis will reconnect from scatch from 1. So obviously the connection process has nothing to do with the slave, so the down of the slave won't affect the application.

**Comment by hellish** [comment]
@luin I'll check again my config. I assumed its correct since I see the following.
```
127.0.0.1:7000> sentinel master mymaster
 1) "name"
 2) "mymaster"
 3) "ip"
 4) "127.0.0.1"
 5) "port"
 6) "5555"
 7) "runid"
 8) "73b4db1a696185bd195c0ea0f5aee86a257b193d"
 9) "flags"
10) "master"
11) "link-pending-commands"
12) "0"
13) "link-refcount"
14) "1"
15) "last-ping-sent"
16) "0"
17) "last-ok-ping-reply"
18) "911"
19) "last-ping-reply"
20) "911"
21) "down-after-milliseconds"
22) "9000"
23) "info-refresh"
24) "1008"
25) "role-reported"
26) "master"
27) "role-reported-time"
28) "61891660"
29) "config-epoch"
30) "214"
31) "num-slaves"
32) "1"
33) "num-other-sentinels"
34) "0"
35) "quorum"
36) "1"
37) "failover-timeout"
38) "180000"
39) "parallel-syncs"
40) "1"

```

it finds 1 master which has 1 slave.

**Comment by luin** [comment]
That's strange that the app connected to :6666 instead of :5555. Can you post the full logs here, including how the connection is made? Here's mine:

```shell
testsentinel ❯ DEBUG=ioredis:* node index.js                       ⏎
  ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
  ioredis:redis status[127.0.0.1:7000]: [empty] -> connecting +3ms
  ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,mymaster) +3ms
  ioredis:redis status[127.0.0.1:7000]: connecting -> connect +5ms
  ioredis:redis status[127.0.0.1:7000]: connect -> ready +0ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[0] -> sentinel(get-master-addr-by-name,mymaster) +1ms
  ioredis:redis write command[0] -> sentinel(sentinels,mymaster) +4ms
  ioredis:SentinelConnector sentinels [ { host: '127.0.0.1', port: 7000 } ] +0ms
  ioredis:redis status[127.0.0.1:5555]: connecting -> connect +11ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[127.0.0.1:7000]: ready -> close +1ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[127.0.0.1:7000]: close -> end +0ms
  ioredis:redis status[127.0.0.1:5555]: connect -> ready +1ms
  ioredis:redis write command[0] -> ping() +979ms
null 'PONG'
  ioredis:redis write command[0] -> ping() +1s
null 'PONG'
  ioredis:redis write command[0] -> ping() +1s
null 'PONG'
  ioredis:redis write command[0] -> ping() +1s
null 'PONG'
  ioredis:redis write command[0] -> ping() +1s
null 'PONG'
```
