### ISSUE TITLE
初始化的时候报错，急～～～

### ISSUE THREAD

**Issue by lgwebdream** [luin/ioredis#372]
【代码】
_this.redis = new _ioredis2.default(6379,RDS_HOST,{password:RDS_PWD,dropBufferSupport:true});
【报错】
[ioredis] Unhandled error event: ReplyError: ERR AUTH Authentication password incomplete.The password is instanceid:password, example: 05719bf0c3ae11e4:123456.
    at JavascriptReplyParser.returnError (/opt/node-publish/study/node_modules/ioredis/lib/redis/parser.js:25:25)
    at JavascriptReplyParser.run (/opt/node-publish/study/node_modules/redis-parser/lib/javascript.js:135:18)
    at JavascriptReplyParser.execute (/opt/node-publish/study/node_modules/redis-parser/lib/javascript.js:112:10)
    at Socket.<anonymous> (/opt/node-publish/study/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)

**Comment by luin** [comment]
用的不是官方的 Redis 吧。错误信息不是写着了么...`ERR AUTH Authentication password incomplete.The password is instanceid:password, example: 05719bf0c3ae11e4:123456 `

**Comment by lgwebdream** [comment]
在我本地是好好的，编译到服务器就不行了。是官方的呢。
import Redis from "ioredis";

        this.redis = new Redis({
            port: RDS_PORT, // Redis port 
            host: RDS_HOST, // Redis host 
            password: RDS_PWD,
            dropBufferSupport: true
        });

**Comment by luin** [comment]
相信我，这个决定不是官方版的 Redis，是修改过的。错误信息说的是密码不完整，格式是 instanceid:password，你只传了后一部分（或前一部分）

**Comment by lgwebdream** [comment]
您的意思是我的Redi服务器 还是 这个模块呢。我用的是 ioredis 直接 install下来的。我需要在install一个 redis模块么？
不好意思啊 追问了好几次。

**Comment by luin** [comment]
我的意思是你线上（服务器上）连的 Redis 服务器是非官方修改版，代码被改过了。Redis 服务器报错说你的密码有错误

**Comment by lgwebdream** [comment]
我直接用redis这个模块是可以连通的，所以我很奇怪。要是redis服务器有问题的话，那redis这个模块也应该挂呢。

**Comment by luin** [comment]
不可能的...和模块没关系，你再仔细检查一下吧

**Comment by lgwebdream** [comment]
我用的就是直接阿里云的redis服务，应该问题不大呢。

**Comment by luin** [comment]
1. 阿里云 Redis 是非官方的，被修改过了；
2. 你现在遇到的问题是密码错误；
3. 不论是 ioredis 还是 redis 模块都会遇到这个问题

**Comment by lgwebdream** [comment]
您的意思我用阿里云的Redis就不能用ioredis了？还是说需要按照 password做什么修改？

**Comment by luin** [comment]
当然可以用 ioredis 了，密码我上面不是说了么。。你现在的密码错了，阿里云要求密码是 instance_id:password，你只提供了 password。

```javascript
new Redis({ password: 'instance_id:password' });
```

把对应的 `instance_id` 和 `password` 换成你的就行了。

**Comment by lgwebdream** [comment]
明白了，非常感谢。

**Comment by fghpdf** [comment]
简直了。。。。。
