### ISSUE TITLE
Crash in returnError() method (item is null).

### ISSUE THREAD

**Issue by markschmid** [luin/ioredis#383]
We're using version 2.4.0 and are seeing a crash in parser.js in the returnError() method.
This is probably because the variable `item` is not checked for null.

```
/<mypath>/node_modules/ioredis/lib/redis/parser.js:48
    name: item.command.name,
              ^

TypeError: Cannot read property 'command' of undefined
    at Redis.exports.returnError (/usr/local/tm/software/node_modules/ioredis/lib/redis/parser.js:48:15)
    at HiredisReplyParser.replyParser.Parser.returnError (/usr/local/tm/software/node_modules/ioredis/lib/redis/parser.js:25:13)
    at HiredisReplyParser.execute (/usr/local/tm/software/node_modules/ioredis/node_modules/redis-parser/lib/hiredis.js:28:18)
    at Socket.<anonymous> (/usr/local/tm/software/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[nodemon] app crashed
```

**Comment by luin** [comment]
That's strange. Did you connect to an official Redis instance or a proxy server? Can you reproduce the issue?

**Comment by markschmid** [comment]
Yes, official Redis instance (cluster configuration). I think it happened because the cluster was not instantiated correctly or something. After I've downgraded to ioredis@2.0.0 it did not crash anymore but showed a DENIED error (https://www.reddit.com/r/redis/comments/3zv85m/new_security_feature_redis_protected_mode/). After I've fixed the redis configuration, it worked again (also with ioredis@2.4.0).

There might be situations, where `item` can be null or undefined and maybe this could be handled in ioredis. It seemed to me that ioredis@2.0.0 did handle this differently than 2.4.0 but I might be mistaken. In any case: We like ioredis a lot and I'm happy our setup works again.

**Comment by thelinuxlich** [comment]
I'm seeing this error too with ioredis 2.4 and redis 3.2 :((((

**Comment by thelinuxlich** [comment]
Hmm I solved this by adding "bind IP" to redis.conf which seems to be required on 3.2+

**Comment by luin** [comment]
Seems there's an issue in ioredis of handling wrong bound IP.
