### ISSUE TITLE
how ioredis cluster to flushdb

### ISSUE THREAD

**Issue by 748890753yiyi** [luin/ioredis#404]
this is my operate：

var redisClient= new Redis.Cluster([{
        port: 7004,
        host: '192.168.80.10'
    },{
        port: 7005,
        host: '192.168.80.19'
    },{
        port: 7007,
        host: '192.168.80.19'
    },{
        port: 7002,
        host: '192.168.80.19'
    },{
        port: 7006,
        host: '192.168.80.19'
    },{
        port: 7008,
        host: '192.168.80.19'
    }]);
//port 7004,7005,7007 is master,port 7002,7006,7008 is slave 
var masters  = redisClient.nodes("master");
                     Promise.all(masters .map(function (node) {
                        return node.flushdb();
                    }));

Unhandled rejection ReplyError: READONLY You can't write against a read only slave.
    at JavascriptReplyParser.replyParser.Parser.returnError (E:\node_modules\ioredis\lib\redis\parser.js:25:25)
    at JavascriptReplyParser.run (E:\node_modules\ioredis\node_modules\redis-parser\lib\javascript.js:135:18)
    at JavascriptReplyParser.execute (E:\node_modules\ioredis\node_modules\redis-parser\lib\javascript.js:112:10)
    at Socket.<anonymous> (E:\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)

**Comment by luin** [comment]
When you create a Cluster instance, ioredis will fetch the node information asynchronously. You need to listen to the `connect` event and get the master nodes after that.

If you really want to run the command synchronously, you can provide `readOnly` property to each node, `true` means the node is a slave.

**Comment by 748890753yiyi** [comment]
@luin thank you very much, the method is right.
