### ISSUE TITLE
question: using Cluster ctor and specifying non-cluster enabled node

### ISSUE THREAD

**Issue by AVVS** [luin/ioredis#41]
Lets assume opts are like this:

```
    "redisCluster": {
        "hosts": [
            { "host": "localhost", "port": 6379 }
        ],
        "options": {

        }
    },
```

Then I create cluster connection:

```js
var clusterClient = new Redis.Cluster(config.redisCluster.hosts, config.redisCluster.options);
```

Redis is 3.x, but cluster mode is disabled for this instances on my local machine. The behaviour in the result is the following:

```
22:09:53 ng.ark.com: Connected to AMQP
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Cluster.addListener (events.js:160:15)
  at Cluster.once (events.js:185:8)
  at Cluster.<anonymous> (/Users/vitaly/projects/api_v2/node_modules/ioredis/lib/cluster.js:87:10)
  at tryCatcher (/Users/vitaly/projects/api_v2/node_modules/bluebird/js/main/util.js:24:31)
  at Promise._resolveFromResolver (/Users/vitaly/projects/api_v2/node_modules/bluebird/js/main/promise.js:427:31)
  at new Promise (/Users/vitaly/projects/api_v2/node_modules/bluebird/js/main/promise.js:53:37)
  at Cluster.connect (/Users/vitaly/projects/api_v2/node_modules/ioredis/lib/cluster.js:65:10)
  at Cluster.<anonymous> (/Users/vitaly/projects/api_v2/node_modules/ioredis/lib/cluster.js:99:16)
  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Cluster.addListener (events.js:160:15)
  at Cluster.once (events.js:185:8)
  at Cluster.<anonymous> (/Users/vitaly/projects/api_v2/node_modules/ioredis/lib/cluster.js:88:10)
  at tryCatcher (/Users/vitaly/projects/api_v2/node_modules/bluebird/js/main/util.js:24:31)
  at Promise._resolveFromResolver (/Users/vitaly/projects/api_v2/node_modules/bluebird/js/main/promise.js:427:31)
  at new Promise (/Users/vitaly/projects/api_v2/node_modules/bluebird/js/main/promise.js:53:37)
  at Cluster.connect (/Users/vitaly/projects/api_v2/node_modules/ioredis/lib/cluster.js:65:10)
  at Cluster.<anonymous> (/Users/vitaly/projects/api_v2/node_modules/ioredis/lib/cluster.js:99:16)
  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

I havent really dug into the code, but it seems like .connect is called multiple times and previous event listeners are not removed. Maybe this is specific to the wrong configuration (using cluster ctor on non-cluster node), but maybe not. Should probably look at the error handling here

**Comment by luin** [comment]
Looks like to be the same problem as https://github.com/luin/ioredis/commit/f663fe236d4b83d3f836e61748906eb9952a6211. I'm looking into it.
