### ISSUE TITLE
ioredis fails to connect to redis sever after a flush operations via redis-cli

### ISSUE THREAD

**Issue by altanai** [luin/ioredis#427]
Everytime I do a flushall on the redis server ( in cluster mode)  ioredis gives this error . 
```
[ioredis] Unhandled error event: Error: Failed to refresh slots cache.
    at tryNode (/usr/local/lib/node_modules/ioredis/lib/cluster/index.js:371:19)
    at /usr/local/lib/node_modules/ioredis/lib/cluster/index.js:383:9
    at /usr/local/lib/node_modules/ioredis/lib/cluster/index.js:587:14
    at run (/usr/local/lib/node_modules/ioredis/lib/utils/index.js:150:16)
    at tryCatcher (/usr/local/lib/node_modules/ioredis/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/usr/local/lib/node_modules/ioredis/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/usr/local/lib/node_modules/ioredis/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ioredis/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/ioredis/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/usr/local/lib/node_modules/ioredis/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/ioredis/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/ioredis/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

I am using ioredis to connect to redis servers cluster via 

```
client = new Redis.Cluster(redisClusters, {
			retryDelayOnFailover : '100'
		});
```

where redisClusters is an array of following objects 

      {
        "host": "1.2.3.4",
        "port": "6379"
      }

**Comment by luin** [comment]
Try to listen to the "error" event to see what the error is:

```javascript
client = new Redis.Cluster(redisClusters, {
			retryDelayOnFailover : '100'
		});
client.on('error', function (err) {
  console.log(err.lastNodeError);
});
```
