### ISSUE TITLE
[ioredis] Unhandled error event: Error

### ISSUE THREAD

**Issue by tuananh** [luin/ioredis#444]
Can anyone help me how to debug this? The error is very vague `[ioredis] Unhandled error event: Error`

I checked the redis server and it's working fine.

```
var redis = new Redis(config.redisPort, config.redisHost, {
    keyPrefix: config.redisPrefix || 'test:',
    password: config.redisPassword
})
```

```
DEBUG=ioredis:* node index.js
  ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
  ioredis:redis status[localhost:6379]: [empty] -> connecting +241ms
  ioredis:redis status[localhost:6379]: [empty] -> connecting +3ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +22ms
  ioredis:redis write command[0] -> auth(mypassword) +2ms
  ioredis:redis write command[0] -> info() +1ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +2ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +0ms
  ioredis:redis write command[0] -> info() +1ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +17ms
[ioredis] Unhandled error event: Error
    at JavascriptReplyParser.returnError (/home/ubuntu/src/example/node_modules/ioredis/lib/redis/parser.js:25:25)
    at JavascriptReplyParser.run (/home/ubuntu/src/example/node_modules/redis-parser/lib/javascript.js:135:18)
    at JavascriptReplyParser.execute (/home/ubuntu/src/example/node_modules/redis-parser/lib/javascript.js:112:10)
    at Socket.<anonymous> (/home/ubuntu/src/example/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:563:20)
```

**Comment by luin** [comment]
Try to attach the error event and log the error:

```javascript
redis.on('error', function (error) {
  console.dir(error)
})
```

**Comment by tuananh** [comment]
@luin 

I added it but it's not printing any extra error, not even the `@@@` string below.

```
redis.on('error', function (error) {
  console.log('@@@@@@@@@@')
  console.dir(error)
})
```

**Comment by luin** [comment]
What ioredis version are you using?

**Comment by tuananh** [comment]
`cat node_modules/ioredis/package.json  | grep version` show it's at `2.5.0`

**Comment by WClouds** [comment]
Meet the same error!

**Comment by luin** [comment]
@tuananh @WClouds Could you confirm that there's only one Redis instance is created so that the "Unhandled error" can't be emitted from other instances that not bound the "error" event?

**Comment by tuananh** [comment]
@luin it was indeed caused by another instance in another file which i forgot to remove the require. Thanks for helping me debug it.
