### ISSUE TITLE
I use the way by promise, but I got an error, what should i do?

### ISSUE THREAD

**Issue by Sailor20** [luin/ioredis#495]
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
ReplyError: ERR unknown command 'select'
     at JavascriptReplyParser.returnError (/u/data/nodejs/live-server/node_modules/ioredis/lib/redis/parser.js:25:25)
     at JavascriptReplyParser.run (/u/data/nodejs/live-server/node_modules/redis-parser/lib/javascript.js:135:18)
     at JavascriptReplyParser.execute (/u/data/nodejs/live-server/node_modules/redis-parser/lib/javascript.js:112:10)
     at Socket.<anonymous> (/u/data/nodejs/live-server/node_modules/ioredis/lib/redis/event_handler.js:107:22)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at readableAddChunk (_stream_readable.js:176:18)
     at Socket.Readable.push (_stream_readable.js:134:10)
     at TCP.onread (net.js:547:20)

**Comment by luin** [comment]
What version of Redis server are you using? Is it the official version? It seems that `select` command is not supported in that instance, so selecting database will raise the error.

**Comment by tuananh** [comment]
Looks like he's using a proxy in front of redis. Twemproxy and Dynomite do not support SELECT command.
