### ISSUE TITLE
Cluster mode issue with redis in k8s

### ISSUE THREAD

**Issue by yacut** [luin/ioredis#517]
I have a cluster issue in k8s. I've try just set and get one key. 
The simple app looks like:
```javascript
var redis = new Redis.Cluster([
                    {port: "6379", host: "redis-cluster-0.redis-cluster.default.svc.cluster.local"},
                    {port: "6379", host: "redis-cluster-1.redis-cluster.default.svc.cluster.local"},
                    {port: "6379", host: "redis-cluster-2.redis-cluster.default.svc.cluster.local"},
                    {port: "6379", host: "redis-cluster-3.redis-cluster.default.svc.cluster.local"},
                    {port: "6379", host: "redis-cluster-4.redis-cluster.default.svc.cluster.local"},
                    {port: "6379", host: "redis-cluster-5.redis-cluster.default.svc.cluster.local"},
                ], {
                    enableReadyCheck: true,
                    scaleReads: "all", //"slave",
                    redisOptions:{
                        active: true,
                        inMemory: false,
                        redis: {
                            db: 0,
                            sentinels: false,
                            name: "bla",
                            keyPrefix: "prefix:"
                        },
                        enableOfflineQueue: false,
                        reconnectOnError: (error) =>{
                            debug("Reconnect", error);
                        },
                        ttl: 3600
                    }
                });
redis.on("error", error => debug("error", error));
redis.on("node error", error => debug("node error", error));
redis.on("connect", () => debug("connected"));
redis.on("ready", () => {
  debug("ready");
  debug("all", this.redis.nodes("all").length);
  debug("master", this.redis.nodes("master").length);
  debug("slave", this.redis.nodes("slave").length);
});
redis.on("close", () => debug("close"));
redis.on("reconnecting", () => debug("reconnecting"));
redis.on("end", () => debug("end"));
redis.set("test", "are-you-okay?", "EX", 1000).timeout(1000).catch(debug);

```
With DEBUG=* I have logs loop:
```shell
  ioredis:cluster status: [empty] -> connecting +0ms
  ioredis:redis status[redis-cluster-0.redis-cluster.default.svc.cluster.local:6379]: [empty] -> wait +83ms
  ioredis:redis status[redis-cluster-1.redis-cluster.default.svc.cluster.local:6379]: [empty] -> wait +1ms
  ioredis:redis status[redis-cluster-2.redis-cluster.default.svc.cluster.local:6379]: [empty] -> wait +0ms
  ioredis:redis status[redis-cluster-3.redis-cluster.default.svc.cluster.local:6379]: [empty] -> wait +0ms
  ioredis:redis status[redis-cluster-4.redis-cluster.default.svc.cluster.local:6379]: [empty] -> wait +1ms
  ioredis:redis status[redis-cluster-5.redis-cluster.default.svc.cluster.local:6379]: [empty] -> wait +0ms
  ioredis:cluster getting slot cache from redis-cluster-1.redis-cluster.default.svc.cluster.local:6379 +1ms
  ioredis:redis status[redis-cluster-1.redis-cluster.default.svc.cluster.local:6379]: wait -> connecting +3ms
  ioredis:redis status[redis-cluster-5.redis-cluster.default.svc.cluster.local:6379]: wait -> connecting +3ms
my-service set { key: 'prefix:test:1539a6b9-3470-4da1-b37d-29ca7602f91a',
  val: 'are-you-okay?',
  ttl: 15 } +99ms
my-service node error Error: Stream isn't writeable and enableOfflineQueue options is false
    at Redis.sendCommand (/usr/src/app/node_modules/ioredis/lib/redis.js:578:20)
    at Redis.cluster (/usr/src/app/node_modules/ioredis/lib/commander.js:131:17)
    at Cluster.getInfoFromNode (/usr/src/app/node_modules/ioredis/lib/cluster/index.js:588:9)
    at tryNode (/usr/src/app/node_modules/ioredis/lib/cluster/index.js:380:11)
    at Cluster.refreshSlotsCache (/usr/src/app/node_modules/ioredis/lib/cluster/index.js:395:3)
    at Cluster.<anonymous> (/usr/src/app/node_modules/ioredis/lib/cluster/index.js:173:10)
    at Promise._execute (/usr/src/app/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/usr/src/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/src/app/node_modules/bluebird/js/release/promise.js:79:10)
    at Cluster.connect (/usr/src/app/node_modules/ioredis/lib/cluster/index.js:132:10)
    at new Cluster (/usr/src/app/node_modules/ioredis/lib/cluster/index.js:88:10)

  ioredis:redis status[10.90.237.161:6379]: connect -> close +1ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[10.90.237.161:6379]: close -> end +0ms
  ioredis:redis status[10.90.228.59:6379]: connect -> close +1ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[10.90.228.59:6379]: close -> end +0ms
  ioredis:cluster status: connecting -> close +0ms
  ioredis:cluster status: close -> reconnecting +0ms
  ioredis:cluster Cluster is disconnected. Retrying after 118ms +119ms
  ioredis:cluster status: reconnecting -> connecting +0ms
  ioredis:redis status[redis-cluster-0.redis-cluster.default.svc.cluster.local:6379]: [empty] -> wait +1ms
  ioredis:redis status[redis-cluster-1.redis-cluster.default.svc.cluster.local:6379]: [empty] -> wait +0ms
  ioredis:redis status[redis-cluster-2.redis-cluster.default.svc.cluster.local:6379]: [empty] -> wait +76ms
  ioredis:redis status[redis-cluster-3.redis-cluster.default.svc.cluster.local:6379]: [empty] -> wait +1ms
  ioredis:redis status[redis-cluster-4.redis-cluster.default.svc.cluster.local:6379]: [empty] -> wait +0ms
  ioredis:redis status[redis-cluster-5.redis-cluster.default.svc.cluster.local:6379]: [empty] -> wait +0ms
  ioredis:cluster getting slot cache from redis-cluster-3.redis-cluster.default.svc.cluster.local:6379 +0ms
  ioredis:redis status[redis-cluster-3.redis-cluster.default.svc.cluster.local:6379]: wait -> connecting +1ms
  ioredis:redis status[redis-cluster-4.redis-cluster.default.svc.cluster.local:6379]: wait -> connecting +0ms
``` 

The redis cli works on same machine. To set key:
```shell
$ redis-cli -h redis-cluster-1.redis-cluster.default.svc.cluster.local -c
redis-cluster-1.redis-cluster.default.svc.cluster.local:6379> get foo
-> Redirected to slot [12182] located at 10.90.237.161:6379
"bar"
10.90.237.161:6379> set fooo baaar
OK
```
Ana get key:
```shell
$ redis-cli -h redis-cluster-1.redis-cluster.default.svc.cluster.local -c
redis-cluster-1.redis-cluster.default.svc.cluster.local:6379> get fooo
-> Redirected to slot [3916] located at 10.90.237.161:6379
"baaar"
```

What do I wrong? Any Idea?

**Comment by luin** [comment]
I'm closing this. Feel free to reopen it if the problem still exists.

**Comment by leoDreamer** [comment]
@yacut I have a question when connect to k8s's redis cluster , can i use svc node in ioredis config?

**Comment by yacut** [comment]
@leoDreamer If you have sentinel on each node, you can do it. I had this setup before and it's never works great. I think, it will be better to create one svc for master and one svc for slaves ([like redis chart do](https://github.com/kubernetes/charts/tree/master/stable/redis)), and put them both to the ioredis config.

**Comment by leoDreamer** [comment]
@yacut Thanks for reply, actually our OPS use one proxy svc node, I can't find the relevant config in ioredis. I know it now, thanks agin
