### ISSUE TITLE
keyspace events in a clustered environment

### ISSUE THREAD

**Issue by geogeim** [luin/ioredis#520]
I'm trying to use keyspace events with ioredis in a cluster environment with 2 machines and 4 instances per machine. From what i've read the expired events are emitted on the local node in the cluster and are not broadcasted to the whole cluster, so i'm enumerating every node in the cluster, update the configuration and subscribe to the event. This works if i try to connect  on a dev environment with only one machine, but when I try to connect to the prod environment i get the exception below.

If I wait for the 'ready' event everything seems to work fine. 
Does this mean that the connection retry and buffering logic does not work for individual nodes?
How about the auto resubscription on connection failure?

```
redisSub.on("pmessage", subscriber);
return Promise.all(redisSub.nodes('master').map(function (node) {
  return node.config('SET', "notify-keyspace-events", "Ex").then(function () { <- here
    return node.psubscribe('__keyevent@0__:expired');
  });
})).then(function () {
```
``` 
Error: Connection is closed.
    at close (project\common\node_modules\ioredis\lib\redis\event_handler.js:101:21)
    at Socket.<anonymous> (project\common\node_modules\ioredis\lib\redis\event_handler.js:76:14)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
From previous event:
    at Command.initPromise (project\common\node_modules\ioredis\lib\command.js:63:18)
    at new Command (project\common\node_modules\ioredis\lib\command.js:51:8)
    at Redis.psubscribe (project\common\node_modules\ioredis\lib\commander.js:131:29)
    at project\session\gc.js:68:21
From previous event:
    at project\session\gc.js:67:65 <- here
    at Array.map (native)
    at project\session\gc.js:66:49
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by luin** [comment]
A `Cluster` will create multiple `Redis` instances, each instance connecting to a Redis server of the cluster. Every instance has `retryStrategy` set to null, which means ioredis won't auto reconnect when the connection is closed. Instead, ioredis will refresh the nodes in the cluster and create the new instance connecting to the new server.

You may want to listen to the `-node` and `+node` event to know when a node is destroyed or created.
