### ISSUE TITLE
"TypeError: str.charCodeAt is not a function" when using Buffers as keys in cluster-mode

### ISSUE THREAD

**Issue by philipp-cliqz** [luin/ioredis#593]
Though using binary data as keys (represented as a "Buffer" in JavaScript) works as expected in non-cluster mode, it breaks when you are running Redis in cluster mode:

```
 TypeError: str.charCodeAt is not a function
     at toUTF8Array (/group-sign/server/node_modules/cluster-key-slot/lib/index.js:93:16)
     at generate (/group-sign/server/node_modules/cluster-key-slot/lib/index.js:133:14)
     at Command.getSlot (/group-sign/server/node_modules/ioredis/lib/command.js:88:19)
     at Cluster.sendCommand (/group-sign/server/node_modules/ioredis/lib/cluster/index.js:440:47)
     at Cluster.set (/group-sign/server/node_modules/ioredis/lib/commander.js:131:17)
    ...
```

Looks like in the call to the the cluster-key-slot library, the key is expected to be a String, not a Buffer:
https://github.com/luin/ioredis/blob/master/lib/command.js#L90 

In non-cluster mode, the code is not executed as there is no need to compute the slot. I assume that is why it works there.

(As a workaround, I have switched to Strings for the keys.)

**Comment by tinder-xhao** [comment]
Is there any update about this issue? I'm encountering the same problem here

**Comment by tuananh** [comment]
similar to #637

**Comment by philipp-classen** [comment]
@tuananh You are right, it is a duplicate of the new #637 ticket.
