### ISSUE TITLE
Unhandled rejection ReplyError: CROSSSLOT Keys in request don't hash to the same slot 

### ISSUE THREAD

**Issue by anuradhag** [luin/ioredis#626]
Hello there,

I am using ioredis to enable redis cluster usage to set and purge keys. On purging keys, I get the above error. The purge happens anyway. When I use the redis instance in expressjs middleware I get this error otherwise I dont.

I am using 4.10.x as the express version.

```
var express = require('express');
var expressSession = require("express-session");
var sessionStorage = require('connect-redis')(expressSession);
var redis = require('ioredis');
var config = require('./config');var app = express();

var client = new redis.Cluster([{
	host: config.session.host,
	port: config.session.port,
	password: config.session.pass,
	ttl: config.session.ttl
}]);

app.use(expressSession({
  unset: "destroy",
  saveUninitialized: false,
  resave: false,
  secret: config.session.secret,
  store: new sessionStorage({
		client: client,
		ttl: config.session.ttl,
    prefix: '{sess}.'
  }),
  key: "authorization.sid",
  cookie: {maxAge: config.session.maxAge}
}))

app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.json());

app.post('/login', function(req, res) {
	if(req.user) {
		return res.redirect('/home');
	}

	if (req.body.username === 'Anu' && req.body.password === 'Password') {
		req.logIn({name: 'Anu'}, function(err) {
			return res.redirect('/home');
		})
	} else {
		return res.send(400);
	}
})

app.get('/logout', function(req, res) {
	req.logout();
})

var port = process.env.PORT || '3000';
app.listen(port);
```

Note: I get this error only when I use it in the express middleware and not when using the io-redis package seperately.

Actually everything works fine except for express logging this unhandled error.

**Comment by anuradhag** [comment]
Having raised this issue with them too https://github.com/expressjs/express/issues/3646

**Comment by luin** [comment]
This error is not ioredis related. It happens when calling a multiple-keys command (such as `mget`).

**Comment by anuradhag** [comment]
```
Unhandled rejection ReplyError: CROSSSLOT Keys in request don't hash to the same slot
  at JavascriptRedisParser.replyParser.Parser.returnError (/usr/src/app/node_modules/ioredis/lib/redis/parser.js:24:25)
at JavascriptRedisParser.execute (/usr/src/app/node_modules/redis-parser/lib/parser.js:572:12)
at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/lib/redis/event_handler.js:107:22)
at emitOne (events.js:90:13)
at Socket.emit (events.js:182:7)
at readableAddChunk (_stream_readable.js:147:16)
at Socket.Readable.push (_stream_readable.js:111:10)
at TCP.onread (net.js:523:20)
```

**Comment by anuradhag** [comment]
I get this above stack trace every 10 seconds, even when my app is idle. Not sure, If it is something to do with my configuration. How do I proceed further? Please help.

**Comment by luin** [comment]
Just looked into the code of connect-redis. It seems connect-redis doesn't support Redis cluster, so you need use `new redis` instead of `new redis.Cluster`.

**Comment by armenr** [comment]
...wait, so you can't use  connect-redis with redis cluster/?
