### ISSUE TITLE
DeprecationWarning: The Buffer() and new Buffer() constructors are not recommended

### ISSUE THREAD

**Issue by dex4er** [luin/ioredis#627]
Hi.

With `NODE_OPTIONS='--pending-deprecation --throw-deprecation'` and Node 10:

```
DeprecationWarning: The Buffer() and new Buffer() constructors are not recommended for use due to security and usability concerns. Please use the new Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() construction methods instead.
      at showFlaggedDeprecation (buffer.js:127:13)
      at new Buffer (buffer.js:148:3)
      at bufferAlloc (/Users/dexter/src/project/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:21:47)
      at Object.<anonymous> (/Users/dexter/src/project/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:7:18)
      at Module._compile (module.js:652:30)
      at Object.Module._extensions..js (module.js:663:10)
      at Module.load (module.js:565:32)
      at tryModuleLoad (module.js:505:12)
      at Function.Module._load (module.js:497:3)
      at Module.require (module.js:596:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (/Users/dexter/src/project/node_modules/ioredis/node_modules/redis-parser/index.js:3:18)
      at Module._compile (module.js:652:30)
      at Object.Module._extensions..js (module.js:663:10)
      at Module.load (module.js:565:32)
      at tryModuleLoad (module.js:505:12)
      at Function.Module._load (module.js:497:3)
      at Module.require (module.js:596:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (/Users/dexter/src/project/node_modules/ioredis/lib/redis/parser.js:7:14)
      at Module._compile (module.js:652:30)
      at Object.Module._extensions..js (module.js:663:10)
      at Module.load (module.js:565:32)
      at tryModuleLoad (module.js:505:12)
      at Function.Module._load (module.js:497:3)
      at Module.require (module.js:596:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (/Users/dexter/src/project/node_modules/ioredis/lib/redis.js:638:27)
      at Module._compile (module.js:652:30)
      at Object.Module._extensions..js (module.js:663:10)
      at Module.load (module.js:565:32)
      at tryModuleLoad (module.js:505:12)
      at Function.Module._load (module.js:497:3)
      at Module.require (module.js:596:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (/Users/dexter/src/project/node_modules/ioredis/index.js:3:28)
      at Module._compile (module.js:652:30)
      at Object.Module._extensions..js (module.js:663:10)
      at Module.load (module.js:565:32)
      at tryModuleLoad (module.js:505:12)
      at Function.Module._load (module.js:497:3)
      at Module.require (module.js:596:17)
      at require (internal/module.js:11:18)
```

**Comment by luin** [comment]
Fixed in v4.0.0-2. Thank you for pointing this out!
