### ISSUE TITLE
unable to use command info <command> with redis.call

### ISSUE THREAD

**Issue by tuananh** [luin/ioredis#628]
i'm unable to use this `command info <command>` with redis.call?

```js
const info = await redis.call(['command', 'info', 'set'])
```

getting this errror

```
TypeError: Cannot read property 'command' of undefined
    at Redis.exports.returnError (/Users/anh/code/test/node_modules/ioredis/lib/redis/parser.js:42:16)
    at JavascriptRedisParser.returnError (/Users/anh/code/test/node_modules/ioredis/lib/redis/parser.js:24:13)
    at JavascriptRedisParser.execute (/Users/anh/code/test/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/Users/anh/code/test/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
```

**Comment by luin** [comment]
What ioredis version & Redis version did you use?

**Comment by tuananh** [comment]
`"ioredis": "3.2.2"` and redis `4.0.1`

**Comment by luin** [comment]
It turns out the first argument for the `call` method is special that it should be a string. The following two are valid:

```javascript
redis.call('command', 'info', 'set')
redis.call('command', ['info', 'set'])
```

**Comment by tuananh** [comment]
Thank you.
