### ISSUE TITLE
sentinel connect unhandled error

### ISSUE THREAD

**Issue by luckyscript** [luin/ioredis#635]
```
Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms.
```
but I can reach all sentinels server,and all redis operator is ok.

so, I dont understand why this error shown frequently.

wish solutions, sincerely.

**Comment by zluo001** [comment]
I‘m get the same problem, but the detail error message is
 Unhandled error event: Error: connect ETIMEDOUT
    at Socket.<anonymous> (/node_modules/ioredis/lib/redis.js:289:21) 
Also, I can access all sentinel servers.

**Comment by luin** [comment]
Sorry for the late response. Could you enable the debug log (DEBUG=ioredis:* node yourapp.js) and post the logs here?

**Comment by luckyscript** [comment]
``` 
ioredis:redis status[10.27.18.227:26379]: ready -> close +1ms
  ioredis:connection skip reconnecting since the connection is manually closed. +1ms
  ioredis:redis status[10.27.18.227:26379]: close -> end +0ms
  ioredis:redis status[10.37.65.92:6379]: connect -> ready +0ms
  ioredis:redis status[10.37.65.92:6379]: ready -> close +4s
  ioredis:connection reconnect in 50ms +6ms
  ioredis:redis status[10.37.65.92:6379]: close -> reconnecting +1ms
  ioredis:redis status[10.37.65.92:6379]: reconnecting -> connecting +52ms
  ioredis:SentinelConnector All sentinels are unreachable. Retrying from scratch after 10ms +0ms
[2018-07-02 09:02:14.104] [ERROR] console - [ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms
    at connectToNext (E:\*\node_modules\ioredis\lib\connectors\sentinel_connector.js:64:19)
    at SentinelConnector.connect (E:\*\node_modules\ioredis\lib\connectors\sentinel_connector.js:44:3)
    at Redis.<anonymous> (E:\*\node_modules\ioredis\lib\redis.js:264:20)
    at Promise._execute (E:\*\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (E:\*\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (E:\*\node_modules\bluebird\js\release\promise.js:79:10)
    at Redis.connect (E:*\node_modules\ioredis\lib\redis.js:250:10)
    at Timeout._onTimeout (E:\*\node_modules\ioredis\lib\redis\event_handler.js:95:12)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  ioredis:redis status[10.27.18.228:26379]: [empty] -> connecting +12ms
  ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,d_c10943_1) +3ms
  ioredis:redis status[10.27.18.228:26379]: connecting -> connect +1ms
  ioredis:redis status[10.27.18.228:26379]: connect -> ready +0ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[0] -> sentinel(get-master-addr-by-name,d_c10943_1) +1ms
  ioredis:redis write command[0] -> sentinel(sentinels,d_c10943_1) +1ms
  ioredis:SentinelConnector sentinels [ { host: '10.27.18.228', port: 26379 },
  { host: '10.27.18.227', port: 26379 },
  { host: '10.27.18.225', port: 26379 } ] +1ms
  ioredis:SentinelConnector resolved: 10.37.65.92:6379 +0ms
  ioredis:redis status[10.37.65.92:6379]: connecting -> connect +1ms
  ioredis:redis write command[0] -> info() +1ms
  ioredis:redis status[10.27.18.228:26379]: ready -> close +0ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[10.27.18.228:26379]: close -> end +1ms
  ioredis:redis status[10.37.65.92:6379]: connect -> ready +0ms
```
thanks for the response.Above is the debug log, it seems like network error, but I can reach all sentinel ip  
 in fact.

**Comment by dasaripravin-developer** [comment]
Hello luin,

I am facing the same issue on the ioredis@4.14.0 version. so this bug is still not solved.
can you suggest to me, what I need to do to solve the below issue?

[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms. Last error: Connection is closed.
    at Promise (/usr/local/share/Node/NodeProject/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at new Promise (<anonymous>)
    at connectToNext (/usr/local/share/Node/NodeProject/node_modules/ioredis/built/connectors/SentinelConnector/index.js:41:37)
    at resolve (/usr/local/share/Node/NodeProject/node_modules/ioredis/built/connectors/SentinelConnector/index.js:100:29)
    at client.sentinel (/usr/local/share/Node/NodeProject/node_modules/ioredis/built/connectors/SentinelConnector/index.js:139:24)
    at tryCatcher (/usr/local/share/Node/NodeProject/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/usr/local/share/Node/NodeProject/node_modules/standard-as-callback/built/index.js:30:51)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by dasaripravin-developer** [comment]
Hello luin,

I am facing the same issue on the ioredis@4.14.0 version. so this bug is still not solved.
can you suggest to me, what I need to do to solve the below issue?

[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms. Last error: Connection is closed.

**Comment by gwiater** [comment]
This problem still exists in new version 5.2.4

`[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms.
at connectToNext (node_modules/ioredis/built/connectors/SentinelConnector/index.js:64:31)
at SentinelConnector.connect (node_modules/ioredis/built/connectors/SentinelConnector/index.js:120:16)
at node_modules/ioredis/built/Redis.js:121:64
at new Promise (<anonymous>)
at EventEmitter.connect (node_modules/ioredis/built/Redis.js:103:25)
at Timeout._onTimeout (node_modules/ioredis/built/redis/event_handler.js:164:18)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)`

when it will be solved?

**Comment by Mahfuz2811** [comment]
I am facing the same issue in the latest version 5.2.5

**Comment by Harsh246** [comment]
> I am facing the same issue in the latest version 5.2.5

Hi, Do you managed to figure out this?

**Comment by ChrisNoSim** [comment]
Same problem here. We getting that error message from time-to-time, but all REDIS pods are running healthy in GKE (using bitnami chart).

**Comment by GD-Dheer** [comment]
Any updates on this issue?

**Comment by faizan1990** [comment]
Can we please get an update on this? This is going to make us continue our search for a good node client that supports sentinel and doesn't throw errors for no apparent reason. Thanks

**Comment by luin** [comment]
Can you enable logs with `DEBUG=ioredis:* node yourapp.js` and send them here? Without logs, it's hard to say whether it's a networking issue or not. A minimal reproducible example would make debugging much easier.

**Comment by Mahfuz2811** [comment]
@Harsh246 In my case the problem was, I had provided a sentinel password during connection, but actually, the sentinel has no password.

**Comment by morsmodr** [comment]
@luin I am experiencing similar issues as well, but the thing is I am using a distroless node image on my docker container & cannot add debug to it. ioredis version `5.3.2`

at connectToNext (/app/node_modules/ioredis/built/connectors/SentinelConnector/index.js:117:24)
at connectToNext (/app/node_modules/ioredis/built/connectors/SentinelConnector/index.js:64:31)
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 410ms. Last error: NOAUTH Authentication required.

**Comment by maxbronnikov10** [comment]
why u close this issue? We still have this problem. Can u give some feedback?

**Comment by VikramMaiya** [comment]
I am still facing the issue with the latest ioredis version. Any updates or reasons for it ?

**Comment by maxbronnikov10** [comment]
Set timeout to 0 in redis settings

**Comment by Kev1ntan** [comment]
any update how to solve this issue @luin ?
