### ISSUE TITLE
Connection in subscriber mode, only subscriber commands may be used

### ISSUE THREAD

**Issue by zxtyjx** [luin/ioredis#656]
我在使用socket.io连接redis集群时，会出现以下错误，麻烦帮忙看下是怎么导致的，谢谢～～～～～

Unhandled rejection Error: Connection in subscriber mode, only subscriber commands may be used
    at Redis.sendCommand (/home/socket-server/node_modules/ioredis/lib/redis.js:562:20)
    at tryConnection (/home/socket-server/node_modules/ioredis/lib/cluster/index.js:537:13)
    at Cluster.sendCommand (/home/socket-server/node_modules/ioredis/lib/cluster/index.js:479:3)
    at Cluster.publish (/home/socket-server/node_modules/ioredis/lib/commander.js:131:17)
    at /home/socket-server/node_modules/socket.io-redis/index.js:470:11
    at tryCatcher (/home/socket-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/home/socket-server/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/home/socket-server/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/home/socket-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/socket-server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/socket-server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/socket-server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/socket-server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by luin** [comment]
这个问题发生的原因是 redis.subscribe() 后还执行了其他命令。如果需要执行其他命令的话需要新建个连接，在新连接处理，不要复用给 socket.io 的连接。

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________
