### ISSUE TITLE
redis.my_command results in Promise Rejection: ERR unknown command 'evalsha'

### ISSUE THREAD

**Issue by Danver97** [luin/ioredis#704]
Hello everyone!
I've started using this awesome module, but I got into this problem:
I need to do some conditional redis command if a key is present in a list. Needless to say, I figured out I need Lua Scripting.
Here's what is in the documentations:
```javascript
redis.defineCommand('echo', {
  numberOfKeys: 2,
  lua: 'return {KEYS[1],KEYS[2],ARGV[1],ARGV[2]}'
});
 
// Now `echo` can be used just like any other ordinary command,
// and ioredis will try to use `EVALSHA` internally when possible for better performance.
redis.echo('k1', 'k2', 'a1', 'a2', function (err, result) {
  // result === ['k1', 'k2', 'a1', 'a2']
});
```
Pretty straight forward, BUT when i call `await redis.my_command()` I get an `Unhandled Promise rejection: ERR unknown command 'evalsha'`.
Ok, maybe I should not use promises and from this: 
```javascript
redis.my_command((err, result) => {
  console.log(err);
  console.log(result);
})
```
...I got:
```
{ ReplyError: ERR unknown command 'evalsha'
    at parseError (D:\Users\christian\Desktop\Microservices\restaurant-catalog-service\node_modules\ioredis\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (D:\Users\christian\Desktop\Microservices\restaurant-catalog-service\node_modules\ioredis\node_modules\redis-parser\lib\parser.js:302:14)
  command:
   { name: 'evalsha',
     args:
      [ '745fc99e4929cfb80d636dffd0ff0399b81acc9c',
        '4',
        'abc:processingList',
        'abc:publishedList',
        'abc:processingListSortedSet',
        '11111' ] } }
undefined
```

Here's my code:
```javascript
const renqueueIfPresent = "count = redis.call('lrem', KEY[1], 1, KEY[4]) if ( count == 1 ) then redis.call('rpush', KEY[3], KEY[4]) redis.call('zrem', KEY[2], KEY[4]) redis.call('publish', KEY[2], KEY[4]) end";

redis.defineCommand('renqueueIfPresent', {
    numberOfKeys: 4,
    lua: renqueueIfPresent,
});

async function strategy2(ch, message) {
  console.log('\tchecker!');
  await redis.zadd(keys.processingListSS, Date.now(), message);
  setTimeout(async () => {
      redis.renqueueIfPresent(keys.processingList, keys.publishedList, keys.processingListSS, message, (err, result) => {
          console.log(err);
          console.log(result);
      });
      console.log('executed');
  }, 100);
}

sub.on('message', strategy2);

// subscription...
```
More informations: 
- I'm running this piece of code on a child process (I don't think it would be a problem)
- The properties of the object `keys` have been properly checked as well as `message` value
- I discovered that calling `await redis.eval()` and `await redis.evalsha()` (with or without arguments) give similar errors (even if these functions are not documented).

Maybe the problem is a wrong Lua script? Or is it a bug?

Thanks so much for your help!

**Comment by Danver97** [comment]
Figured out after 3μs after publishing this issue (using a Redis console) that I'm running an old Redis version (pre 2.6) that not support EVAL commands.
Closing this issue.
