### ISSUE TITLE
multi() still executes other commands even if one command fails, is not transactional

### ISSUE THREAD

**Issue by DanielJoyce** [luin/ioredis#706]
From a test

let x = await client.multi()
            .hmset("derp", [ "a", "b", "c" ])
            .hmset("derp", [ "a", "b", "c", "d" ])
            .hgetall("derp")
            .exec((err, result) => console.log("ERROR", err, result));
          console.log(x);

```
ERROR null [ [ ReplyError: ERR wrong number of arguments for HMSET
        at parseError (/home/daniel/git/tesla-data-point/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/home/daniel/git/tesla-data-point/node_modules/redis-parser/lib/parser.js:302:14) ],
  [ null, 'OK' ],
  [ null, { a: 'b', c: 'd' } ] ]

```

Per the docs, multi() is supposed to fail like this

```
redis.multi().set('foo').set('foo', 'new value').exec(function (err, results) {
  // err:
  //  { [ReplyError: EXECABORT Transaction discarded because of previous errors.]
  //    name: 'ReplyError',
  //    message: 'EXECABORT Transaction discarded because of previous errors.',
  //    command: { name: 'exec', args: [] },
  //    previousErrors:
  //     [ { [ReplyError: ERR wrong number of arguments for 'set' command]
  //         name: 'ReplyError',
  //         message: 'ERR wrong number of arguments for \'set\' command',
  //         command: [Object] } ] }
});
```

We're not seeing this behavior at all. If one command in a multi transaction fails, it behaves no different than pipeline, we're not seeing it fail the whole transaction.

**Comment by DanielJoyce** [comment]
https://registry.yarnpkg.com/ioredis/-/ioredis-4.0.0.tgz#fabf1cf8724f14fd0885233cf2f4fbc6e1e59da2

From our yarn.lock file.

**Comment by luin** [comment]
Hi, this is an issue on the redis side:

```
127.0.0.1:6379> multi
OK
127.0.0.1:6379> hmset abc a b c
QUEUED
127.0.0.1:6379> set foo
(error) ERR wrong number of arguments for 'set' command
```
