### ISSUE TITLE
Issue Redis Proxy Connection

### ISSUE THREAD

**Issue by prakasa1904** [luin/ioredis#725]
Hi I have issue with proxy connection. My proxy not using tls. The connection always response error bellow:

```
MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/var/www/lite-2/mercurius/node_modules/ioredis/built/redis/event_handler.js:95:37)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)
```

any idea about this error ?

**Comment by prakasa1904** [comment]
when use redis-cli its working normal...

**Comment by luin** [comment]
Could you turn debug mode on (DEBUG=ioredis:* node yourapp) and post the logs here?

**Comment by prakasa1904** [comment]
debug output:

```
ioredis:redis status[HOST:PORT]: [empty] -> connecting +0ms
  ioredis:redis status[IP:PORT]: connecting -> connect +11ms
  ioredis:redis write command[IP:PORT]: 0 -> info([]) +2ms
  ioredis:redis status[IP:PORT]: connect -> close +4ms
  ioredis:connection reconnect in 50ms +0ms
  ioredis:redis status[IP:PORT]: close -> reconnecting +0ms
  ioredis:redis status[IP:PORT]: reconnecting -> connecting +51ms
  ioredis:redis status[IP:PORT]: connecting -> connect +4ms
  ioredis:redis write command[IP:PORT]: 0 -> info([]) +1ms
  ioredis:redis status[IP:PORT]: connect -> close +1ms
  ioredis:connection reconnect in 100ms +57ms
```

when I try this: `redis-cli -h <IP> -p <PORT` . Its fine

any idea about this isue ?

**Comment by prakasa1904** [comment]
fixed, my bad. My configuration is typo `enableReadyChek` and its just ignored by ioredis. My proxy deni info command.
