### ISSUE TITLE
Regression since 4.2.1

### ISSUE THREAD

**Issue by JSteunou** [luin/ioredis#759]
Since I tried to upgrade to 4.3.0 I have this error. I tracked it down. It appears since 4.2.1. With 4.2.0 I dont have this issue.

```
TypeError: Command.checkFlag is not a function
    at Redis.require.Redis.sendCommand (/opt/myproject/node_modules/ioredis/built/redis.js:561:21)
    at Redis.info (/opt/myproject/node_modules/ioredis/built/commander.js:121:21)
    at Redis.require.Redis._readyCheck (/opt/myproject/node_modules/ioredis/built/redis.js:387:10)
    at Socket.<anonymous> (/opt/myproject/node_modules/ioredis/built/redis/event_handler.js:36:18)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:10)

```

The command I'm using is `redisClient.flushdb()` with instance options  
```js
{
  host: "redis_project_test"
},
```
and `options.dropBufferSupport = true;`

I'm in dockerised environment

**Comment by JSteunou** [comment]
after removing my package-lock.json and install from scratch all node modules instead of trusting npm on `update` for update and `install package@version` for rollback it works again... This is sad
