### ISSUE TITLE
multi ReplyError is received as result instead of error

### ISSUE THREAD

**Issue by apmcodes** [luin/ioredis#788]
If wrong datatype is passed (like SET instead of LIST) to the below multi command then instead of error the returned result contains the ReplyError. 

```
            redis.multi()
                .rpoplpush(aipKey, aipKey)
                .lrange(aipKey, 0, -1)
                .exec((err, result) => {
                    console.log('err', err)
                    if (err) {
                        console.log('got error');
                        return;
                    }
                    console.log('result', result);
             }

```
Output
```
err null
result [ [ ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value
        at parseError (/work/git/nilbounce/verifier/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/work/git/nilbounce/verifier/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14) ],
  [ ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value
        at parseError (/work/git/nilbounce/verifier/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/work/git/nilbounce/verifier/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14) ] ]

```

**Comment by apmcodes** [comment]
Oops ... all the commands results are returned as an result array ...
