### ISSUE TITLE
cluster:  TypeError: Cannot read property 'sendCommand' of undefined

### ISSUE THREAD

**Issue by klinquist** [luin/ioredis#81]
Hi,
I'm seeing a crash of my app using the latest ioredis in cluster mode:
How can I help you debug this?   

/data/myModule/node_modules/ioredis/lib/cluster.js:357
      redis.sendCommand(command, stream);
           ^
TypeError: Cannot read property 'sendCommand' of undefined
    at tryConnection (/data/millarouter/node_modules/ioredis/lib/cluster.js:357:12)
    at Cluster.sendCommand (/data/millarouter/node_modules/ioredis/lib/cluster.js:324:3)
    at Cluster.keys (/data/millarouter/node_modules/ioredis/lib/commander.js:111:17)
    at cleanup (/data/millarouter/index.js:298:20)
    at null.<anonymous> (/data/millarouter/index.js:329:2)
    at wrapper [as _onTimeout] (timers.js:265:14)
    at Timer.listOnTimeout (timers.js:110:15)

**Comment by luin** [comment]
hi, are you using ioredis 1.5.4? I found a bug in 1.5.3 that may lead to this problem.

**Comment by klinquist** [comment]
a-ha - I am running 1.5.3.  I will upgrade and re-open if it reoccurs.  Thank you for the quick response.
