### ISSUE TITLE
always None of startup nodes is available

### ISSUE THREAD

**Issue by trojanliu** [luin/ioredis#832]
Error: None of startup nodes is available
  at Cluster.handleCloseEvent (/Working/testDemo/node_modules/ioredis/built/cluster/index.js:200:29)
  at Cluster.g (events.js:286:16)
  at emitNone (events.js:91:20)
  at Cluster.emit (events.js:185:7)
  at process.nextTick (/Working/testDemo/node_modules/ioredis/built/cluster/index.js:297:18)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by trojanliu** [comment]
version is the latest.
client = new Redis.Cluster(config.redis, {clusterRetryStrategy:null, redisOptions: config.redisOptions})

**Comment by smriti-d** [comment]
experiencing the sam issue, is there a workaround to it?
