### ISSUE TITLE
Elasticache Redis with TLS and Redis Auth gives ClusterAllFailedError

### ISSUE THREAD

**Issue by headlessme** [luin/ioredis#837]
I'm trying to get ioredis (version 4.9.1) to connect to an Elasticache cluster (default.redis4.0.cluster.on, version 4.0.10, Encryption in transit, Redis Auth, 1 shard, 3 nodes). 

This is how I'm trying to connect:

```javascript
const url = "redis://:<password-redacted>@clustercfg.<url-redacted>.use1.cache.amazonaws.com";
const clusterOptions = { redisOptions: { tls: { } } };
const redis = new Redis.Cluster([url], clusterOptions);
```

But I'm getting the following error repeatedly:

```
{ ClusterAllFailedError: Failed to refresh slots cache.
     at tryNode (/usr/src/app/node_modules/ioredis/built/cluster/index.js:326:31)
     at /usr/src/app/node_modules/ioredis/built/cluster/index.js:342:21
     at redis.cluster.utils_1.timeout (/usr/src/app/node_modules/ioredis/built/cluster/index.js:568:24)
     at run (/usr/src/app/node_modules/ioredis/built/utils/index.js:150:22)
     at tryCatcher (/usr/src/app/node_modules/standard-as-callback/lib/utils.js:10:19)
     at /usr/src/app/node_modules/standard-as-callback/index.js:31:35
     at process._tickCallback (internal/process/next_tick.js:68:7)
   lastNodeError:
    Error: Connection is closed.
        at close (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:102:25)
        at TLSSocket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:73:20)
        at Object.onceWrapper (events.js:277:13)
        at TLSSocket.emit (events.js:194:15)
        at TLSSocket.EventEmitter.emit (domain.js:441:20)
        at _handle.close (net.js:597:12)
        at TCP.done (_tls_wrap.js:388:7) }
```

Connecting works fine when using ioredis without the Cluster constructor, so I'm pretty sure the URL and the password are correct. This works but occasionally gives MOVED errors, which I think are expected:

```javascript
const redis = new Redis(url, { tls: { } });
```

Any clues to what I'm doing wrong?

**Comment by divyanagrath** [comment]
I'm getting similar error.

**Comment by headlessme** [comment]
I saw a similar issue that suggested adding a configuration option to override the DNS lookup. I tried adding: 

```javascript
const clusterOptions = {
    redisOptions: options,
    dnsLookup: (address, callback) => callback(null, address)
};
```

I'm still seeing the issue. Here's some logs with `DEBUG=ioredis:*` enabled.

```
2019-04-05T23:08:59.291Z ioredis:cluster Cluster is disconnected. Retrying after 1998ms
2019-04-05T23:08:59.291Z ioredis:cluster status: reconnecting -> connecting
2019-04-05T23:08:59.291Z ioredis:cluster resolved hostname clustercfg.<redacted>.use1.cache.amazonaws.com to IP clustercfg.<redacted>.use1.cache.amazonaws.com
2019-04-05T23:08:59.291Z ioredis:cluster:connectionPool Reset with [ { password: '<redacted>',
 host: 'clustercfg.<redacted>.use1.cache.amazonaws.com',
 port: 6379 } ]
2019-04-05T23:08:59.291Z ioredis:cluster:connectionPool Connecting to clustercfg.<redacted>.use1.cache.amazonaws.com:6379 as master
2019-04-05T23:08:59.291Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379]: [empty] -> wait
2019-04-05T23:08:59.291Z ioredis:cluster getting slot cache from clustercfg.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:08:59.291Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379]: wait -> connecting
2019-04-05T23:08:59.291Z ioredis:redis queue command[clustercfg.<redacted>.use1.cache.amazonaws.com:6379]: 0 -> cluster([ 'slots' ])
2019-04-05T23:08:59.291Z ioredis:cluster:subscriber selected a subscriber clustercfg.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:08:59.292Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: [empty] -> wait
2019-04-05T23:08:59.292Z ioredis:cluster:subscriber started
2019-04-05T23:08:59.297Z ioredis:redis status[10.0.3.62:6379]: connecting -> connect
2019-04-05T23:08:59.297Z ioredis:redis write command[10.0.3.62:6379]: 0 -> auth([ '<redacted>' ])
2019-04-05T23:08:59.297Z ioredis:redis write command[10.0.3.62:6379]: 0 -> info([])
2019-04-05T23:08:59.298Z ioredis:redis status[10.0.3.62:6379]: connect -> ready
2019-04-05T23:08:59.298Z ioredis:connection send 1 commands in offline queue
2019-04-05T23:08:59.298Z ioredis:redis write command[10.0.3.62:6379]: 0 -> cluster([ 'slots' ])
2019-04-05T23:08:59.299Z ioredis:cluster cluster slots result count: 1
2019-04-05T23:08:59.299Z ioredis:cluster cluster slots result [0]: slots 0~16383 served by <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:08:59.299Z ioredis:cluster:connectionPool Reset with [ { host:
  '<redacted>0001-001.<redacted>.use1.cache.amazonaws.com',
 port: 6379,
 readOnly: false } ]
2019-04-05T23:08:59.299Z ioredis:cluster:connectionPool Disconnect clustercfg.<redacted>.use1.cache.amazonaws.com:6379 because the node does not hold any slot
2019-04-05T23:08:59.299Z ioredis:cluster:connectionPool Connecting to <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 as master
2019-04-05T23:08:59.300Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379]: [empty] -> wait
2019-04-05T23:08:59.300Z ioredis:cluster status: connecting -> connect
2019-04-05T23:08:59.300Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379]: wait -> connecting
2019-04-05T23:08:59.300Z ioredis:redis queue command[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379]: 0 -> cluster([ 'info' ])
redis connected rediss://:<redacted>@clustercfg.<redacted>.use1.cache.amazonaws.com
2019-04-05T23:08:59.300Z ioredis:redis status[10.0.3.62:6379]: ready -> close
2019-04-05T23:08:59.301Z ioredis:connection skip reconnecting since the connection is manually closed.
2019-04-05T23:08:59.301Z ioredis:redis status[10.0.3.62:6379]: close -> end
2019-04-05T23:08:59.301Z ioredis:cluster:subscriber subscriber has left, selecting a new one...
2019-04-05T23:08:59.301Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: wait -> close
2019-04-05T23:08:59.301Z ioredis:connection skip reconnecting since the connection is manually closed.
2019-04-05T23:08:59.301Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: close -> end
2019-04-05T23:08:59.301Z ioredis:cluster:subscriber selected a subscriber <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:08:59.301Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: [empty] -> wait
2019-04-05T23:08:59.390Z ioredis:redis status[10.0.3.62:6379]: connecting -> connect
2019-04-05T23:08:59.390Z ioredis:redis write command[10.0.3.62:6379]: 0 -> info([])
2019-04-05T23:08:59.391Z ioredis:cluster Ready check failed (Error: Ready check failed: NOAUTH Authentication required.). Reconnecting...
2019-04-05T23:08:59.391Z ioredis:cluster status: connect -> disconnecting
2019-04-05T23:08:59.391Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: wait -> close
2019-04-05T23:08:59.391Z ioredis:connection skip reconnecting since the connection is manually closed.
2019-04-05T23:08:59.391Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: close -> end
2019-04-05T23:08:59.391Z ioredis:cluster:subscriber stopped
2019-04-05T23:08:59.391Z ioredis:cluster:connectionPool Reset with []
2019-04-05T23:08:59.391Z ioredis:cluster:connectionPool Disconnect <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 because the node does not hold any slot
2019-04-05T23:08:59.392Z ioredis:redis status[10.0.3.62:6379]: connect -> close
2019-04-05T23:08:59.392Z ioredis:connection skip reconnecting since the connection is manually closed.
2019-04-05T23:08:59.392Z ioredis:redis status[10.0.3.62:6379]: close -> end
2019-04-05T23:08:59.392Z ioredis:cluster status: disconnecting -> close
2019-04-05T23:08:59.392Z ioredis:cluster status: close -> reconnecting
2019-04-05T23:09:01.393Z ioredis:cluster Cluster is disconnected. Retrying after 2000ms
2019-04-05T23:09:01.393Z ioredis:cluster status: reconnecting -> connecting
2019-04-05T23:09:01.393Z ioredis:cluster resolved hostname clustercfg.<redacted>.use1.cache.amazonaws.com to IP clustercfg.<redacted>.use1.cache.amazonaws.com
2019-04-05T23:09:01.393Z ioredis:cluster:connectionPool Reset with [ { password: '<redacted>',
 host: 'clustercfg.<redacted>.use1.cache.amazonaws.com',
 port: 6379 } ]
2019-04-05T23:09:01.393Z ioredis:cluster:connectionPool Connecting to clustercfg.<redacted>.use1.cache.amazonaws.com:6379 as master
2019-04-05T23:09:01.393Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379]: [empty] -> wait
2019-04-05T23:09:01.393Z ioredis:cluster getting slot cache from clustercfg.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:09:01.393Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379]: wait -> connecting
2019-04-05T23:09:01.393Z ioredis:redis queue command[clustercfg.<redacted>.use1.cache.amazonaws.com:6379]: 0 -> cluster([ 'slots' ])
2019-04-05T23:09:01.393Z ioredis:cluster:subscriber selected a subscriber clustercfg.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:09:01.393Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: [empty] -> wait
2019-04-05T23:09:01.393Z ioredis:cluster:subscriber started
2019-04-05T23:09:01.400Z ioredis:redis status[10.0.3.62:6379]: connecting -> connect
2019-04-05T23:09:01.400Z ioredis:redis write command[10.0.3.62:6379]: 0 -> auth([ '<redacted>' ])
2019-04-05T23:09:01.400Z ioredis:redis write command[10.0.3.62:6379]: 0 -> info([])
2019-04-05T23:09:01.401Z ioredis:redis status[10.0.3.62:6379]: connect -> ready
2019-04-05T23:09:01.401Z ioredis:connection send 1 commands in offline queue
2019-04-05T23:09:01.401Z ioredis:redis write command[10.0.3.62:6379]: 0 -> cluster([ 'slots' ])
2019-04-05T23:09:01.402Z ioredis:cluster cluster slots result count: 1
2019-04-05T23:09:01.402Z ioredis:cluster cluster slots result [0]: slots 0~16383 served by <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:09:01.402Z ioredis:cluster:connectionPool Reset with [ { host:
  '<redacted>0001-001.<redacted>.use1.cache.amazonaws.com',
 port: 6379,
 readOnly: false } ]
2019-04-05T23:09:01.402Z ioredis:cluster:connectionPool Disconnect clustercfg.<redacted>.use1.cache.amazonaws.com:6379 because the node does not hold any slot
2019-04-05T23:09:01.402Z ioredis:cluster:connectionPool Connecting to <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 as master
2019-04-05T23:09:01.402Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379]: [empty] -> wait
2019-04-05T23:09:01.403Z ioredis:cluster status: connecting -> connect
2019-04-05T23:09:01.403Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379]: wait -> connecting
2019-04-05T23:09:01.403Z ioredis:redis queue command[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379]: 0 -> cluster([ 'info' ])
redis connected rediss://:<redacted>@clustercfg.<redacted>.use1.cache.amazonaws.com
2019-04-05T23:09:01.404Z ioredis:redis status[10.0.3.62:6379]: ready -> close
2019-04-05T23:09:01.404Z ioredis:connection skip reconnecting since the connection is manually closed.
2019-04-05T23:09:01.404Z ioredis:redis status[10.0.3.62:6379]: close -> end
2019-04-05T23:09:01.404Z ioredis:cluster:subscriber subscriber has left, selecting a new one...
2019-04-05T23:09:01.404Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: wait -> close
2019-04-05T23:09:01.404Z ioredis:connection skip reconnecting since the connection is manually closed.
2019-04-05T23:09:01.404Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: close -> end
2019-04-05T23:09:01.404Z ioredis:cluster:subscriber selected a subscriber <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:09:01.404Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: [empty] -> wait
2019-04-05T23:09:01.408Z ioredis:redis status[10.0.3.62:6379]: connecting -> connect
2019-04-05T23:09:01.408Z ioredis:redis write command[10.0.3.62:6379]: 0 -> info([])
2019-04-05T23:09:01.486Z ioredis:cluster Ready check failed (Error: Ready check failed: NOAUTH Authentication required.). Reconnecting...
2019-04-05T23:09:01.486Z ioredis:cluster status: connect -> disconnecting
2019-04-05T23:09:01.486Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: wait -> close
2019-04-05T23:09:01.486Z ioredis:connection skip reconnecting since the connection is manually closed.
2019-04-05T23:09:01.486Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: close -> end
2019-04-05T23:09:01.486Z ioredis:cluster:subscriber stopped
2019-04-05T23:09:01.486Z ioredis:cluster:connectionPool Reset with []
2019-04-05T23:09:01.486Z ioredis:cluster:connectionPool Disconnect <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 because the node does not hold any slot
2019-04-05T23:09:01.487Z ioredis:redis status[10.0.3.62:6379]: connect -> close
2019-04-05T23:09:01.487Z ioredis:connection skip reconnecting since the connection is manually closed.
2019-04-05T23:09:01.487Z ioredis:redis status[10.0.3.62:6379]: close -> end
2019-04-05T23:09:01.488Z ioredis:cluster status: disconnecting -> close
2019-04-05T23:09:01.488Z ioredis:cluster status: close -> reconnecting
2019-04-05T23:09:03.488Z ioredis:cluster Cluster is disconnected. Retrying after 2000ms
2019-04-05T23:09:03.488Z ioredis:cluster status: reconnecting -> connecting
2019-04-05T23:09:03.488Z ioredis:cluster resolved hostname clustercfg.<redacted>.use1.cache.amazonaws.com to IP clustercfg.<redacted>.use1.cache.amazonaws.com
2019-04-05T23:09:03.488Z ioredis:cluster:connectionPool Reset with [ { password: '<redacted>',
 host: 'clustercfg.<redacted>.use1.cache.amazonaws.com',
 port: 6379 } ]
2019-04-05T23:09:03.488Z ioredis:cluster:connectionPool Connecting to clustercfg.<redacted>.use1.cache.amazonaws.com:6379 as master
2019-04-05T23:09:03.489Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379]: [empty] -> wait
2019-04-05T23:09:03.489Z ioredis:cluster getting slot cache from clustercfg.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:09:03.489Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379]: wait -> connecting
2019-04-05T23:09:03.489Z ioredis:redis queue command[clustercfg.<redacted>.use1.cache.amazonaws.com:6379]: 0 -> cluster([ 'slots' ])
2019-04-05T23:09:03.489Z ioredis:cluster:subscriber selected a subscriber clustercfg.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:09:03.489Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: [empty] -> wait
2019-04-05T23:09:03.489Z ioredis:cluster:subscriber started
2019-04-05T23:09:03.494Z ioredis:redis status[10.0.3.62:6379]: connecting -> connect
2019-04-05T23:09:03.494Z ioredis:redis write command[10.0.3.62:6379]: 0 -> auth([ '<redacted>' ])
2019-04-05T23:09:03.494Z ioredis:redis write command[10.0.3.62:6379]: 0 -> info([])
2019-04-05T23:09:03.495Z ioredis:redis status[10.0.3.62:6379]: connect -> ready
2019-04-05T23:09:03.495Z ioredis:connection send 1 commands in offline queue
2019-04-05T23:09:03.495Z ioredis:redis write command[10.0.3.62:6379]: 0 -> cluster([ 'slots' ])
2019-04-05T23:09:03.496Z ioredis:cluster cluster slots result count: 1
2019-04-05T23:09:03.496Z ioredis:cluster cluster slots result [0]: slots 0~16383 served by <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:09:03.497Z ioredis:cluster:connectionPool Reset with [ { host:
  '<redacted>0001-001.<redacted>.use1.cache.amazonaws.com',
 port: 6379,
 readOnly: false } ]
2019-04-05T23:09:03.497Z ioredis:cluster:connectionPool Disconnect clustercfg.<redacted>.use1.cache.amazonaws.com:6379 because the node does not hold any slot
2019-04-05T23:09:03.497Z ioredis:cluster:connectionPool Connecting to <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 as master
2019-04-05T23:09:03.497Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379]: [empty] -> wait
2019-04-05T23:09:03.497Z ioredis:cluster status: connecting -> connect
2019-04-05T23:09:03.497Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379]: wait -> connecting
redis connected rediss://:<redacted>@clustercfg.<redacted>.use1.cache.amazonaws.com
2019-04-05T23:09:03.497Z ioredis:redis queue command[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379]: 0 -> cluster([ 'info' ])
2019-04-05T23:09:03.498Z ioredis:redis status[10.0.3.62:6379]: ready -> close
2019-04-05T23:09:03.498Z ioredis:connection skip reconnecting since the connection is manually closed.
2019-04-05T23:09:03.498Z ioredis:redis status[10.0.3.62:6379]: close -> end
2019-04-05T23:09:03.498Z ioredis:cluster:subscriber subscriber has left, selecting a new one...
2019-04-05T23:09:03.498Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: wait -> close
2019-04-05T23:09:03.498Z ioredis:connection skip reconnecting since the connection is manually closed.
2019-04-05T23:09:03.498Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: close -> end
2019-04-05T23:09:03.498Z ioredis:cluster:subscriber selected a subscriber <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:09:03.498Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: [empty] -> wait
2019-04-05T23:09:03.590Z ioredis:redis status[10.0.3.62:6379]: connecting -> connect
2019-04-05T23:09:03.590Z ioredis:redis write command[10.0.3.62:6379]: 0 -> info([])
2019-04-05T23:09:03.591Z ioredis:cluster Ready check failed (Error: Ready check failed: NOAUTH Authentication required.). Reconnecting...
2019-04-05T23:09:03.591Z ioredis:cluster status: connect -> disconnecting
2019-04-05T23:09:03.591Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: wait -> close
2019-04-05T23:09:03.591Z ioredis:connection skip reconnecting since the connection is manually closed.
2019-04-05T23:09:03.591Z ioredis:redis status[<redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: close -> end
2019-04-05T23:09:03.591Z ioredis:cluster:subscriber stopped
2019-04-05T23:09:03.591Z ioredis:cluster:connectionPool Reset with []
2019-04-05T23:09:03.591Z ioredis:cluster:connectionPool Disconnect <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379 because the node does not hold any slot
2019-04-05T23:09:03.592Z ioredis:redis status[10.0.3.62:6379]: connect -> close
2019-04-05T23:09:03.592Z ioredis:connection skip reconnecting since the connection is manually closed.
2019-04-05T23:09:03.592Z ioredis:redis status[10.0.3.62:6379]: close -> end
2019-04-05T23:09:03.592Z ioredis:cluster status: disconnecting -> close
2019-04-05T23:09:03.592Z ioredis:cluster status: close -> reconnecting
2019-04-05T23:09:05.593Z ioredis:cluster Cluster is disconnected. Retrying after 2000ms
2019-04-05T23:09:05.593Z ioredis:cluster status: reconnecting -> connecting
2019-04-05T23:09:05.593Z ioredis:cluster resolved hostname clustercfg.<redacted>.use1.cache.amazonaws.com to IP clustercfg.<redacted>.use1.cache.amazonaws.com
2019-04-05T23:09:05.593Z ioredis:cluster:connectionPool Reset with [ { password: '<redacted>',
 host: 'clustercfg.<redacted>.use1.cache.amazonaws.com',
 port: 6379 } ]
2019-04-05T23:09:05.593Z ioredis:cluster:connectionPool Connecting to clustercfg.<redacted>.use1.cache.amazonaws.com:6379 as master
2019-04-05T23:09:05.593Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379]: [empty] -> wait
2019-04-05T23:09:05.593Z ioredis:cluster getting slot cache from clustercfg.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:09:05.593Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379]: wait -> connecting
2019-04-05T23:09:05.593Z ioredis:redis queue command[clustercfg.<redacted>.use1.cache.amazonaws.com:6379]: 0 -> cluster([ 'slots' ])
2019-04-05T23:09:05.593Z ioredis:cluster:subscriber selected a subscriber clustercfg.<redacted>.use1.cache.amazonaws.com:6379
2019-04-05T23:09:05.593Z ioredis:redis status[clustercfg.<redacted>.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: [empty] -> wait
2019-04-05T23:09:05.593Z ioredis:cluster:subscriber started
2019-04-05T23:09:05.598Z ioredis:redis status[10.0.3.62:6379]: connecting -> connect
2019-04-05T23:09:05.599Z ioredis:redis write command[10.0.3.62:6379]: 0 -> auth([ '<redacted>' ])
2019-04-05T23:09:05.599Z ioredis:redis write command[10.0.3.62:6379]: 0 -> info([])
2019-04-05T23:09:05.600Z ioredis:redis status[10.0.3.62:6379]: connect -> ready
2019-04-05T23:09:05.600Z ioredis:connection send 1 commands in offline queue
2019-04-05T23:09:05.600Z ioredis:redis write command[10.0.3.62:6379]: 0 -> cluster([ 'slots' ])
2019-04-05T23:09:05.600Z ioredis:cluster cluster slots result count: 1
2019-04-05T23:09:05.600Z ioredis:cluster cluster slots result [0]: slots 0~16383 served by <redacted>0001-001.<redacted>.use1.cache.amazonaws.com:6379
redis connected rediss://:<redacted>@clustercfg.<redacted>.use1.cache.amazonaws.com
2019-04-05T23:09:05.601Z ioredis:cluster:connectionPool Reset with [ { host:
  '<redacted>0001-001.<redacted>.use1.cache.amazonaws.com',
 port: 6379,
 readOnly: false } ]
```

**Comment by headlessme** [comment]
@luin any ideas on this? It's causing real issues for us.

**Comment by headlessme** [comment]
I figured out this issue, it seems that passing the password in the URL to the cluster setup won't result in that password being used to connect to all the cluster nodes that get listed by querying the clustercfg node. In the end I parsed the password out of the URL myself and passed it into redisOptions manually. Seems like this could perhaps be done by default to avoid this error case?


Ended up with something like which is working so far!

```javascript
const url = "redis://:<password-redacted>@clustercfg.<url-redacted>.use1.cache.amazonaws.com";
const [, password] = (URL.parse(url).auth||'').split(':');
const clusterOptions = { redisOptions: { password: password, tls: { } } };
const redis = new Redis.Cluster([url], clusterOptions);
```

**Comment by williamwang1** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed after 7 days if no further activity occurs, but feel free to re-open a closed issue if needed.

u saved my day
