### ISSUE TITLE
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)

### ISSUE THREAD

**Issue by kerwin-ly** [luin/ioredis#851]
I encountered this issue and dont know how to debug it. Can anyone help me?Thanks in advance!
```
error: [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```
```js
const Redis = require("ioredis");
const { Store } = require("koa-session2");
 
class RedisStore extends Store {
    constructor() {
        super();
        this.redis = new Redis();
    }
 
    async get(sid, ctx) {
        let data = await this.redis.get(`SESSION:${sid}`);
        return JSON.parse(data);
    }
 
    async set(session, { sid =  this.getID(24), maxAge = 1000 * 60 * 60 } = {}, ctx) {
        try {
            console.log(`SESSION:${sid}`);
            // Use redis set EX to automatically drop expired sessions
            await this.redis.set(`SESSION:${sid}`, JSON.stringify(session), 'EX', maxAge / 1000);
        } catch (e) {}
        return sid;
    }
 
    async destroy(sid, ctx) {
        return await this.redis.del(`SESSION:${sid}`);
    }
}
 
module.exports = RedisStore;
```

**Comment by kerwin-ly** [comment]
fixed.I forget that my server was running on port 3000.When create instance `Redis`,just change the listening port `this.redis = new Redis(3000);`...
