### ISSUE TITLE
Error: Connection is closed when try to call `con.quit`

### ISSUE THREAD

**Issue by shlomisas** [luin/ioredis#874]
I'm creating a connection and after it's connected i'm trying to close it, but getting `Connection is closed` error.

```
const Redis = require('ioredis');

async function createConnection(){

    return new Promise((resolve, reject) => {
        const connectionName = 'test';

        const client = new Redis({
            connectionName,
            host: '127.0.0.1',
            port: '6379'
        });

        client.on('connect', () => {
            console.log(`Redis has connected for: ${connectionName}`);
            resolve(client);
        });

        client.on('ready', () => {
            console.log(`Redis is ready for: ${connectionName}`);
        });

        client.on('close', () => {
            console.log(`Redis has closed for: ${connectionName}`);
        });

        client.on('reconnecting', () => {
            console.log(`Redis is reconnecting for: ${connectionName}`);
        });

        client.on('end', () => {
            console.log(`Redis has ended for: ${connectionName}`);
        });

        client.on('error', (err) => {
            console.error(err);
        });
    });
}

(async () => {
    try{
        const con = await createConnection();
        await con.quit();
    }catch(e){
        console.error(e);
    }
})();
```

Here is the error: https://www.screencast.com/t/zAImB3bdVFwQ

```
Error: Connection is closed.
    at close (C:\personal\dev\beatsense\packages\realtime\node_modules\ioredis\built\redis\event_handler.js:102:25)
    at Socket.<anonymous> (C:\personal\dev\beatsense\packages\realtime\node_modules\ioredis\built\redis\event_handler.js:69:20)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:557:12)
Debugger attached.
Waiting for the debugger to disconnect...
```

Any idea?

**Comment by luin** [comment]
Could you enable the debug mode `DEBUG=ioredis:* node yourapp.js` and post the logs here. I tested on my side and the logs are:

```
➜ node test
Redis has connected for: test
Redis is ready for: test
Redis has closed for: test
Redis has ended for: test
```

**Comment by cameljava** [comment]
I have tested the same code, against aws redis(one master, two rep) cluster mode disabled. Even called conn.quit(), client still hanging there,

here is the debug log:
[ec2-user@ip-10-170-0-217 kt]$ node redis-test.js
  ioredis:redis status[master.redis-dev-drx.seorg1.apse2.cache.amazonaws.com:6379 (test)]: [empty] -> connecting +0ms
  ioredis:redis status[10.170.4.107:6379 (test)]: connecting -> connect +146ms
  ioredis:redis write command[10.170.4.107:6379 (test)]: 0 -> auth([ 'xxxxxxxxxx' ]) +1ms
  ioredis:redis write command[10.170.4.107:6379 (test)]: 0 -> info([]) +3ms
Redis has connected for: test
ready to test
  ioredis:redis write command[10.170.4.107:6379 (test)]: 0 -> quit([]) +1ms

**Comment by blueyestar** [comment]
Same problem here
