### ISSUE TITLE
error when trying to use sentinel outside of localhost

### ISSUE THREAD

**Issue by Karnich** [luin/ioredis#880]
Hi

This is my first time using sentinel. i got it working locally but when i run it on my kubernetes platform i get this error:
```
Error: All sentinels are unreachable. Retrying from scratch after 1ms. Last error: ERR unknown command `sentinel`, with args beginning with: `get-master-addr-by-name`, `mymaster`, 
2019-06-03T12:17:56.94509194Z     at connectToNext (/usr/src/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
2019-06-03T12:17:56.945096532Z     at /usr/src/node_modules/ioredis/built/connectors/SentinelConnector/index.js:93:21
2019-06-03T12:17:56.945099944Z     at /usr/src/node_modules/ioredis/built/connectors/SentinelConnector/index.js:127:24
2019-06-03T12:17:56.94510342Z     at tryCatcher (/usr/src/node_modules/standard-as-callback/built/utils.js:11:23)
2019-06-03T12:17:56.945106589Z     at /usr/src/node_modules/standard-as-callback/built/index.js:30:51
2019-06-03T12:17:56.945109714Z     at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

What does this mean exactly? is this an error that occures on the sentinel host or in my client container?

**Comment by luin** [comment]
The error indicated the server didn't recognize SENTINEL command. That is usually caused by using an old Redis version (older than 2.8).

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Karnich** [comment]
I have a duplicate environment variable which ment my new port for sentinel got overriden by the old port for redis -.-  my bad! problem solves
