### ISSUE TITLE
[ioredis] Unhandled error event

### ISSUE THREAD

**Issue by barakpx** [luin/ioredis#896]
ioredis cluster client will print out connection issues even if I register to error handler.

`console.error('[ioredis] Unhandled error event:', error.stack);`

Even when your cluster redis instance registered for 'error' or 'node error'.
Look like getInfoFromNode duplicates Redis instance, the current duplicate implementation does not close the event listeners. Any error on the cloned instance will fall to the console.log.

This is an issue as when there are connection problems the process prints out to the console and doesn't trigger the event on the cluster instance.

**Comment by kjr247** [comment]
Is this a new bug? Can I use an earlier version? What needs to be done?

**Comment by barakpx** [comment]
Not sure it is new - but when you clone the listeners when you duplicate the Redis instance I think we will get the right behavior.

**Comment by barakpx** [comment]
Created PR https://github.com/luin/ioredis/pull/899

**Comment by Kristoffer95** [comment]
I am having this error
`
Using ts-node version 8.10.1, typescript version 3.8.3
http://localhost:3000
[ioredis] Unhandled error event: Error: write EPIPE
    at WriteWrap.afterWrite (net.js:789:14)
[ioredis] Unhandled error event: Error: write EPIPE
    at WriteWrap.afterWrite (net.js:789:14)
[ioredis] Unhandled error event: Error: write EPIPE
    at WriteWrap.afterWrite (net.js:789:14)
[ioredis] Unhandled error event: Error: write EPIPE
    at WriteWrap.afterWrite (net.js:789:14)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
[ioredis] Unhandled error event: Error: write EPIPE
    at WriteWrap.afterWrite (net.js:789:14)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
`

**Comment by Kristoffer95** [comment]
https://github.com/luin/ioredis/issues/1121

**Comment by Ha2ryZhang** [comment]
Long Time no operation will report this error
```
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[ioredis] Unhandled error event: Error: connect ENETUNREACH 103.44.240.118:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```

**Comment by bakdakonusuruz** [comment]
Hi all, I'm having this error quite frequently

````
[ioredis] Unhandled error event: Error: write EPIPE
afterWriteDispatched (internal/stream_base_commons.js:156:25)
writeGeneric (internal/stream_base_commons.js:147:3)
Socket._writeGeneric (net.js:785:11)
Socket._write (net.js:797:8)
writeOrBuffer (_stream_writable.js:352:12)
Socket.Writable.write (_stream_writable.js:303:10)
Redis.sendCommand (/app/node_modules/ioredis/built/redis/index.js:659:33)
Redis.info (/app/node_modules/ioredis/built/commander.js:111:25)
Redis._readyCheck (/app/node_modules/ioredis/built/redis/index.js:475:10)
Socket.<anonymous> (/app/node_modules/ioredis/built/redis/event_handler.js:54:18)
Object.onceWrapper (events.js:421:28)
Socket.emit (events.js:327:22)
TCPConnectWrap.afterConnect [as oncomplete] (net.js:1132:10)
````

**Comment by zhuzhengjing** [comment]
[ioredis] Unhandled error event: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Redis.sendCommand (/root/app-service/node_modules/ioredis/built/redis/index.js:608:33)
    at Redis.info (/root/app-service/node_modules/ioredis/built/commander.js:124:21)
    at Redis._readyCheck (/root/app-service/node_modules/ioredis/built/redis/index.js:430:10)
    at Socket.<anonymous> (/root/app-service/node_modules/ioredis/built/redis/event_handler.js:47:18)
    at Object.onceWrapper (events.js:482:28)
    at Socket.emit (events.js:388:22)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1132:10)

**Comment by SirawichDev** [comment]
can you guys fixed it yet ?
