### ISSUE TITLE
[ioredis] Unhandled error event: Error: connect EINVAL 0.0.24.235 - Local (0.0.0.0:0)

### ISSUE THREAD

**Issue by mandaputtra** [luin/ioredis#915]
Hi, I got some strange error that I can't even understand here. The errors say like this. only when using `pubsub` any ideas what are wrong here? 

Linux Mint 18.4
ioredis 4.10
redis-cli 4.0.9

```js
{ Error: connect EINVAL 0.0.24.235 - Local (0.0.0.0:0)
    at internalConnect (net.js:881:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1028:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:59:10)
  errno: 'EINVAL',
  code: 'EINVAL',
  syscall: 'connect',
  address: '0.0.24.235' }

```

My Code :

```js
const Redis = require('ioredis')

const redisConfig = {
  port: process.env.REDIS_PORT || 6379,
  host: process.env.REDIS_HOST || '0.0.0.0'
}

const redis = new Redis(redisConfig)
const pub = new Redis(redisConfig)

redis.subscribe('chat', (err, count) => {
  if (err) throw err
})

redis.subscribe('notifications', (err, count) => {
  if (err) throw err
})

exports.sendMessage = message => {
  const str = JSON.stringify(message) // :receiver, :sender, :message
  pub.publish('chat', str)
}
exports.sendNotifications = notif => pub.publish('notifications', notif)
exports.redis = redis
```

Thanks

**Comment by mandaputtra** [comment]
```js
const Redis = require('ioredis')

const redisConfig = {
  port: 6379,
  host: '0.0.0.0'
}

const redis = new Redis(redisConfig)
const pub = new Redis(redisConfig)

redis.subscribe('chat', (err, count) => {
  if (err) throw err
})

redis.subscribe('notifications', (err, count) => {
  if (err) throw err
})

exports.sendMessage = message => {
  const str = JSON.stringify(message) // :receiver, :sender, :message
  pub.publish('chat', str)
}
exports.sendNotifications = notif => pub.publish('notifications', notif)
exports.redis = redis
```

Change the code without `process.env` it works

**Comment by trajano** [comment]
You have to use the `??` operator.  However, I am getting a similar error to you but on Redis Commander.
