### ISSUE TITLE
exports.useColors is not a function

### ISSUE THREAD

**Issue by P4sca1** [luin/ioredis#924]
The following error exists since `4.11.0`. `4.10.4` works fine.
The error occurs on application startup.

```
/home/pascal/code/api/node_modules/follow-redirects/node_modules/debug/src/debug.js:120
  debug.useColors = exports.useColors();
                            ^
TypeError: exports.useColors is not a function
    at Function.createDebug (/home/pascal/code/api/node_modules/follow-redirects/node_modules/debug/src/debug.js:120:29)
    at Object.genDebugFunction [as Debug] (/home/pascal/code/api/node_modules/ioredis/built/utils/debug.js:50:31)
    at Object.<anonymous> (/home/pascal/code/api/node_modules/ioredis/built/DataHandler.js:7:23)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by luin** [comment]
Did you specify a version for "debug" explicitly in your package.json? ioredis upgrade "debug" internally, so you may encounter this problem if you didn't add "debug" as a dependency explicitly in the package.json.

**Comment by P4sca1** [comment]
I specified the following under `dependencies` in my `package.json`:
`"debug": "^4.1.1",`

**Comment by luin** [comment]
Please make sure the version of the installed "debug" is "^4.1.1" (by checking out node_modules/debug/package.json), or you need to run `npm install` to update all packages.

**Comment by P4sca1** [comment]
Sorry for the late answer.
`node_modules/debug/package.json` states stat version `4.1.1` is installed.
I ran `npm install`.

**Comment by luin** [comment]
Could you provide a repo containing a minimum project that can reproduce the exception?

**Comment by P4sca1** [comment]
I was not able to reproduce the issue with a minimum project.
Are there any changes from `4.10.4` to `4.11.0` that could cause such issues?

**Comment by luin** [comment]
The only change related to this issue is the "debug" package was upgraded in 4.11.0. The reason I thought this issue was caused by using a wrong version of "debug" is that in the latest version of "debug", there isn't `/src/debug.js` file that showed in the error stack.

**Comment by P4sca1** [comment]
Maybe it is because other addons depend on an older version and those are getting mixed up somehow?

**Comment by luin** [comment]
@P4sca1 What do you get for `npm ls`? Could you post it here? I think it's probably caused by package.json and package-lock.json were out of sync.
