### ISSUE TITLE
SentinelIterator throws error after upgrade from v3 to v4

### ISSUE THREAD

**Issue by haimomesi** [luin/ioredis#936]
I get this error after upgrading to the latest version. Sentinels are properly configured.

```
TypeError: Cannot add property 3, object is not extensible
    at Array.push (<anonymous>)
    at SentinelIterator.add (/Users/mantubeezz/bitbucket/bmi/server/node_modules/ioredis/built/connectors/SentinelConnector/SentinelIterator.js:31:24)
    at result.map.forEach.sentinel (/Users/mantubeezz/bitbucket/bmi/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:126:47)
    at Array.forEach (<anonymous>)
    at client.sentinel (/Users/mantubeezz/bitbucket/bmi/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:120:18)
    at tryCatcher (/Users/mantubeezz/bitbucket/bmi/server/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/Users/mantubeezz/bitbucket/bmi/server/node_modules/standard-as-callback/built/index.js:19:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Changing this line from

https://github.com/luin/ioredis/blob/e593e349fd2811eed2f1a369ffb3a06205909482/lib/connectors/SentinelConnector/SentinelIterator.ts#L42

to 

`this.sentinels = [...this.sentinels, sentinel];`

fixed it for me. I wonder why nobody else is getting this :/

**Comment by luin** [comment]
Thank you for pointing this out. This issue is caused by passing an option that was handled by `Object.preventExtensions` so that `Array#push()` fails. I'll create a fix to make sure that the original options are immutable. However, I checked the code of v3, it seems there also has a `#push` here https://github.com/luin/ioredis/blob/v3.2.2/lib/connectors/sentinel_connector.js#L120, so it seems that v3 should have the same issue.

**Comment by haimomesi** [comment]
I've upgraded from v3.2.1 but still, that code lies there as well.
Thank you for the quick reply. Looking forward for the fix 🥇
