### ISSUE TITLE
ioredis(bull.js) can't connect to redis on private network, but redis-cli works

### ISSUE THREAD

**Issue by r3wt** [luin/ioredis#953]
**version info**
ioredis: `4.14.0`
node: `10.15.3`
ubuntu: `18.04`
redis: `4.0.9`

I have already read a similar thread, and followed the debug instructions for ioredis. I also tried both the `ip address`, and also a named host(by defining in `/etc/hosts`. both result in the same problem. below is an excerpt from the error log.
```
error   [8/27/2019, 8:08:25 PM] redis(subscriber) experienced an error { Error: connect ETIMEDOUT
    at Socket.<anonymous> (/<redacted path>/node_modules/ioredis/built/redis/index.js:275:31)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:440:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) errorno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'connect' }
2019-08-27T20:08:25.007Z ioredis:redis status[<redacted ip>:6379]: connecting -> close
2019-08-27T20:08:25.010Z ioredis:connection reconnect in 100ms
2019-08-27T20:08:25.010Z ioredis:redis status[<redacted ip>:6379]: close -> reconnecting
2019-08-27T20:08:25.111Z ioredis:redis status[<redacted ip>:6379]: reconnecting -> connecting
2019-08-27T20:08:25.114Z ioredis:redis status[<redacted ip>:6379]: connecting -> connect
2019-08-27T20:08:25.115Z ioredis:redis write command[<redacted ip>:6379]: 0 -> info([])
2019-08-27T20:08:25.118Z ioredis:redis status[<redacted ip>:6379]: connect -> ready
2019-08-28T02:32:56.933Z ioredis:redis status[ciserro-redis-1:6379]: [empty] -> connecting
2019-08-28T02:32:56.935Z ioredis:redis status[ciserro-redis-1:6379]: [empty] -> connecting
2019-08-28T02:32:56.939Z ioredis:redis queue command[ciserro-redis-1:6379]: 0 -> info([])
2019-08-28T02:32:57.848Z ioredis:redis status[<redacted ip>:6379]: connecting -> connect
2019-08-28T02:32:57.849Z ioredis:redis write command[<redacted ip>:6379]: 0 -> info([])
2019-08-28T02:32:57.853Z ioredis:redis status[<redacted ip>:6379]: connecting -> connect
2019-08-28T02:32:57.854Z ioredis:redis write command[<redacted ip>:6379]: 0 -> info([])
2019-08-28T02:32:57.875Z ioredis:redis status[<redacted ip>:6379]: connect -> ready
2019-08-28T02:32:57.876Z ioredis:connection send 1 commands in offline queue
2019-08-28T02:32:57.877Z ioredis:redis write command[<redacted ip>:6379]: 0 -> info([])
2019-08-28T02:32:57.879Z ioredis:redis status[<redacted ip>:6379]: connect -> ready
```
I'm hoping to get some insight on what the problem might be.

**Comment by knoxcard** [comment]
@r3wt - close ticket?

Also, maybe you need this in your code somewhere?

```
redis.on('connect', function() {
  /* then run your logic */
})
```

**Comment by r3wt** [comment]
@knoxcard yes, i forgot i had open this card. the issue was coming from an error received by the client INVALID SCRIPT
