### ISSUE TITLE
Redis connection to localhost periodically closes itself and fails to reconnect

### ISSUE THREAD

**Issue by sakekasi** [luin/ioredis#967]
Hi All,

My redis connection to localhost will occasionally close itself, try to reconnect and proceed to hit a connection refused error from the server. The server is definitely running (tested w/ redis-cli, and through the library), but this still happens. Any advice as to what I should do?

I have attached a trace of what's happening below

```
2019-09-18T16:56:24.946Z ioredis:redis write command[127.0.0.1:6379]: 0 -> zincrby([ 'shift:statistics:responseTimeMs',
  '7.000382',
  'sumsq',
  [length]: 3 ])
[bugsnag] 8 session(s) reported
2019-09-18T16:57:44.256Z ioredis:redis status[127.0.0.1:6379]: ready -> close
2019-09-18T16:57:44.256Z ioredis:connection reconnect in 50ms
2019-09-18T16:57:44.256Z ioredis:redis status[127.0.0.1:6379]: close -> reconnecting
2019-09-18T16:57:44.256Z ioredis:redis status[127.0.0.1:6379]: ready -> close
2019-09-18T16:57:44.256Z ioredis:connection reconnect in 50ms
2019-09-18T16:57:44.256Z ioredis:redis status[127.0.0.1:6379]: close -> reconnecting
2019-09-18T16:57:44.306Z ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting
2019-09-18T16:57:44.307Z ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting
2019-09-18T16:57:44.307Z ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
2019-09-18T16:57:44.308Z ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
2019-09-18T16:57:44.308Z ioredis:redis status[127.0.0.1:6379]: connecting -> close
2019-09-18T16:57:44.308Z ioredis:connection reconnect in 100ms
2019-09-18T16:57:44.308Z ioredis:redis status[127.0.0.1:6379]: close -> reconnecting
2019-09-18T16:57:44.308Z ioredis:redis status[127.0.0.1:6379]: connecting -> close
2019-09-18T16:57:44.308Z ioredis:connection reconnect in 100ms
2019-09-18T16:57:44.308Z ioredis:redis status[127.0.0.1:6379]: close -> reconnecting
2019-09-18T16:57:44.408Z ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting
2019-09-18T16:57:44.409Z ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting
2019-09-18T16:57:44.409Z ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
2019-09-18T16:57:44.409Z ioredis:connection error: Error: connect ECONNREFUSED 127.0.0.1:6379
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
2019-09-18T16:57:44.409Z ioredis:redis status[127.0.0.1:6379]: connecting -> close
2019-09-18T16:57:44.409Z ioredis:connection reconnect in 150ms
2019-09-18T16:57:44.409Z ioredis:redis status[127.0.0.1:6379]: close -> reconnecting
2019-09-18T16:57:44.410Z ioredis:redis status[127.0.0.1:6379]: connecting -> close
2019-09-18T16:57:44.410Z ioredis:connection reconnect in 150ms
2019-09-18T16:57:44.410Z ioredis:redis status[127.0.0.1:6379]: close -> reconnecting
2019-09-18T16:57:44.559Z ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting
2019-09-18T16:57:44.560Z ioredis:redis status[127.0.0.1:6379]: reconnecting -> connecting
2019-09-18T16:57:44.560Z ioredis:redis status[127.0.0.1:6379]: connecting -> connect
2019-09-18T16:57:44.560Z ioredis:redis write command[127.0.0.1:6379]: 0 -> info([ [length]: 0 ])
2019-09-18T16:57:44.561Z ioredis:redis status[127.0.0.1:6379]: connecting -> connect
2019-09-18T16:57:44.561Z ioredis:redis write command[127.0.0.1:6379]: 0 -> info([ [length]: 0 ])
2019-09-18T16:57:44.570Z ioredis:redis Redis server still loading, trying again in 1000ms
2019-09-18T16:57:44.570Z ioredis:redis Redis server still loading, trying again in 1000ms
2019-09-18T16:57:45.571Z ioredis:redis write command[127.0.0.1:6379]: 0 -> info([ [length]: 0 ])
2019-09-18T16:57:45.571Z ioredis:redis write command[127.0.0.1:6379]: 0 -> info([ [length]: 0 ])
2019-09-18T16:57:45.571Z ioredis:redis status[127.0.0.1:6379]: connect -> ready
2019-09-18T16:57:45.571Z ioredis:connection subscribe 1 channels
2019-09-18T16:57:45.571Z ioredis:redis write command[127.0.0.1:6379]: 0 -> subscribe([ 'shift:data:bantix:updates', [length]: 1 ])
2019-09-18T16:57:45.572Z ioredis:redis status[127.0.0.1:6379]: connect -> ready
2019-09-18T16:57:45.572Z ioredis:connection resend 0 unfulfilled commands
```

**Comment by knoxcard** [comment]
can u post your code? 
Are you connecting to "localhost" or "0.0.0.0" or "127.0.0.1"?
_Always use IP address, DNS lookups are slower..._

**Comment by sakekasi** [comment]
Thank you for the quick response. I appreciate it!

Can't post my code unfortunately, but I am using '127.0.0.1'

**Comment by sakekasi** [comment]
If that doesn't help, I can try and come up with a clean snippet

**Comment by knoxcard** [comment]
Yes, please post snippet.
