### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Connection is closed.  event_handler.js:115:25

### ISSUE THREAD

**Issue by Apollon77** [luin/ioredis#971]
Some users of my project which is using ioredis current version  (npm latest) got:

```
UnhandledPromiseRejectionWarning: Error: Connection is closed. 
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:115:25) 
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:82:20) at Object.onceWrapper (events.js:315:30) at emitOne (events.js:116:13) 
at Socket.emit (events.js:211:7) 
at TCP._handle.close [as _onclose] (net.js:561:12)(node:2345) 

UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2345) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

On my host the line number lead me to 

```
        self.flushQueue(new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));
```
Is there abug on your side? I'm not that fit in Promises and stuff.

Thank you having a look.

**Comment by Apollon77** [comment]
I think I got it ... I use quit now and hope that it is gone then ....

**Comment by Apollon77** [comment]
Sorry, also with removing "disconnect" calls after quit it still appers sometime.

My main question is how "reject" is really handled here for the command ... Is there somehting that "converts" this into callback style error responses?

**Comment by Apollon77** [comment]
Ok, I found the relevant command (it were "publish"s) and added a "catch(err =>{})" ... so it works. DOn't kniw if it should be that way ... maybe add it to the documentation?

**Comment by Mahmoud-Abd-Alhadi** [comment]
> Ok, I found the relevant command (it were "publish"s) and added a "catch(err =>{})" ... so it works. DOn't kniw if it should be that way ... maybe add it to the documentation?

@Apollon77 , Can you please describe what have you done exactly?

**Comment by Apollon77** [comment]
basically as said ...

client.publish(id, message).catch(_err => {});

**Comment by joebowbeer** [comment]
I am seeing what looks like the same issue with an ElastiCache  cluster:

```
020-06-21T23:31:44.314Z ioredis:cluster status: ready -> disconnecting
2020-06-21T23:31:44.314Z ioredis:cluster:subscriber stopped
2020-06-21T23:31:44.315Z ioredis:redis write command[]: 0 -> quit([])
2020-06-21T23:31:44.315Z ioredis:redis status[cluster-staging-0001-002]: wait -> connecting
2020-06-21T23:31:44.315Z ioredis:redis status[cluster-staging-0001-003]: wait -> connecting
2020-06-21T23:31:44.316Z ioredis:cluster status: ready -> disconnecting
2020-06-21T23:31:44.316Z ioredis:redis status[cluster-staging-0001-002]: wait -> close
2020-06-21T23:31:44.316Z ioredis:connection skip reconnecting since the connection is manually closed.
2020-06-21T23:31:44.316Z ioredis:redis status[cluster-staging-0001-002]: close -> end
2020-06-21T23:31:44.316Z ioredis:cluster:subscriber stopped
2020-06-21T23:31:44.316Z ioredis:redis write command[]: 0 -> quit([])
2020-06-21T23:31:44.316Z ioredis:redis status[cluster-staging-0001-002]: wait -> connecting
2020-06-21T23:31:44.317Z ioredis:redis status[cluster-staging-0001-003]: wait -> connecting
2020-06-21T23:31:44.317Z ioredis:redis status[cluster-staging-0001-002]: connecting -> end
2020-06-21T23:31:44.317Z ioredis:redis status[cluster-staging-0001-003]: connecting -> end
2020-06-21T23:31:44.317Z ioredis:redis status[cluster-staging-0001-002]: connecting -> end
2020-06-21T23:31:44.318Z ioredis:redis status[cluster-staging-0001-003]: connecting -> end
2020-06-21T23:31:44.318Z ioredis:cluster:connectionPool Remove cluster-staging-0001-002
2020-06-21T23:31:44.318Z ioredis:cluster:connectionPool Remove cluster-staging-0001-003
2020-06-21T23:31:44.318Z ioredis:cluster:connectionPool Remove cluster-staging-0001-002
2020-06-21T23:31:44.318Z ioredis:cluster:connectionPool Remove cluster-staging-0001-003
queue shutdown complete
2020-06-21T23:31:44.319Z ioredis:redis status[]: ready -> close
2020-06-21T23:31:44.319Z ioredis:connection skip reconnecting since the connection is manually closed.
2020-06-21T23:31:44.319Z ioredis:redis status[]: close -> end
2020-06-21T23:31:44.319Z ioredis:cluster:connectionPool Remove cluster-staging-0001-001
2020-06-21T23:31:44.319Z ioredis:cluster status: disconnecting -> close
2020-06-21T23:31:44.320Z ioredis:redis status[]: ready -> close
2020-06-21T23:31:44.320Z ioredis:connection skip reconnecting since the connection is manually closed.
2020-06-21T23:31:44.320Z ioredis:redis status[]: close -> end
2020-06-21T23:31:44.320Z ioredis:cluster:connectionPool Remove cluster-staging-0001-001
2020-06-21T23:31:44.320Z ioredis:cluster status: disconnecting -> close
Redis connection close
2020-06-21T23:31:44.321Z ioredis:cluster status: close -> end
2020-06-21T23:31:44.336Z ioredis:connection error: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:609:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1547:19)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: 'cluster-staging-0001-002',
  port: 6379,
  localAddress: undefined
}
2020-06-21T23:31:44.337Z ioredis:redis status[cluster-staging-0001-002]: connecting -> close
2020-06-21T23:31:44.338Z ioredis:connection skip reconnecting since the connection is manually closed.
2020-06-21T23:31:44.338Z ioredis:redis status[cluster-staging-0001-002]: close -> end
(node:1) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:179:25)
    at TLSSocket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:146:20)
    at Object.onceWrapper (events.js:422:26)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at TCP.done (_tls_wrap.js:567:7)
```

**Comment by ajendrex** [comment]
Hi!

I'm trying to connect to an elasticache served redis cluster from a pod within an EKS node and having this error:

```
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
[ioredis] Unhandled error event: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:617:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1544:19)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
```

I'm a little lost here, but, does anyone know what could it be / how to solve this?
I'm using the main endpoint to connect to the cluster...

**Comment by Apollon77** [comment]
@ajendrex Hm the issue is closed ... and you come with a completely different error case and message ... makes it sense to post it here? Maybe a new issue is much better?

**Comment by RahulSanskrityayan** [comment]
Hi @Apollon77  i am also facing similar issue . can you please guide where this change needs to be done.

basically as said ...
client.publish(id, message).catch(_err => {});

do we need to replace the below line with 
self.flushQueue(new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));  as the error points to this line only.

Your help will be highly appreciated .

Thanks,
Rahul S

**Comment by Apollon77** [comment]
We did not patched the ioredis itself, but really made sure to catch all relevant errors. And in fact it was the .ctah as above in our code. Each  Redis command can fail ...
