### ISSUE TITLE
etimeout error does not show the IP/port that fails to connect to

### ISSUE THREAD

**Issue by ORESoftware** [luin/ioredis#975]
I see this in my logs:

```console
ntrs error: { Error: connect ETIMEDOUT
    at Socket.<anonymous> (/root/interos/repos/ntrs-cli/node_modules/ioredis/built/redis/index.js:275:31)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:422:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) errorno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'connect' }
```

but sadly, it does not show which IP/DNS/Port it fails to connect to. Contrast the above, with a better stack trace like so:

```console
lmx client error: { Error: connect ECONNREFUSED 172.31.9.171:6970
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  [stack]: 'Error: connect ECONNREFUSED 172.31.9.171:6970\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)',
  [message]: 'connect ECONNREFUSED 172.31.9.171:6970',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.31.9.171',
  port: 6970 }

```

so I think you know what to do, if it's possible to do so. thanks.

**Comment by ORESoftware** [comment]
bump
