### ISSUE TITLE
Cannot parse the db number correctly

### ISSUE THREAD

**Issue by ORESoftware** [luin/ioredis#976]
I am getting this error:

```console
{ ReplyError: ERR DB index is out of range
    at parseError (/root/interos/repos/ntrs-cli/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/root/interos/repos/ntrs-cli/node_modules/redis-parser/lib/parser.js:302:14) command: { name: 'select', args: [ '20127' ] } }
```

here is what I have:

```js
const client_db0 = new Redis(`redis://${conf["platform-build.public-dns"]}:6379/0`);
const client_db1 = new Redis(`redis://${conf["platform-build.public-dns"]}:6379/1`);
const client_db2 = new Redis(`redis://${conf["platform-build.public-dns"]}:6379/2`);
const client_db3 = new Redis(`redis://${conf["platform-build.public-dns"]}:6379/3`);
```

**Comment by ORESoftware** [comment]
it is due to the extra whitespace here:

```
 'platform-build.public-dns': ' 127.0.0.1',
```

that sucks

**Comment by tuananh** [comment]
that error is quite misleading

**Comment by ORESoftware** [comment]
I assume the error: `command: { name: 'select', args: [ '20127' ] } ` is somehow intepreting 

```console
' 127.0.0.1:6379:1'   # note first char as whitespace
```
as db number `20127` somehow?  weird parsing

**Comment by tuananh** [comment]
because space is encode to `%20` so it becomes 'redis://%20127.0.0.1:6379/1'
