### ISSUE TITLE
egg-redis客户端每次不到10分钟，就报ERR server closed connection 

### ISSUE THREAD

**Issue by huenchao** [luin/ioredis#986]
我用egg-redis插件来作为redis客户端，每次超过10分钟左右，redis就会被断开，并且没有重链机制，并且报错。错误如下：
```
2019-10-07 15:54:05,764 ERROR 33651 [egg-redis] client error: Error: Command queue state error. If you can reproduce this, please report it. Last error: ERR server closed connection
2019-10-07 15:54:05,774 ERROR 33651 nodejs.Error: Command queue state error. If you can reproduce this, please report it. Last error: ERR server closed connection
    at DataHandler.shiftCommand (/Users/huenchao/common/egg-test/node_modules/ioredis/built/DataHandler.js:164:27)
    at DataHandler.returnError (/Users/huenchao/common/egg-test/node_modules/ioredis/built/DataHandler.js:33:27)
    at JavascriptRedisParser.returnError (/Users/huenchao/common/egg-test/node_modules/ioredis/built/DataHandler.js:15:22)
    at JavascriptRedisParser.execute (/Users/huenchao/common/egg-test/node_modules/redis-parser/lib/parser.js:542:14)
    at Socket.DataHandler.redis.stream.on.data (/Users/huenchao/common/egg-test/node_modules/ioredis/built/DataHandler.js:25:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
pid: 33651
hostname: huenchaodeMacBook-Pro.local

Context
**Node Version10.13.1:
**Egg Version2.6.1:
**Plugin Nameegg-redis:
**Plugin Version2.4.0:
**Platform macos:

**Comment by groot9325** [comment]
any update? did your fix it? @huenchao
